/** Auto-generated by scripts/build-manifest.ts — do not edit. */
import type { SpellingManifest } from "../src/types.js";
import manifestJson from "./manifest.json" with { type: "json" };

export const SPELLING_MANIFEST: SpellingManifest = manifestJson as SpellingManifest;
export const SPELLING_MANIFEST_VERSION = 1;
