import type { FeatureRegistryEntry } from "./types";

/**
 * Feature Registry scaffold (Sprint 0 · S0-T03).
 * Visibility follows Phase 9 Migration Blueprint + Phase 9 naming amendment.
 * Speech is the only wedgeEligible hero for MVP freeze.
 */
export const V2_FEATURE_REGISTRY: readonly FeatureRegistryEntry[] = [
  // —— Shells ——
  {
    id: "front_door",
    purpose: "First-session Speech-first journey before login walls.",
    category: "shell",
    discoveryStage: "hero",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "front_door",
    routeOwner: ["/front-door"],
    wedgeEligible: false,
  },
  {
    id: "today",
    purpose: "Companion home that presents one Mission.",
    category: "shell",
    discoveryStage: "hero",
    navOwner: "today",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "today",
    routeOwner: ["/today"],
    wedgeEligible: false,
  },
  {
    id: "ask_amy",
    purpose: "Text guide that discovers tools via Tool Registry only.",
    category: "shell",
    discoveryStage: "hero",
    navOwner: "ask_amy",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "ask_amy",
    routeOwner: ["/ask-amy", "/assistant"],
    wedgeEligible: false,
  },
  {
    id: "for_child",
    purpose: "Treasury shell for [Child] — discoverable modules, not Front Door.",
    category: "shell",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "for_child",
    routeOwner: ["/for-child", "/parenting-hub"],
    wedgeEligible: false,
  },
  {
    id: "premium",
    purpose: "Speech premium promise after a win or limit — never on Front Door steps.",
    category: "shell",
    discoveryStage: "hero",
    navOwner: "account",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "premium",
    routeOwner: ["/pricing"],
    wedgeEligible: false,
  },

  // —— Hero wedge (Speech) ——
  {
    id: "speech_coach",
    purpose: "Core speech practice path for Today Mission and Front Door WOW.",
    category: "talk_speech",
    discoveryStage: "hero",
    navOwner: "for_child",
    askAmyHandoff: "speech_only_v2",
    premiumRole: "soft_gate",
    analyticsOwner: "speech",
    routeOwner: [
      "/speech-coach",
      "/speech-coach/talk",
      "/speech-coach/live-session",
      "/speech-coach-v2",
      "/speech-coach-v2/session",
    ],
    wedgeEligible: true,
  },
  {
    id: "talking_amy",
    purpose: "Age-appropriate speech WOW / practice companion.",
    category: "talk_speech",
    discoveryStage: "hero",
    navOwner: "for_child",
    askAmyHandoff: "speech_only_v2",
    premiumRole: "soft_gate",
    analyticsOwner: "speech",
    routeOwner: ["/talking-amy"],
    wedgeEligible: true,
  },

  // —— Discoverable treasury ——
  {
    id: "school_morning_flow",
    purpose: "Calm school-morning routine helper.",
    category: "calm_days",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "routines",
    routeOwner: ["/school-morning-flow"],
    wedgeEligible: false,
  },
  {
    id: "smart_math_tricks",
    purpose: "Visual math tricks practice.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/smart-math-tricks"],
    wedgeEligible: false,
  },
  {
    id: "phonics",
    purpose: "Reading / phonics practice.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/phonics"],
    wedgeEligible: false,
  },
  {
    id: "study",
    purpose: "Study zone curriculum surface.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/study"],
    wedgeEligible: false,
  },
  {
    id: "discovery_worlds",
    purpose: "Exploration worlds for curiosity play.",
    category: "play",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "discovery",
    routeOwner: ["/discovery-worlds", "/worlds/:slug"],
    wedgeEligible: false,
  },
  {
    id: "animal_world",
    purpose: "Animal discovery play mode.",
    category: "play",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "discovery",
    routeOwner: ["/animal-world"],
    wedgeEligible: false,
  },
  {
    id: "rhymes",
    purpose: "Rhymes and story-adjacent audio play.",
    category: "play",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "stories",
    routeOwner: ["/rhymes"],
    wedgeEligible: false,
  },
  {
    id: "games",
    purpose: "Games hub and wallet play.",
    category: "play",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "games",
    routeOwner: ["/games"],
    wedgeEligible: false,
  },
  {
    id: "rewards",
    purpose: "Rewards after earnings.",
    category: "play",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "games",
    routeOwner: ["/rewards"],
    wedgeEligible: false,
  },
  {
    id: "how_library",
    purpose: "How? library answers for kids' questions.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/answer-to-kids-how"],
    wedgeEligible: false,
  },
  {
    id: "amy_coach",
    purpose: "Parent coaching sessions.",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "parent_support",
    routeOwner: ["/amy-coach"],
    wedgeEligible: false,
  },
  {
    id: "amy_ai_tutor",
    purpose: "Quick tutor for learning help.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/amy-ai-tutor"],
    wedgeEligible: false,
  },
  {
    id: "audio_lessons",
    purpose: "Audio lesson library.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/audio-lessons"],
    wedgeEligible: false,
  },
  {
    id: "nutrition",
    purpose: "Nutrition hub and caregiver share.",
    category: "care",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "nutrition",
    routeOwner: ["/nutrition", "/nutrition/share/:token"],
    wedgeEligible: false,
  },
  {
    id: "health_lab",
    purpose: "Health lab care tools.",
    category: "care",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "health",
    routeOwner: ["/health-lab"],
    wedgeEligible: false,
  },
  {
    id: "birth_sky",
    purpose: "Birth Sky / Amy Astro keepsake.",
    category: "keepsakes",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "birth_sky",
    routeOwner: ["/birth-sky"],
    wedgeEligible: false,
  },
  {
    id: "routines",
    purpose: "AI routine generator and runner.",
    category: "calm_days",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "routines",
    routeOwner: ["/routines", "/routines/generate", "/routines/:id"],
    wedgeEligible: false,
  },
  {
    id: "behavior",
    purpose: "Behavior tracking for parents.",
    category: "care",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "care",
    routeOwner: ["/behavior"],
    wedgeEligible: false,
  },
  {
    id: "life_skills",
    purpose: "Life skills practice.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/life-skills"],
    wedgeEligible: false,
  },
  {
    id: "event_prep",
    purpose: "Event / PTM prep helper.",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "post_pmf",
    premiumRole: "soft_gate",
    analyticsOwner: "parent_support",
    routeOwner: ["/event-prep"],
    wedgeEligible: false,
  },
  {
    id: "worksheet",
    purpose: "Worksheet studio.",
    category: "learn",
    discoveryStage: "discoverable",
    navOwner: "for_child",
    askAmyHandoff: "none",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/worksheet"],
    wedgeEligible: false,
  },
  {
    id: "progress",
    purpose: "Progress insights after data exists.",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "account",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "insights",
    routeOwner: ["/progress"],
    wedgeEligible: false,
  },
  {
    id: "insights",
    purpose: "Parent insights surface.",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "account",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "insights",
    routeOwner: ["/insights"],
    wedgeEligible: false,
  },
  {
    id: "parent_growth",
    purpose: "Parent growth coaching surface.",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "account",
    askAmyHandoff: "none",
    premiumRole: "soft_gate",
    analyticsOwner: "parent_support",
    routeOwner: ["/parent-growth"],
    wedgeEligible: false,
  },
  {
    id: "referrals",
    purpose: "Referral program (post-PMF attention).",
    category: "parent_support",
    discoveryStage: "discoverable",
    navOwner: "account",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "growth",
    routeOwner: ["/referrals"],
    wedgeEligible: false,
  },

  // —— Hidden ——
  {
    id: "abacus",
    purpose: "Abacus practice — keep alive by deep link until speech PMF.",
    category: "learn",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/abacus"],
    wedgeEligible: false,
  },
  {
    id: "spelling",
    purpose: "Spelling practice — deep link only until speech PMF.",
    category: "learn",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/spelling"],
    wedgeEligible: false,
  },
  {
    id: "olympiad",
    purpose: "Olympiad practice — deep link only until speech PMF.",
    category: "learn",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "soft_gate",
    analyticsOwner: "learning",
    routeOwner: ["/olympiad"],
    wedgeEligible: false,
  },
  {
    id: "recipes",
    purpose: "Recipes — deep link / search within treasury.",
    category: "care",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "nutrition",
    routeOwner: ["/recipes"],
    wedgeEligible: false,
  },
  {
    id: "kids_control_center",
    purpose: "Kids Control Center preview — not primary nav.",
    category: "shell",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "debug",
    routeOwner: ["/kids-control-center"],
    wedgeEligible: false,
  },
  {
    id: "environment",
    purpose: "Environment / AQI helper inside tools — not Home.",
    category: "care",
    discoveryStage: "hidden",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "free",
    analyticsOwner: "care",
    routeOwner: ["/environment"],
    wedgeEligible: false,
  },

  // —— Archived experiences (not features to promote) ——
  {
    id: "dashboard_home",
    purpose: "Dashboard-as-default-home experience (retired).",
    category: "shell",
    discoveryStage: "archived",
    navOwner: "none",
    askAmyHandoff: "none",
    premiumRole: "n_a",
    analyticsOwner: "migration",
    routeOwner: ["/dashboard"],
    wedgeEligible: false,
  },
] as const;

export function getFeatureEntry(
  id: string,
): FeatureRegistryEntry | undefined {
  return V2_FEATURE_REGISTRY.find((entry) => entry.id === id);
}

export function listFeaturesByDiscoveryStage(
  stage: FeatureRegistryEntry["discoveryStage"],
): FeatureRegistryEntry[] {
  return V2_FEATURE_REGISTRY.filter((entry) => entry.discoveryStage === stage);
}

export function listWedgeEligibleFeatures(): FeatureRegistryEntry[] {
  return V2_FEATURE_REGISTRY.filter((entry) => entry.wedgeEligible);
}
