import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import type { SchoolBrandingProfile, BrandThemeId, FooterToggles } from "@workspace/worksheet-studio";
import {
  BRAND_THEME_LABELS,
  PRESET_SCHOOL_NAMES,
  applyThemeToProfile,
} from "@workspace/worksheet-studio";
import {
  createDefaultProfile,
  createProfileFromPreset,
  deleteSchoolProfile,
  duplicateSchoolProfile,
  exportSchoolProfileJson,
  getActiveBrandingProfile,
  importSchoolProfileJson,
  listSchoolProfiles,
  resetSchoolProfileToDefault,
  saveSchoolProfile,
  switchSchoolProfile,
  applyBrandingToDocument,
} from "@workspace/worksheet-studio/client";
import { generateWorksheetLocal } from "@workspace/worksheet-studio";
import {
  Copy, Download, Palette, RotateCcw, Save, School, Trash2, Upload,
} from "lucide-react";

type Tab = "school" | "colors" | "footer" | "themes" | "profiles";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onBrandingSaved?: () => void;
};

const COLOR_FIELDS: Array<{ key: keyof SchoolBrandingProfile["colors"]; label: string }> = [
  { key: "primary", label: "Primary" },
  { key: "secondary", label: "Secondary" },
  { key: "accent", label: "Accent" },
  { key: "headerBackground", label: "Header BG" },
  { key: "footerBackground", label: "Footer BG" },
  { key: "border", label: "Border" },
  { key: "title", label: "Title" },
  { key: "text", label: "Text" },
  { key: "button", label: "Button" },
];

const FOOTER_TOGGLES: Array<{ key: keyof FooterToggles; label: string }> = [
  { key: "showAddress", label: "Address" },
  { key: "showPhone", label: "Phone" },
  { key: "showEmail", label: "Email" },
  { key: "showWebsite", label: "Website" },
  { key: "showConfidential", label: "Confidential notice" },
  { key: "showPageNumber", label: "Page number" },
  { key: "showGeneratedBy", label: "Generated by AmyNest" },
];

export function WorksheetBrandingSheet({ open, onOpenChange, onBrandingSaved }: Props) {
  const [tab, setTab] = useState<Tab>("school");
  const [draft, setDraft] = useState<SchoolBrandingProfile>(() => getActiveBrandingProfile());
  const [savedSnapshot, setSavedSnapshot] = useState<SchoolBrandingProfile>(() => getActiveBrandingProfile());
  const [profiles, setProfiles] = useState<SchoolBrandingProfile[]>(() => listSchoolProfiles());
  const importRef = useRef<HTMLInputElement>(null);

  const refresh = useCallback(() => {
    const active = getActiveBrandingProfile();
    setDraft(structuredClone(active));
    setSavedSnapshot(structuredClone(active));
    setProfiles(listSchoolProfiles());
  }, []);

  useEffect(() => {
    if (open) refresh();
  }, [open, refresh]);

  const previewDoc = useMemo(() => {
    const base = generateWorksheetLocal({
      prompt: "Preview worksheet — animals and colours",
      classLevel: "ukg",
      subject: "english",
      difficulty: "easy",
      pageCount: 1,
    });
    return applyBrandingToDocument(base, draft);
  }, [draft]);

  const patch = (partial: Partial<SchoolBrandingProfile>) => {
    setDraft((prev) => ({ ...prev, ...partial, updatedAt: new Date().toISOString() }));
  };

  const patchColor = (key: keyof SchoolBrandingProfile["colors"], value: string) => {
    setDraft((prev) => ({
      ...prev,
      themeId: "custom" as BrandThemeId,
      colors: { ...prev.colors, [key]: value },
    }));
  };

  const patchFooter = (key: keyof FooterToggles, value: boolean) => {
    setDraft((prev) => ({ ...prev, footer: { ...prev.footer, [key]: value } }));
  };

  const handleSave = () => {
    saveSchoolProfile(draft);
    switchSchoolProfile(draft.id);
    setSavedSnapshot(structuredClone(draft));
    setProfiles(listSchoolProfiles());
    onBrandingSaved?.();
  };

  const handleUndo = () => setDraft(structuredClone(savedSnapshot));

  const readImage = (file: File, field: "logoSrc" | "signatureSrc" | "stampSrc") => {
    const reader = new FileReader();
    reader.onload = () => patch({ [field]: String(reader.result) });
    reader.readAsDataURL(file);
  };

  const headerPreview = previewDoc.pages[0]?.elements.filter((e) => e.id.startsWith("brand_")) ?? [];

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="bottom" className="max-h-[94dvh] overflow-y-auto rounded-t-3xl pb-[max(env(safe-area-inset-bottom),1rem)]">
        <SheetHeader>
          <SheetTitle className="text-left text-lg font-bold" style={{ color: draft.colors.primary }}>
            School Branding
          </SheetTitle>
        </SheetHeader>

        <div className="mt-2 flex flex-wrap gap-1.5">
          {(["school", "colors", "footer", "themes", "profiles"] as Tab[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setTab(t)}
              className={cn(
                "rounded-full px-3 py-1.5 text-xs font-medium capitalize touch-manipulation",
                tab === t ? "text-white" : "bg-muted text-muted-foreground",
              )}
              style={tab === t ? { backgroundColor: draft.colors.primary } : undefined}
            >
              {t}
            </button>
          ))}
        </div>

        {/* Live preview */}
        <div
          className="mt-3 overflow-hidden rounded-xl border p-3"
          style={{ backgroundColor: draft.colors.headerBackground, borderColor: draft.colors.border }}
        >
          <p className="mb-2 text-center text-[10px] font-bold uppercase tracking-wider" style={{ color: draft.colors.secondary }}>
            Live preview
          </p>
          <div className="mx-auto max-w-xs space-y-1 text-center">
            {draft.logoSrc && (
              <img src={draft.logoSrc} alt="" className="mx-auto h-12 w-12 object-contain" />
            )}
            <p className="text-sm font-bold" style={{ color: draft.colors.title }}>{draft.schoolName}</p>
            {draft.tagline && <p className="text-xs" style={{ color: draft.colors.secondary }}>{draft.tagline}</p>}
            {draft.foundation && <p className="text-[10px]" style={{ color: draft.colors.text }}>{draft.foundation}</p>}
            <p className="text-xs font-semibold" style={{ color: draft.colors.title }}>Topic – Preview Worksheet</p>
          </div>
          <p className="mt-2 text-center text-[9px]" style={{ color: draft.colors.text }}>
            {headerPreview.length} header elements · {previewDoc.pages[0]?.elements.filter((e) => e.id.startsWith("footer_")).length ?? 0} footer elements
          </p>
        </div>

        {tab === "school" && (
          <div className="mt-4 space-y-3">
            <Field label="School name" value={draft.schoolName} onChange={(v) => patch({ schoolName: v })} />
            <Field label="Tagline" value={draft.tagline ?? ""} onChange={(v) => patch({ tagline: v })} />
            <Field label="Foundation" value={draft.foundation ?? ""} onChange={(v) => patch({ foundation: v })} />
            <Field label="Address" value={draft.address ?? ""} onChange={(v) => patch({ address: v })} />
            <div className="grid grid-cols-2 gap-2">
              <Field label="Phone" value={draft.phone ?? ""} onChange={(v) => patch({ phone: v })} />
              <Field label="Email" value={draft.email ?? ""} onChange={(v) => patch({ email: v })} />
            </div>
            <Field label="Website" value={draft.website ?? ""} onChange={(v) => patch({ website: v })} />
            <Field label="Principal" value={draft.principalName ?? ""} onChange={(v) => patch({ principalName: v })} />
            <Field label="Teacher (default)" value={draft.teacherName ?? ""} onChange={(v) => patch({ teacherName: v })} />
            <Field label="Academic session" value={draft.academicSession ?? ""} onChange={(v) => patch({ academicSession: v })} />
            <Field label="Class prefix" value={draft.classPrefix ?? ""} onChange={(v) => patch({ classPrefix: v })} />
            <Field label="Footer text" value={draft.footerText ?? ""} onChange={(v) => patch({ footerText: v })} />
            <ImageUpload label="School logo" src={draft.logoSrc} onFile={(f) => readImage(f, "logoSrc")} />
            <ImageUpload label="Digital signature" src={draft.signatureSrc} onFile={(f) => readImage(f, "signatureSrc")} optional />
            <ImageUpload label="Official stamp" src={draft.stampSrc} onFile={(f) => readImage(f, "stampSrc")} optional />
          </div>
        )}

        {tab === "colors" && (
          <div className="mt-4 grid grid-cols-2 gap-3">
            {COLOR_FIELDS.map(({ key, label }) => (
              <label key={key} className="space-y-1">
                <span className="text-xs font-medium text-muted-foreground">{label}</span>
                <div className="flex gap-2">
                  <input
                    type="color"
                    value={draft.colors[key]}
                    onChange={(e) => patchColor(key, e.target.value)}
                    className="h-11 w-14 cursor-pointer rounded-lg border touch-manipulation"
                    aria-label={label}
                  />
                  <Input
                    value={draft.colors[key]}
                    onChange={(e) => patchColor(key, e.target.value)}
                    className="h-11 font-mono text-xs touch-manipulation"
                  />
                </div>
              </label>
            ))}
          </div>
        )}

        {tab === "footer" && (
          <div className="mt-4 space-y-2">
            {FOOTER_TOGGLES.map(({ key, label }) => (
              <label key={key} className="flex h-12 items-center justify-between rounded-xl border px-3 touch-manipulation">
                <span className="text-sm">{label}</span>
                <input
                  type="checkbox"
                  checked={draft.footer[key]}
                  onChange={(e) => patchFooter(key, e.target.checked)}
                  className="h-5 w-5"
                />
              </label>
            ))}
            <Field
              label="Confidential notice"
              value={draft.footerConfidentialText ?? ""}
              onChange={(v) => patch({ footerConfidentialText: v })}
            />
          </div>
        )}

        {tab === "themes" && (
          <div className="mt-4 grid grid-cols-2 gap-2">
            {(Object.keys(BRAND_THEME_LABELS) as BrandThemeId[]).map((themeId) => (
              <button
                key={themeId}
                type="button"
                onClick={() => setDraft(applyThemeToProfile(themeId, draft))}
                className={cn(
                  "rounded-xl border p-3 text-left text-xs font-semibold touch-manipulation",
                  draft.themeId === themeId && "ring-2 ring-[#1e3a5f]",
                )}
                style={{
                  borderColor: draft.colors.border,
                  backgroundColor: applyThemeToProfile(themeId).colors.headerBackground,
                  color: applyThemeToProfile(themeId).colors.primary,
                }}
              >
                {BRAND_THEME_LABELS[themeId]}
              </button>
            ))}
          </div>
        )}

        {tab === "profiles" && (
          <div className="mt-4 space-y-2">
            <p className="text-xs text-muted-foreground">Switch school profile — all worksheets use active branding.</p>
            {profiles.map((p) => (
              <div key={p.id} className={cn("flex items-center gap-2 rounded-xl border p-3", p.id === draft.id && "ring-2 ring-[#1e3a5f]")}>
                <button
                  type="button"
                  className="min-w-0 flex-1 text-left touch-manipulation"
                  onClick={() => {
                    switchSchoolProfile(p.id);
                    refresh();
                  }}
                >
                  <p className="truncate font-semibold" style={{ color: p.colors.primary }}>{p.name}</p>
                  <p className="truncate text-xs text-muted-foreground">{p.schoolName}</p>
                </button>
                <Button variant="ghost" size="icon" className="h-9 w-9" onClick={() => { const c = duplicateSchoolProfile(p.id); if (c) refresh(); }} aria-label="Duplicate">
                  <Copy className="h-4 w-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-9 w-9"
                  disabled={profiles.length <= 1}
                  onClick={() => { if (deleteSchoolProfile(p.id)) refresh(); }}
                  aria-label="Delete"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            ))}
            <div className="flex flex-wrap gap-2 pt-2">
              {PRESET_SCHOOL_NAMES.map((preset) => (
                <Button
                  key={preset.id}
                  size="sm"
                  variant="outline"
                  className="h-10 rounded-full touch-manipulation"
                  onClick={() => { createProfileFromPreset(preset.id); refresh(); }}
                >
                  <School className="mr-1 h-3 w-3" /> {preset.name}
                </Button>
              ))}
            </div>
            <Button
              size="sm"
              variant="outline"
              className="w-full touch-manipulation"
              onClick={() => {
                const p = createDefaultProfile({ id: `school_${Date.now()}`, name: "New School", schoolName: "NEW SCHOOL" });
                saveSchoolProfile(p);
                switchSchoolProfile(p.id);
                refresh();
              }}
            >
              + Add custom school
            </Button>
          </div>
        )}

        <div className="mt-4 flex flex-wrap gap-2">
          <Button className="h-12 flex-1 touch-manipulation" style={{ backgroundColor: draft.colors.button }} onClick={handleSave}>
            <Save className="mr-2 h-4 w-4" /> Save
          </Button>
          <Button variant="outline" className="h-12 touch-manipulation" onClick={handleUndo}>
            <RotateCcw className="mr-2 h-4 w-4" /> Undo
          </Button>
          <Button variant="outline" className="h-12 touch-manipulation" onClick={() => setDraft(resetSchoolProfileToDefault(draft.id))}>
            Reset
          </Button>
        </div>

        <div className="mt-2 flex gap-2">
          <Button
            variant="outline"
            size="sm"
            className="flex-1 touch-manipulation"
            onClick={() => {
              const blob = new Blob([exportSchoolProfileJson(draft.id)], { type: "application/json" });
              const url = URL.createObjectURL(blob);
              const a = document.createElement("a");
              a.href = url;
              a.download = `${draft.name.replace(/\s+/g, "-").toLowerCase()}-branding.json`;
              a.click();
              URL.revokeObjectURL(url);
            }}
          >
            <Download className="mr-1 h-3 w-3" /> Export JSON
          </Button>
          <Button variant="outline" size="sm" className="flex-1 touch-manipulation" onClick={() => importRef.current?.click()}>
            <Upload className="mr-1 h-3 w-3" /> Import JSON
          </Button>
          <input
            ref={importRef}
            type="file"
            accept="application/json,.json"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (!file) return;
              const reader = new FileReader();
              reader.onload = () => {
                try {
                  importSchoolProfileJson(String(reader.result));
                  refresh();
                } catch { /* invalid */ }
              };
              reader.readAsText(file);
            }}
          />
        </div>
      </SheetContent>
    </Sheet>
  );
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <label className="block space-y-1">
      <span className="text-xs font-medium text-muted-foreground">{label}</span>
      <Input value={value} onChange={(e) => onChange(e.target.value)} className="h-11 rounded-xl touch-manipulation" />
    </label>
  );
}

function ImageUpload({
  label, src, onFile, optional,
}: { label: string; src?: string; onFile: (f: File) => void; optional?: boolean }) {
  const ref = useRef<HTMLInputElement>(null);
  return (
    <div className="space-y-1">
      <span className="text-xs font-medium text-muted-foreground">{label}{optional ? " (optional)" : ""}</span>
      <div className="flex items-center gap-3">
        {src && <img src={src} alt="" className="h-14 w-14 rounded-lg border object-contain" />}
        <Button type="button" variant="outline" className="h-11 touch-manipulation" onClick={() => ref.current?.click()}>
          <Palette className="mr-2 h-4 w-4" /> Upload
        </Button>
        <input ref={ref} type="file" accept="image/*" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) onFile(f); }} />
      </div>
    </div>
  );
}
