export {
  LESSONS,
  getLessonText,
  lessonsForAge,
  lessonCountForAge,
  getAgeLabel,
  getLessonById,
  getRecommendedLessonsForCoachGoal,
  COACH_AUDIO_GOAL_STORAGE_KEY,
  TIER_LABELS,
  LESSON_SERIES,
  orphanLessonIdsForAge,
  seriesForAge,
  getSeriesById,
  resolveSeriesLessons,
  totalSeriesMinutes,
  LESSONS_COMPLETE_STORAGE_KEY,
  parseCompletedLessonIds,
  serializeCompletedLessonIds,
  markLessonComplete,
  getSeriesProgress,
  firstIncompleteLessonId,
  partIndexForLesson,
  type AgeBucket,
  type LangCode,
  type LessonTier,
  type MultiLang,
  type Lesson,
  type LessonSeries,
  type SeriesProgress,
  AGE_LABELS,
} from "@workspace/audio-lessons";
