import type { JourneyDefinition } from "./types.js";

/** Pre-signup onboarding — mirrors client pre-signup-reengagement milestones. */
export const PRESIGNUP_JOURNEY: JourneyDefinition = {
  journeyId: "presignup_onboarding",
  segment: "INSTALLED_NEVER_REGISTERED",
  steps: [
    {
      stepId: "day0",
      delayHours: 2,
      titleKey: "presignup.day0.title",
      bodyKey: "presignup.day0.body",
      defaultTitle: "Your child's personalized routine is waiting",
      defaultBody: "Open AmyNest to build a gentle daily plan in minutes.",
      deepLink: "/sign-in?source=notif_presignup_d0",
      category: "engagement",
      emoji: "✨",
      goal: "GOAL_PARENT_ENGAGEMENT",
    },
    {
      stepId: "day1",
      delayHours: 24,
      titleKey: "presignup.day1.title",
      bodyKey: "presignup.day1.body",
      defaultTitle: "Complete setup in under 2 minutes",
      defaultBody: "Sign in once — Amy handles the rest for your family.",
      deepLink: "/sign-in?source=notif_presignup_d1",
      category: "engagement",
      emoji: "⏱️",
      goal: "GOAL_PARENT_ENGAGEMENT",
    },
    {
      stepId: "day3",
      delayHours: 72,
      titleKey: "presignup.day3.title",
      bodyKey: "presignup.day3.body",
      defaultTitle: "Start building healthy habits today",
      defaultBody: "A simple routine helps mornings feel calmer.",
      deepLink: "/sign-in?source=notif_presignup_d3",
      category: "engagement",
      emoji: "🌱",
      goal: "GOAL_ROUTINE_COMPLETION",
    },
    {
      stepId: "day7",
      delayHours: 168,
      titleKey: "presignup.day7.title",
      bodyKey: "presignup.day7.body",
      defaultTitle: "Thousands of parents already use AmyNest",
      defaultBody: "Join families building calmer days — setup takes one tap.",
      deepLink: "/sign-in?source=notif_presignup_d7",
      category: "engagement",
      emoji: "💛",
      goal: "GOAL_PARENT_ENGAGEMENT",
    },
  ],
};

export const NO_ROUTINE_JOURNEY: JourneyDefinition = {
  journeyId: "no_routine_activation",
  segment: "REGISTERED_NO_ROUTINE",
  steps: [
    {
      stepId: "h24",
      delayHours: 24,
      titleKey: "no_routine.h24.title",
      bodyKey: "no_routine.h24.body",
      defaultTitle: "Amy can build today's routine in under one minute",
      defaultBody: "Tell Amy about your child — get a personalized plan instantly.",
      deepLink: "/routines/generate?source=notif_no_routine_24h",
      category: "engagement",
      emoji: "🗓️",
      goal: "GOAL_ROUTINE_COMPLETION",
      skipIf: (s) => s.firstRoutineCompleted,
    },
    {
      stepId: "h48",
      delayHours: 48,
      titleKey: "no_routine.h48.title",
      bodyKey: "no_routine.h48.body",
      defaultTitle: "Still no routine? Amy makes it easy",
      defaultBody: "One minute of setup — a calmer day for your child.",
      deepLink: "/routines/generate?source=notif_no_routine_48h",
      category: "engagement",
      emoji: "✨",
      goal: "GOAL_ROUTINE_COMPLETION",
      skipIf: (s) => s.firstRoutineCompleted,
    },
    {
      stepId: "h72",
      delayHours: 72,
      titleKey: "no_routine.h72.title",
      bodyKey: "no_routine.h72.body",
      defaultTitle: "Last nudge — your routine is one tap away",
      defaultBody: "Amy is ready when you are. No pressure.",
      deepLink: "/routines/generate?source=notif_no_routine_72h",
      category: "engagement",
      emoji: "💛",
      goal: "GOAL_ROUTINE_COMPLETION",
      skipIf: (s) => s.firstRoutineCompleted,
    },
  ],
};

export const INACTIVE_JOURNEY: JourneyDefinition = {
  journeyId: "inactive_recovery",
  segment: "INACTIVE_USERS",
  steps: [
    {
      stepId: "d3",
      delayHours: 72,
      titleKey: "inactive.d3.title",
      bodyKey: "inactive.d3.body",
      defaultTitle: "We saved your progress",
      defaultBody: "Pick up where you left off — one small step today.",
      deepLink: "/hub?source=notif_inactive_d3",
      category: "engagement",
      goal: "GOAL_REACTIVATION",
    },
    {
      stepId: "d7",
      delayHours: 168,
      titleKey: "inactive.d7.title",
      bodyKey: "inactive.d7.body",
      defaultTitle: "Your child's routine is still here",
      defaultBody: "No guilt — open AmyNest whenever you're ready.",
      deepLink: "/routines?source=notif_inactive_d7",
      category: "engagement",
      goal: "GOAL_REACTIVATION",
    },
    {
      stepId: "d14",
      delayHours: 336,
      titleKey: "inactive.d14.title",
      bodyKey: "inactive.d14.body",
      defaultTitle: "A gentle check-in from Amy",
      defaultBody: "Your family's plan is waiting — we won't nag.",
      deepLink: "/hub?source=notif_inactive_d14",
      category: "engagement",
      goal: "GOAL_RETENTION",
    },
    {
      stepId: "d30",
      delayHours: 720,
      titleKey: "inactive.d30.title",
      bodyKey: "inactive.d30.body",
      defaultTitle: "Still thinking about routines?",
      defaultBody: "AmyNest is here when life calms down.",
      deepLink: "/hub?source=notif_inactive_d30",
      category: "engagement",
      goal: "GOAL_RETENTION",
    },
  ],
};

export const EXPIRED_PREMIUM_JOURNEY: JourneyDefinition = {
  journeyId: "expired_premium_winback",
  segment: "EXPIRED_PREMIUM",
  steps: [
    {
      stepId: "d1",
      delayHours: 24,
      titleKey: "expired.d1.title",
      bodyKey: "expired.d1.body",
      defaultTitle: "Your Premium features paused",
      defaultBody: "Renew anytime — your routines and progress are safe.",
      deepLink: "/pricing?renew=1&source=notif_expired_d1",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "d3",
      delayHours: 72,
      titleKey: "expired.d3.title",
      bodyKey: "expired.d3.body",
      defaultTitle: "Miss unlimited routines?",
      defaultBody: "Pick up where you left off with one tap.",
      deepLink: "/pricing?renew=1&source=notif_expired_d3",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "d7",
      delayHours: 168,
      titleKey: "expired.d7.title",
      bodyKey: "expired.d7.body",
      defaultTitle: "Your family's progress is still saved",
      defaultBody: "Come back to Premium when you're ready.",
      deepLink: "/pricing?renew=1&source=notif_expired_d7",
      category: "conversion",
      goal: "GOAL_RETENTION",
    },
    {
      stepId: "d14",
      delayHours: 336,
      titleKey: "expired.d14.title",
      bodyKey: "expired.d14.body",
      defaultTitle: "Amy still remembers your child",
      defaultBody: "Renew Premium to unlock Speech Coach and more.",
      deepLink: "/pricing?renew=1&source=notif_expired_d14",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "d30",
      delayHours: 720,
      titleKey: "expired.d30.title",
      bodyKey: "expired.d30.body",
      defaultTitle: "Welcome back anytime",
      defaultBody: "Your account is ready — no setup needed.",
      deepLink: "/pricing?renew=1&source=notif_expired_d30",
      category: "conversion",
      goal: "GOAL_RETENTION",
    },
  ],
};

export const FREE_BEHAVIORAL_JOURNEY: JourneyDefinition = {
  journeyId: "free_behavioral_premium",
  segment: "FREE_BEHAVIORAL",
  steps: [
    {
      stepId: "routine_limit",
      delayHours: 0,
      titleKey: "free.routine_limit.title",
      bodyKey: "free.routine_limit.body",
      defaultTitle: "Unlimited routines with Premium",
      defaultBody: "You're building great habits — unlock unlimited routines.",
      deepLink: "/pricing?source=notif_routine_limit",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "speech_limit",
      delayHours: 0,
      titleKey: "free.speech_limit.title",
      bodyKey: "free.speech_limit.body",
      defaultTitle: "Continue Speech Coach",
      defaultBody: "Premium keeps practice going without limits.",
      deepLink: "/pricing?source=notif_speech_limit",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "meal_limit",
      delayHours: 0,
      titleKey: "free.meal_limit.title",
      bodyKey: "free.meal_limit.body",
      defaultTitle: "Unlimited meal plans",
      defaultBody: "Premium unlocks full nutrition planning for your child.",
      deepLink: "/pricing?source=notif_meal_limit",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
    {
      stepId: "ai_limit",
      delayHours: 0,
      titleKey: "free.ai_limit.title",
      bodyKey: "free.ai_limit.body",
      defaultTitle: "Keep chatting with Amy",
      defaultBody: "Premium removes AI limits so Amy can help anytime.",
      deepLink: "/pricing?source=notif_ai_limit",
      category: "conversion",
      goal: "GOAL_SUBSCRIPTION",
    },
  ],
};

export const PREMIUM_RETENTION_JOURNEY: JourneyDefinition = {
  journeyId: "premium_retention",
  segment: "PREMIUM_USERS",
  steps: [
    {
      stepId: "weekly_report",
      delayHours: 0,
      titleKey: "premium.weekly_report.title",
      bodyKey: "premium.weekly_report.body",
      defaultTitle: "Your weekly report is ready",
      defaultBody: "See how your child progressed this week.",
      deepLink: "/hub?tab=insights&source=notif_premium_weekly",
      category: "engagement",
      goal: "GOAL_PARENT_ENGAGEMENT",
    },
    {
      stepId: "speech_insights",
      delayHours: 0,
      titleKey: "premium.speech_insights.title",
      bodyKey: "premium.speech_insights.body",
      defaultTitle: "New speech insights for your child",
      defaultBody: "Speech Coach found something worth celebrating.",
      deepLink: "/speech-coach?source=notif_premium_speech",
      category: "engagement",
      goal: "GOAL_LEARNING_COMPLETION",
    },
    {
      stepId: "health_lab",
      delayHours: 0,
      titleKey: "premium.health_lab.title",
      bodyKey: "premium.health_lab.body",
      defaultTitle: "Health Lab update",
      defaultBody: "A gentle wellness tip tailored to your child.",
      deepLink: "/health-lab?source=notif_premium_health",
      category: "engagement",
      goal: "GOAL_PARENT_ENGAGEMENT",
    },
  ],
};

export const SEGMENT_JOURNEYS: JourneyDefinition[] = [
  PRESIGNUP_JOURNEY,
  NO_ROUTINE_JOURNEY,
  INACTIVE_JOURNEY,
  EXPIRED_PREMIUM_JOURNEY,
  FREE_BEHAVIORAL_JOURNEY,
  PREMIUM_RETENTION_JOURNEY,
];

export function journeyForSegment(segment: string): JourneyDefinition | null {
  return SEGMENT_JOURNEYS.find((j) => j.segment === segment) ?? null;
}
