/**
 * 72 unique digraph story scripts — one per story, no skeleton reuse.
 */
export type DigraphStoryScript = {
  title: (w: string, w2: string, name: string) => string;
  lines: (w: string, w2: string, name: string) => string[];
};

function s(
  title: DigraphStoryScript["title"],
  lines: DigraphStoryScript["lines"],
): DigraphStoryScript {
  return { title, lines };
}

/** Globally unique sentence structures (72). */
export const DIGRAPH_STORY_SCRIPTS: DigraphStoryScript[] = [
  s((w) => `Hush ${w}`, (w) => [`Hush — a ${w} nearby.`, `Soft moss underfoot.`, `Breeze carried scent.`]),
  s((w, w2, n) => `${n} Traces ${w}`, (w, w2, n) => [`${n} traced the ${w}.`, `Ink marked the ${w2}.`, `Tale complete.`]),
  s((w) => `Glow ${w}`, (w) => [`Twilight on the ${w}.`, `Crickets chirped low.`, `Night drew near.`]),
  s((w, w2) => `Quest ${w}`, (w, w2) => [`Map led to ${w}.`, `Treasure hid in ${w2}.`, `Cheers rang out.`]),
  s((w, n) => `Drift ${w}`, (w, _w2, n) => [`${n} drifted toward ${w}.`, `Waves lapped soft.`, `Harbor lights blinked.`]),
  s((w) => `Murmur ${w}`, (w) => [`Murmur of the ${w}.`, `Echo down the hall.`, `Silence returned.`]),
  s((w, w2) => `Patch ${w}`, (w, w2) => [`Patch fixed the ${w}.`, `Thread through ${w2}.`, `Strong once more.`]),
  s((w, n) => `${n} Finds ${w}`, (w, _w2, n) => [`${n} unearthed ${w}.`, `Brush off the dust.`, `Prize in hand.`]),
  s((w) => `Ripple ${w}`, (w) => [`Ripple crossed the ${w}.`, `Fish darted deep.`, `Stillness again.`]),
  s((w, w2) => `Bundle ${w}`, (w, w2) => [`Bundle held the ${w}.`, `Tied with ${w2}.`, `Ready to go.`]),
  s((w, n) => `Crest ${w}`, (w, _w2, n) => [`${n} climbed crest of ${w}.`, `View stretched wide.`, `Wind in hair.`]),
  s((w) => `Hollow ${w}`, (w) => [`Hollow held the ${w}.`, `Echo from within.`, `Mystery solved.`]),
  s((w) => `Frost ${w}`, (w) => [`Frost rimmed the ${w}.`, `Sun melted edges.`, `Spring hinted.`]),
  s((w, w2, n) => `${n} Sketches ${w}`, (w, w2, n) => [`${n} sketched the ${w}.`, `Charcoal on ${w2}.`, `Art preserved.`]),
  s((w) => `Glint ${w}`, (w) => [`Glint off the ${w}.`, `Shielded eyes from glare.`, `Gem confirmed.`]),
  s((w, w2) => `Harbor ${w}`, (w, w2) => [`Harbor docked the ${w}.`, `Ropes bound ${w2}.`, `Voyage done.`]),
  s((w, n) => `${n} Whittles ${w}`, (w, _w2, n) => [`${n} whittled the ${w}.`, `Shavings piled high.`, `Figurine done.`]),
  s((w) => `Jasper ${w}`, (w) => [`Jasper lined the ${w}.`, `Cool to the touch.`, `Polished bright.`]),
  s((w, w2) => `Kernel ${w}`, (w, w2) => [`Kernel hid in ${w}.`, `Sprout pushed ${w2}.`, `Green shoot rose.`]),
  s((w, n) => `${n} Looms ${w}`, (w, _w2, n) => [`${n} loomed over ${w}.`, `Shadow stretched long.`, `Cloud passed by.`]),
  s((w) => `Mirth ${w}`, (w) => [`Mirth filled the ${w}.`, `Laughter spilled out.`, `Joy unbound.`]),
  s((w, w2) => `Nectar ${w}`, (w, w2) => [`Nectar dripped on ${w}.`, `Bees hummed by ${w2}.`, `Sweet reward.`]),
  s((w, n) => `${n} Orbits ${w}`, (w, _w2, n) => [`${n} orbited the ${w}.`, `Path traced neat.`, `Landing soft.`]),
  s((w) => `Prism ${w}`, (w) => [`Prism split the ${w}.`, `Rainbow on the wall.`, `Colors danced.`]),
  s((w, w2) => `Quartz ${w}`, (w, w2) => [`Quartz studded ${w}.`, `Facet caught ${w2}.`, `Light refracted.`]),
  s((w, n) => `${n} Renders ${w}`, (w, _w2, n) => [`${n} rendered the ${w}.`, `Canvas glowed warm.`, `Masterpiece hung.`]),
  s((w) => `Sable ${w}`, (w) => [`Sable fur on ${w}.`, `Midnight hue deep.`, `Elegant form.`]),
  s((w, w2) => `Tundra ${w}`, (w, w2) => [`Tundra cradled ${w}.`, `Ice gripped ${w2}.`, `Aurora bloomed.`]),
  s((w, n) => `${n} Unfurls ${w}`, (w, _w2, n) => [`${n} unfurled the ${w}.`, `Banner snapped taut.`, `Salute given.`]),
  s((w) => `Velvet ${w}`, (w) => [`Velvet draped the ${w}.`, `Fold upon fold.`, `Luxury soft.`]),
  s((w, w2) => `Wicket ${w}`, (w, w2) => [`Wicket guarded ${w}.`, `Ball rolled past ${w2}.`, `Run scored.`]),
  s((w, n) => `${n} Yields ${w}`, (w, _w2, n) => [`${n} yielded to ${w}.`, `Patience won out.`, `Peace restored.`]),
  s((w) => `Zephyr ${w}`, (w) => [`Zephyr stirred the ${w}.`, `Kite tugged skyward.`, `String held firm.`]),
  s((w, w2, n) => `${n} Anchors ${w}`, (w, w2, n) => [`${n} anchored the ${w}.`, `Chain rattled on ${w2}.`, `Boat held still.`]),
  s((w) => `Belfry ${w}`, (w) => [`Belfry housed the ${w}.`, `Bell tolled noon.`, `Pigeons scattered.`]),
  s((w, w2) => `Cobalt ${w}`, (w, w2) => [`Cobalt stained the ${w}.`, `Brush dipped in ${w2}.`, `Hue vivid.`]),
  s((w, n) => `${n} Dredges ${w}`, (w, _w2, n) => [`${n} dredged the ${w}.`, `Silt rose cloudy.`, `Channel cleared.`]),
  s((w) => `Ember ${w}`, (w) => [`Ember glowed in ${w}.`, `Smoke curled up.`, `Warmth spread.`]),
  s((w, w2) => `Fjord ${w}`, (w, w2) => [`Fjord embraced ${w}.`, `Cliffs flanked ${w2}.`, `Water still.`]),
  s((w, n) => `${n} Gilds ${w}`, (w, _w2, n) => [`${n} gilded the ${w}.`, `Leaf applied thin.`, `Shine renewed.`]),
  s((w) => `Heath ${w}`, (w) => [`Heath bloomed round ${w}.`, `Bees worked busy.`, `Honey soon.`]),
  s((w, w2) => `Inlet ${w}`, (w, w2) => [`Inlet sheltered ${w}.`, `Tide pooled by ${w2}.`, `Shells abundant.`]),
  s((w, n) => `${n} Jousts ${w}`, (w, _w2, n) => [`${n} jousted near ${w}.`, `Lance splintered loud.`, `Crowd roared.`]),
  s((w) => `Knack ${w}`, (w) => [`Knack for fixing ${w}.`, `Tools laid neat.`, `Repair swift.`]),
  s((w, w2) => `Ledge ${w}`, (w, w2) => [`Ledge jutted past ${w}.`, `Rope secured to ${w2}.`, `Climb continued.`]),
  s((w, n) => `${n} Mends ${w}`, (w, _w2, n) => [`${n} mended the ${w}.`, `Stitch invisible.`, `Wear resumed.`]),
  s((w) => `Niche ${w}`, (w) => [`Niche carved in ${w}.`, `Statue fit snug.`, `Craft admired.`]),
  s((w, w2) => `Oasis ${w}`, (w, w2) => [`Oasis bloomed by ${w}.`, `Palms shaded ${w2}.`, `Rest deserved.`]),
  s((w, n) => `${n} Plies ${w}`, (w, _w2, n) => [`${n} plied the ${w}.`, `Trade route long.`, `Goods delivered.`]),
  s((w) => `Quill ${w}`, (w) => [`Quill scratched on ${w}.`, `Letter sealed wax.`, `Post dispatched.`]),
  s((w, w2) => `Ridge ${w}`, (w, w2) => [`Ridge overlooked ${w}.`, `Eagle nested on ${w2}.`, `Wings spread wide.`]),
  s((w, n) => `${n} Stokes ${w}`, (w, _w2, n) => [`${n} stoked the ${w}.`, `Flames leapt high.`, `Hearth cozy.`]),
  s((w) => `Thatch ${w}`, (w) => [`Thatch topped the ${w}.`, `Rain slid off.`, `Dry within.`]),
  s((w, w2) => `Umber ${w}`, (w, w2) => [`Umber washed on ${w}.`, `Shade deepened ${w2}.`, `Portrait aged.`]),
  s((w, n) => `${n} Vaults ${w}`, (w, _w2, n) => [`${n} vaulted over ${w}.`, `Landing balanced.`, `Applause rang.`]),
  s((w) => `Whorl ${w}`, (w) => [`Whorl patterned ${w}.`, `Spiral mesmerized.`, `Nature's art.`]),
  s((w, w2) => `Xylem ${w}`, (w, w2) => [`Xylem carried ${w}.`, `Sap rose through ${w2}.`, `Tree stood tall.`]),
  s((w, n) => `${n} Yearns ${w}`, (w, _w2, n) => [`${n} yearned for ${w}.`, `Patience tested long.`, `Dream fulfilled.`]),
  s((w) => `Zinc ${w}`, (w) => [`Zinc coated the ${w}.`, `Rust held at bay.`, `Years added.`]),
  s((w, w2, n) => `${n} Basks ${w}`, (w, w2, n) => [`${n} basked by ${w}.`, `Warmth soaked ${w2}.`, `Lazy afternoon.`]),
  s((w) => `Cairn ${w}`, (w) => [`Cairn marked the ${w}.`, `Stones stacked high.`, `Trail remembered.`]),
  s((w, w2) => `Delta ${w}`, (w, w2) => [`Delta fanned round ${w}.`, `River split at ${w2}.`, `Fertile land.`]),
  s((w, n) => `${n} Etches ${w}`, (w, _w2, n) => [`${n} etched the ${w}.`, `Metal bit deep.`, `Design permanent.`]),
  s((w) => `Fen ${w}`, (w) => [`Fen surrounded ${w}.`, `Mist hung low.`, `Boots sucked mud.`]),
  s((w, w2) => `Glen ${w}`, (w, w2) => [`Glen echoed round ${w}.`, `Voice bounced off ${w2}.`, `Call returned.`]),
  s((w, n) => `${n} Hews ${w}`, (w, _w2, n) => [`${n} hewed the ${w}.`, `Chips flew fast.`, `Beam true.`]),
  s((w) => `Isle ${w}`, (w) => [`Isle cradled the ${w}.`, `Surf lapped shore.`, `Paradise found.`]),
  s((w, w2) => `Jetty ${w}`, (w, w2) => [`Jetty moored at ${w}.`, `Lines creaked on ${w2}.`, `Sail furled.`]),
  s((w, n) => `${n} Kneads ${w}`, (w, _w2, n) => [`${n} kneaded the ${w}.`, `Dough rose slow.`, `Bread baked gold.`]),
  s((w) => `Loch ${w}`, (w) => [`Loch mirrored the ${w}.`, `Ripples distorted.`, `Reflection cleared.`]),
  s((w, w2) => `Moor ${w}`, (w, w2) => [`Moor stretched past ${w}.`, `Heather dotted ${w2}.`, `Path winding.`]),
  s((w, n) => `${n} Nests ${w}`, (w, _w2, n) => [`${n} nested in ${w}.`, `Twigs woven tight.`, `Eggs warmed.`]),
  s((w) => `Ore ${w}`, (w) => [`Ore veined the ${w}.`, `Pick struck spark.`, `Metal rich.`]),
  s((w, w2) => `Pike ${w}`, (w, w2) => [`Pike pierced the ${w}.`, `Banner hung on ${w2}.`, `Standard raised.`]),
  s((w, n) => `${n} Quells ${w}`, (w, _w2, n) => [`${n} quelled the ${w}.`, `Storm subsided soon.`, `Calm restored.`]),
  s((w) => `Reef ${w}`, (w) => [`Reef guarded the ${w}.`, `Coral branched bright.`, `Fish sheltered.`]),
  s((w, w2) => `Sward ${w}`, (w, w2) => [`Sward cushioned ${w}.`, `Blades bent under ${w2}.`, `Picnic spread.`]),
  s((w, n) => `${n} Tends ${w}`, (w, _w2, n) => [`${n} tended the ${w}.`, `Care given daily.`, `Growth rewarded.`]),
  s((w) => `Urchin ${w}`, (w) => [`Urchin clung to ${w}.`, `Spines bristled sharp.`, `Tide pool alive.`]),
  s((w, w2) => `Vale ${w}`, (w, w2) => [`Vale opened to ${w}.`, `Mist filled ${w2}.`, `Sun broke through.`]),
  s((w, n) => `${n} Wades ${w}`, (w, _w2, n) => [`${n} waded through ${w}.`, `Water chilled toes.`, `Shore reached.`]),
  s((w) => `Yarn ${w}`, (w) => [`Yarn tangled on ${w}.`, `Needles clicked fast.`, `Scarf lengthened.`]),
  s((w, w2) => `Zest ${w}`, (w, w2) => [`Zest grated on ${w}.`, `Citrus perfumed ${w2}.`, `Tang awakened.`]),
];
