import type { SchoolEvent } from "../eventTypes";
import { TIMELINE_STANDARD } from "./event-content-shared";

export const EVENTS_AE: SchoolEvent[] = [
  {
    id: "ae-national-day",
    countries: ["AE"],
    name: "UAE National Day",
    emoji: "🇦🇪",
    dateLabel: "2 Dec",
    month: 11,
    day: 2,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["uae", "patriotic", "flag", "school"],
    overview:
      "Red, green, white & black dress-up, flag ceremonies, and cultural performances at school.",
    whatToPrepare: [
      "UAE flag colours outfit",
      "Small flag or badge",
      "Patriotic speech in English or Arabic",
      "Traditional dress (optional)",
    ],
    speechIdeas: [
      "Happy UAE National Day! I am proud of our united, peaceful country.",
      "On 2 December we celebrate the spirit of the union. Long live the UAE!",
    ],
    activities: [
      "UAE flag collage craft",
      "Learn to say Marhaba and Shukran",
      "Draw iconic UAE landmarks — burj, palm",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit ready", "Flag packed", "Speech practiced", "Craft complete"],
    costumeCategory: "fancy-dress",
    accent: ["#16a34a", "#dc2626"],
  },
  {
    id: "ae-flag-day",
    countries: ["AE"],
    name: "UAE Flag Day",
    emoji: "🚩",
    dateLabel: "3 Nov",
    month: 10,
    day: 3,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["flag", "uae", "assembly", "school"],
    overview:
      "Schools raise the flag together — smart dress, flag etiquette, and unity speeches.",
    whatToPrepare: [
      "Formal school uniform or UAE colours",
      "Flag drawing or poster",
      "Short pledge about respect",
      "Early arrival for ceremony",
    ],
    speechIdeas: [
      "We honour our flag today. It stands for peace, strength, and unity.",
      "The UAE flag has four colours, each with meaning. I am proud to raise it today.",
    ],
    activities: [
      "Colour the four stripes correctly",
      "Flag etiquette role-play",
      "Write what unity means to you",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Uniform ready", "Poster done", "Pledge memorised", "Ceremony time set"],
    costumeCategory: "fancy-dress",
    accent: ["#15803d", "#1e40af"],
  },
  {
    id: "ae-commemoration-day",
    countries: ["AE"],
    name: "Commemoration Day",
    emoji: "🕊️",
    dateLabel: "30 Nov",
    month: 10,
    day: 30,
    category: "School Event",
    ageGroups: ["6-8", "8-12"],
    tags: ["remembrance", "uae", "assembly", "school"],
    overview:
      "Honouring UAE martyrs — respectful assembly, moments of silence, and gratitude speeches.",
    whatToPrepare: [
      "Smart formal dress",
      "Handwritten thank-you note",
      "Short respectful poem",
      "Quiet assembly plan",
    ],
    speechIdeas: [
      "We remember those who gave everything for our safety. We are grateful.",
      "Commemoration Day teaches us courage and sacrifice. We will not forget.",
    ],
    activities: [
      "Write a letter of thanks",
      "Moment of silence practice",
      "Draw a dove of peace",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Formal dress ready", "Note written", "Poem learnt", "Assembly behaviour discussed"],
    costumeCategory: "fancy-dress",
    accent: ["#64748b", "#1e293b"],
  },
  {
    id: "ae-eid-al-fitr",
    countries: ["AE", "IN"],
    name: "Eid al-Fitr",
    emoji: "🌙",
    dateLabel: "Shawwal (variable)",
    approxMonth: 3,
    category: "Festival",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["eid", "festival", "cultural", "school"],
    overview:
      "End of Ramadan celebrations — traditional dress, Eid cards, and sharing sweets at school.",
    whatToPrepare: [
      "Traditional festive outfit",
      "Eid greeting card",
      "Short Eid Mubarak speech",
      "Small treat to share (if allowed)",
    ],
    speechIdeas: [
      "Eid Mubarak! Today we celebrate kindness, family, and gratitude after Ramadan.",
      "I wish everyone joy and peace. Eid Mubarak to my friends and teachers!",
    ],
    activities: [
      "Crescent moon & star craft",
      "Design an Eid card with Arabic calligraphy style",
      "Learn Eid Mubarak greeting",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit ready", "Card finished", "Greeting practiced", "Treats packed"],
    costumeCategory: "fancy-dress",
    accent: ["#059669", "#eab308"],
  },
  {
    id: "ae-international-day",
    countries: ["AE"],
    name: "International / Unity Day",
    emoji: "🌍",
    dateLabel: "School calendar",
    approxMonth: 10,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["diversity", "global", "costume", "school"],
    overview:
      "International schools celebrate many nations — dress from your home country and share culture.",
    whatToPrepare: [
      "Traditional dress from your country",
      "Flag or cultural object to show",
      "Hello in your language",
      "Food fact card (no nuts)",
    ],
    speechIdeas: [
      "I am from [country] and I am happy to share my culture with my class!",
      "Our school is like the whole world in one place. We learn from each other!",
    ],
    activities: [
      "Passport craft with country stamps",
      "World fashion parade",
      "Teach class one word in your language",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Dress ready", "Object packed", "Greeting learnt", "Fact card done"],
    costumeCategory: "fancy-dress",
    accent: ["#2563eb", "#7c3aed"],
  },
];
