import type { SchoolEvent } from "../eventTypes";

const TIMELINE_STANDARD = [
  { daysBefore: 7, label: "Choose theme & gather materials" },
  { daysBefore: 3, label: "Prepare costume & props" },
  { daysBefore: 1, label: "Practice speech & final fitting" },
  { daysBefore: 0, label: "Event day — final check & go!" },
];

export const EVENTS_IN: SchoolEvent[] = [
  {
    id: "in-republic-day",
    countries: ["IN"],
    name: "Republic Day",
    emoji: "🎖️",
    dateLabel: "26 Jan",
    month: 0,
    day: 26,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["patriotic", "school", "fancy-dress", "speech"],
    overview:
      "Schools celebrate India's Constitution with flag hoisting, parades, and fancy-dress as leaders and soldiers.",
    whatToPrepare: [
      "Tricolour-themed outfit or character costume",
      "Small flag or badge",
      "2–3 line patriotic speech",
      "Comfortable shoes for assembly",
    ],
    speechIdeas: [
      "I am proud to be an Indian. On Republic Day we celebrate our Constitution. Jai Hind!",
      "Today we honour the leaders who gave us our rights. Vande Mataram!",
    ],
    activities: [
      "Draw the Indian flag and label saffron, white, green",
      "Learn the National Anthem chorus",
      "Role-play a freedom fighter interview",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Speech memorised", "Flag/badge packed", "School timings confirmed"],
    costumeCategory: "republic-day",
    accent: ["#1d4ed8", "#0ea5e9"],
  },
  {
    id: "in-holi",
    countries: ["IN"],
    name: "Holi",
    emoji: "🎨",
    dateLabel: "Mar (variable)",
    approxMonth: 2,
    category: "Festival",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["festival", "colour", "activity", "school"],
    overview:
      "The festival of colours — schools often hold safe colour play, cultural programs, and white-outfit celebrations.",
    whatToPrepare: [
      "Old white clothes (will get coloured)",
      "Organic / school-approved gulal",
      "Oil or cream for skin & hair protection",
      "Zip-lock bag for phone & valuables",
    ],
    speechIdeas: [
      "Holi is the festival of colours and friendship. We play safely and spread joy!",
      "On Holi we celebrate spring. I wish everyone a colourful, happy Holi!",
    ],
    activities: [
      "Make a paper pichkari (water squirter) craft",
      "Draw a Holi scene with friends playing",
      "Learn a short Holi song or rhyme",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Buy organic colours & old white outfit" },
      { daysBefore: 3, label: "Apply oil test patch; pack spare clothes" },
      { daysBefore: 1, label: "Set school permission form & safety rules" },
      { daysBefore: 0, label: "Wear white, tie hair, carry towel" },
    ],
    checklist: ["White outfit", "Safe colours packed", "Spare clothes in bag", "Permission slip signed"],
    costumeCategory: "fancy-dress",
    accent: ["#ec4899", "#f97316"],
  },
  {
    id: "in-independence-day",
    countries: ["IN"],
    name: "Independence Day",
    emoji: "🇮🇳",
    dateLabel: "15 Aug",
    month: 7,
    day: 15,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["patriotic", "freedom", "fancy-dress", "school"],
    overview:
      "India's Independence Day — flag hoisting, patriotic songs, and fancy-dress as freedom fighters.",
    whatToPrepare: [
      "Freedom fighter or soldier costume",
      "Small tricolour flag",
      "Patriotic speech (2–3 lines)",
      "Saffron/white/green accessory",
    ],
    speechIdeas: [
      "I am Bhagat Singh. I gave my life for India's freedom. Inquilab Zindabad!",
      "On 15 August 1947 India became free. I am proud to be Indian. Jai Hind!",
    ],
    activities: [
      "Make a tricolour badge with paper & ribbon",
      "Map activity: locate India on the globe",
      "Patriotic song practice — 'Saare Jahan Se Achha'",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Speech practiced", "Flag packed", "Pin/brooch secured"],
    costumeCategory: "independence-day",
    accent: ["#f97316", "#22c55e"],
  },
  {
    id: "in-teachers-day",
    countries: ["IN"],
    name: "Teacher's Day",
    emoji: "👩‍🏫",
    dateLabel: "5 Sep",
    month: 8,
    day: 5,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["school", "teacher", "speech", "activity"],
    overview:
      "Celebrating Dr. Sarvepalli Radhakrishnan's birthday — students honour teachers with cards, speeches, and small performances.",
    whatToPrepare: [
      "Thank-you card or handmade gift",
      "Short speech for your teacher",
      "Teacher costume (optional fancy-dress)",
      "Class performance idea if assigned",
    ],
    speechIdeas: [
      "Dear Teacher, you guide us like a light. Thank you for helping me learn every day.",
      "A teacher takes a hand, opens a mind, and touches a heart. Happy Teacher's Day!",
    ],
    activities: [
      "Make a 'Best Teacher' card with drawings",
      "Dress up as a teacher with glasses & book",
      "Write 3 things you learned this year",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Plan card or small gift" },
      { daysBefore: 3, label: "Write & practice thank-you speech" },
      { daysBefore: 1, label: "Finish card decoration" },
      { daysBefore: 0, label: "Present gift & greet teachers" },
    ],
    checklist: ["Card/gift ready", "Speech memorised", "Costume (if needed)", "Class role confirmed"],
    costumeCategory: "fancy-dress",
    accent: ["#6366f1", "#a855f7"],
  },
  {
    id: "in-gandhi-jayanti",
    countries: ["IN"],
    name: "Gandhi Jayanti",
    emoji: "🕊️",
    dateLabel: "2 Oct",
    month: 9,
    day: 2,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["peace", "freedom", "fancy-dress", "school"],
    overview:
      "Birth anniversary of Mahatma Gandhi — schools focus on peace, cleanliness, and non-violence with speeches and dress-ups.",
    whatToPrepare: [
      "White dhoti/kurta or simple white outfit",
      "Round glasses & walking stick (optional)",
      "Speech about peace and truth",
      "Cleanliness pledge for Swachh Bharat",
    ],
    speechIdeas: [
      "I am Mahatma Gandhi. I believe in peace and truth. Be the change you wish to see!",
      "Gandhi taught us non-violence and honesty. Let us keep our school clean!",
    ],
    activities: [
      "2-minute cleanliness drive in classroom",
      "Spinning wheel (charkha) paper craft",
      "Draw Gandhi's spectacles & quote poster",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["White costume ready", "Glasses/stick props", "Speech practiced", "Clean-up plan set"],
    costumeCategory: "gandhi-jayanti",
    accent: ["#ca8a04", "#a3a3a3"],
  },
  {
    id: "in-diwali",
    countries: ["IN"],
    name: "Diwali",
    emoji: "🪔",
    dateLabel: "Oct/Nov (variable)",
    approxMonth: 9,
    category: "Festival",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["festival", "lights", "fancy-dress", "craft"],
    overview:
      "Festival of lights — schools host diya decoration, rangoli, cultural dress, and short speeches about good over evil.",
    whatToPrepare: [
      "Traditional outfit (kurta/lehenga)",
      "DIY diya or lantern craft",
      "Short speech about Diwali",
      "Rangoli colours (if activity assigned)",
    ],
    speechIdeas: [
      "Diwali is the festival of lights. We celebrate goodness and share joy with family!",
      "On Diwali we light diyas and welcome Lakshmi. Happy Diwali to everyone!",
    ],
    activities: [
      "Decorate a clay diya with paint & glitter",
      "Make a paper lantern garland",
      "Draw Ram, Sita & Hanuman story scene",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Choose outfit & buy craft supplies" },
      { daysBefore: 3, label: "Make diya/lantern; practice speech" },
      { daysBefore: 1, label: "Pack outfit & finished craft carefully" },
      { daysBefore: 0, label: "Wear traditional dress; carry craft" },
    ],
    checklist: ["Traditional dress ready", "Craft completed", "Speech memorised", "Safe diyas only"],
    costumeCategory: "fancy-dress",
    accent: ["#f59e0b", "#dc2626"],
  },
  {
    id: "in-childrens-day",
    countries: ["IN"],
    name: "Children's Day",
    emoji: "🎈",
    dateLabel: "14 Nov",
    month: 10,
    day: 14,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["school", "fun", "speech", "performance"],
    overview:
      "Celebrating Nehru's love for children — fun activities, no uniform days, performances, and class parties.",
    whatToPrepare: [
      "Colourful party outfit",
      "Class performance or talent act",
      "Short 'I love being a child' speech",
      "Sharing snacks (if permitted)",
    ],
    speechIdeas: [
      "Children's Day is my favourite! I love to learn, play, and dream big.",
      "Chacha Nehru loved children. Today we celebrate every child's smile!",
    ],
    activities: [
      "Talent show: song, dance, or poem",
      "Friendship bracelet making",
      "Class photo with Nehru cap craft",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit chosen", "Performance rehearsed", "Speech ready", "Snacks packed (if allowed)"],
    costumeCategory: "fancy-dress",
    accent: ["#f472b6", "#fb923c"],
  },
  {
    id: "in-sports-day",
    countries: ["IN"],
    name: "Sports Day",
    emoji: "🏃",
    dateLabel: "Winter (school schedule)",
    approxMonth: 11,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["sports", "school", "activity", "fitness"],
    overview:
      "Annual athletics meet — house colours, track events, march-past, and sporty fancy-dress for mascots.",
    whatToPrepare: [
      "House-colour T-shirt & white shorts/track pants",
      "Running shoes with good grip",
      "Water bottle & cap",
      "Sunscreen for outdoor events",
    ],
    speechIdeas: [
      "Sports teach us teamwork and never giving up. I will do my best today!",
      "Run fast, play fair, cheer loud! Happy Sports Day!",
    ],
    activities: [
      "Warm-up stretches practice at home",
      "Make a house-colour cheer banner",
      "Sack race or relay practice in the park",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Confirm events & house colour" },
      { daysBefore: 3, label: "Break in shoes; practice race" },
      { daysBefore: 1, label: "Pack kit: bottle, cap, spare shirt" },
      { daysBefore: 0, label: "Light breakfast; arrive early" },
    ],
    checklist: ["House shirt ready", "Shoes broken in", "Water bottle packed", "Events list confirmed"],
    costumeCategory: "fancy-dress",
    accent: ["#16a34a", "#0ea5e9"],
  },
  {
    id: "in-annual-day",
    countries: ["IN"],
    name: "Annual Day",
    emoji: "🎭",
    dateLabel: "Dec–Feb (school schedule)",
    approxMonth: 0,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["performance", "costume", "speech", "school"],
    overview:
      "Grand school showcase — dance, drama, choir, and themed costumes. Rehearsals start weeks ahead.",
    whatToPrepare: [
      "Performance costume from teacher's list",
      "Lines / lyrics memorised",
      "Stage props assigned to you",
      "Rehearsal schedule marked on calendar",
    ],
    speechIdeas: [
      "Welcome to our Annual Day! We have worked hard and hope you enjoy our show.",
      "Today we share our talents with pride. Thank you for cheering for us!",
    ],
    activities: [
      "Daily 10-min rehearsal at home",
      "Record yourself to check expressions",
      "Help make simple stage props",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Finalise costume & props" },
      { daysBefore: 3, label: "Full dress rehearsal" },
      { daysBefore: 1, label: "Early sleep; pack costume bag" },
      { daysBefore: 0, label: "Arrive 1 hr early; stay calm & smile" },
    ],
    checklist: ["Costume complete", "Lines memorised", "Props packed", "Rehearsal attended"],
    costumeCategory: "annual-day",
    accent: ["#7c3aed", "#ec4899"],
  },
  {
    id: "in-fancy-dress",
    countries: ["IN"],
    name: "Fancy Dress Competition",
    emoji: "🎉",
    dateLabel: "Any time",
    approxMonth: new Date().getMonth(),
    category: "Competition",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["fancy-dress", "costume", "speech", "competition"],
    overview:
      "Classic school fancy dress — pick a character, make a quick costume, and deliver a 2–3 line introduction.",
    whatToPrepare: [
      "Character chosen (animal, profession, hero)",
      "DIY costume from home materials",
      "Intro speech in first person",
      "Confidence practice in front of mirror",
    ],
    speechIdeas: [
      "I am a doctor. I help people feel better when they are sick.",
      "I am a lion — king of the jungle! Roar with courage!",
    ],
    activities: [
      "Mirror practice with loud clear voice",
      "Photo trial run to check costume",
      "Make a simple prop (stethoscope, tail, hat)",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Speech memorised", "Props attached securely", "Backup outfit packed"],
    costumeCategory: "fancy-dress",
    accent: ["#db2777", "#f59e0b"],
  },
];
