import type { SchoolEvent } from "../eventTypes";
import { TIMELINE_STANDARD } from "./event-content-shared";

export const EVENTS_GB: SchoolEvent[] = [
  {
    id: "gb-bonfire-night",
    countries: ["GB"],
    name: "Bonfire Night (Guy Fawkes)",
    emoji: "🔥",
    dateLabel: "5 Nov",
    month: 10,
    day: 5,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["bonfire", "november", "school", "craft"],
    overview:
      "Fireworks-themed crafts, safety talks, and historical dress-up — schools often hold sparkler art and assembly poems.",
    whatToPrepare: [
      "Warm coat & gloves for outdoor event",
      "Guy Fawkes craft or poster",
      "Short rhyme or history line",
      "Glow sticks if school allows",
    ],
    speechIdeas: [
      "Remember, remember the fifth of November! We learn about history and stay safe with fireworks.",
      "Bonfire Night teaches us about the past. I will always follow firework safety rules!",
    ],
    activities: [
      "Make a firework scratch-art picture",
      "Build a mini 'Guy' with old clothes & newspaper",
      "Firework safety poster for classroom",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Warm clothes packed", "Craft finished", "Safety rules learned", "Permission slip signed"],
    costumeCategory: "fancy-dress",
    accent: ["#ea580c", "#1e293b"],
  },
  {
    id: "gb-remembrance-day",
    countries: ["GB"],
    name: "Remembrance Day",
    emoji: "🌺",
    dateLabel: "11 Nov",
    month: 10,
    day: 11,
    category: "School Event",
    ageGroups: ["6-8", "8-12"],
    tags: ["remembrance", "poppy", "assembly", "school"],
    overview:
      "Two-minute silence, poppy crafts, and respectful speeches about peace and service.",
    whatToPrepare: [
      "Poppy pin or handmade poppy",
      "Smart school uniform or dark outfit",
      "Short remembrance poem",
      "Quiet behaviour plan for assembly",
    ],
    speechIdeas: [
      "We wear poppies to remember those who kept us safe. We will never forget.",
      "On the eleventh hour we stand in silence. Lest we forget.",
    ],
    activities: [
      "Paper poppy wreath craft",
      "Write a thank-you letter to a veteran",
      "Learn 'In Flanders Fields' opening lines",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Poppy ready", "Poem practiced", "Assembly time noted", "Respectful dress chosen"],
    costumeCategory: "fancy-dress",
    accent: ["#dc2626", "#1f2937"],
  },
  {
    id: "gb-world-book-day",
    countries: ["GB"],
    name: "World Book Day",
    emoji: "📚",
    dateLabel: "Mar (first Thursday)",
    approxMonth: 2,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["books", "costume", "reading", "school"],
    overview:
      "Dress as a favourite book character — Harry Potter, Matilda, Gruffalo, and more.",
    whatToPrepare: [
      "Book character costume from home",
      "Copy of the book to carry",
      "1-line character introduction",
      "£1 book token if school distributes",
    ],
    speechIdeas: [
      "I am Matilda and I love reading! Books take me on amazing adventures.",
      "Today I am [character] from [book]. Reading is my superpower!",
    ],
    activities: [
      "Design a new book cover",
      "Character parade in the hall",
      "Buddy reading with younger class",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Book packed", "Intro line memorised", "Token in bag"],
    costumeCategory: "fancy-dress",
    accent: ["#7c3aed", "#2563eb"],
  },
  {
    id: "gb-sports-day",
    countries: ["GB"],
    name: "Sports Day",
    emoji: "🏃",
    dateLabel: "Summer term",
    approxMonth: 5,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["sports", "outdoor", "school", "house"],
    overview:
      "House teams, egg-and-spoon, sprint races, and parent picnics on the school field.",
    whatToPrepare: [
      "House colour T-shirt",
      "Trainers & sun hat",
      "Water bottle & sunscreen",
      "Spare socks",
    ],
    speechIdeas: [
      "Sports Day is about trying your best and cheering for your team!",
      "Run fairly, jump high, and have fun — that's Sports Day!",
    ],
    activities: [
      "Practice relay baton pass",
      "Stretching routine daily",
      "Make a house cheer",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["House shirt ready", "Trainers packed", "Sun cream applied", "Water bottle filled"],
    costumeCategory: "fancy-dress",
    accent: ["#16a34a", "#0ea5e9"],
  },
  {
    id: "gb-christmas-nativity",
    countries: ["GB"],
    name: "Christmas Nativity / Concert",
    emoji: "🎄",
    dateLabel: "Dec",
    month: 11,
    day: 25,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["christmas", "nativity", "concert", "school"],
    overview:
      "Nativity plays, carol concerts, and jumper day — angel, shepherd, and star costumes.",
    whatToPrepare: [
      "Nativity or concert costume",
      "Christmas jumper for non-uniform day",
      "Song lyrics learnt",
      "Secret Santa gift if assigned",
    ],
    speechIdeas: [
      "Merry Christmas! I am an angel bringing good news of great joy!",
      "We celebrate love and kindness at Christmas. Happy Christmas everyone!",
    ],
    activities: [
      "Paper angel wings craft",
      "Practice carol chorus",
      "Make a Christmas card for family",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume fitted", "Jumper ready", "Lyrics learnt", "Gift wrapped"],
    costumeCategory: "annual-day",
    accent: ["#dc2626", "#166534"],
  },
  {
    id: "gb-red-nose-day",
    countries: ["GB"],
    name: "Red Nose Day",
    emoji: "🔴",
    dateLabel: "Mar (biennial)",
    approxMonth: 2,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["charity", "comedy", "dress-up", "school"],
    overview:
      "Comic Relief fundraiser — funny costumes, red noses, and class challenges for charity.",
    whatToPrepare: [
      "Red nose or face paint",
      "Silly outfit or superhero costume",
      "Small donation in envelope",
      "Joke or funny talent ready",
    ],
    speechIdeas: [
      "We laugh and raise money to help others. That's what Red Nose Day is about!",
      "Here is my joke: Why did the nose go to school? To get picked!",
    ],
    activities: [
      "Design a superhero mask",
      "Class joke-telling round",
      "Sponsored silence challenge",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Red nose packed", "Costume ready", "Donation sealed", "Joke practiced"],
    costumeCategory: "fancy-dress",
    accent: ["#ef4444", "#facc15"],
  },
];
