import type { SchoolEvent } from "../eventTypes";
import { TIMELINE_STANDARD } from "./event-content-shared";

/** Continental Europe school & cultural events (France, Germany, Spain, Italy, etc.). */
export const EVENTS_EU: SchoolEvent[] = [
  {
    id: "eu-carnival",
    countries: ["EU"],
    name: "Carnival / Fasching",
    emoji: "🎭",
    dateLabel: "Feb–Mar (variable)",
    approxMonth: 1,
    category: "Festival",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["carnival", "costume", "parade", "school"],
    overview:
      "Colourful costumes, classroom parades, and masks — a highlight of the school year across Europe.",
    whatToPrepare: [
      "Homemade costume or mask",
      "Face paint (school-safe)",
      "Short carnival greeting",
      "Comfortable shoes for parade",
    ],
    speechIdeas: [
      "Happy Carnival! Today we dress up, dance, and spread joy!",
      "My mask is handmade. Carnival teaches us creativity and fun!",
    ],
    activities: [
      "Paper plate mask craft",
      "Confetti shaker from toilet roll",
      "Learn a carnival song or clap rhythm",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Mask finished", "Paint tested", "Parade time noted"],
    costumeCategory: "fancy-dress",
    accent: ["#a855f7", "#ec4899"],
  },
  {
    id: "eu-europe-day",
    countries: ["EU"],
    name: "Europe Day",
    emoji: "🇪🇺",
    dateLabel: "9 May",
    month: 4,
    day: 9,
    category: "School Event",
    ageGroups: ["6-8", "8-12"],
    tags: ["europe", "unity", "culture", "school"],
    overview:
      "Schools celebrate European unity — flags, languages, and projects about neighbours.",
    whatToPrepare: [
      "EU or country flag colours outfit",
      "Hello in two European languages",
      "Poster about a European country",
      "Short unity speech",
    ],
    speechIdeas: [
      "Europe Day reminds us we are stronger together. Bonjour, Hola, Ciao!",
      "I learned about [country]. We share history, art, and friendship across Europe.",
    ],
    activities: [
      "EU stars circle craft (12 stars)",
      "Match flags to countries game",
      "Write peace wishes on paper doves",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit ready", "Poster done", "Greetings learnt", "Speech practiced"],
    costumeCategory: "fancy-dress",
    accent: ["#2563eb", "#facc15"],
  },
  {
    id: "eu-summer-fest",
    countries: ["EU"],
    name: "Summer Fest / Schulfest",
    emoji: "☀️",
    dateLabel: "Jun (end of term)",
    approxMonth: 5,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["summer", "festival", "performance", "school"],
    overview:
      "End-of-year fair with stalls, songs, and class performances — festive dress encouraged.",
    whatToPrepare: [
      "Summer fest costume or class theme outfit",
      "Song or poem for stage",
      "Stall craft or game ready",
      "Sun hat & water bottle",
    ],
    speechIdeas: [
      "Our summer fest celebrates a great school year. Thank you teachers and friends!",
      "I will perform on stage today. I practiced and I am ready!",
    ],
    activities: [
      "Decorate a festival bunting string",
      "Rehearse class song",
      "Make lemonade stall sign",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Act rehearsed", "Stall materials packed", "Sun gear ready"],
    costumeCategory: "annual-day",
    accent: ["#f59e0b", "#22c55e"],
  },
  {
    id: "eu-st-martin",
    countries: ["EU"],
    name: "St Martin's Lantern Walk",
    emoji: "🏮",
    dateLabel: "11 Nov",
    month: 10,
    day: 11,
    category: "Festival",
    ageGroups: ["3-5", "6-8"],
    tags: ["lantern", "november", "tradition", "school"],
    overview:
      "Lantern parades at dusk — handmade paper lanterns and songs (popular in DE, AT, NL schools).",
    whatToPrepare: [
      "Handmade paper lantern with safe LED tea light",
      "Warm jacket & reflective strip",
      "Lantern song line memorised",
      "Parent escort plan for evening walk",
    ],
    speechIdeas: [
      "I made my lantern with care. St Martin shares light with everyone!",
      "Our lanterns glow in the dark. We walk together and sing together!",
    ],
    activities: [
      "Paper lantern craft with tissue paper",
      "Practice lantern song chorus",
      "Draw St Martin sharing his cloak",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Lantern finished", "LED light tested", "Jacket packed", "Song learnt"],
    costumeCategory: "fancy-dress",
    accent: ["#f97316", "#1e293b"],
  },
  {
    id: "eu-christmas-market",
    countries: ["EU"],
    name: "Christmas Market / Advent",
    emoji: "🎄",
    dateLabel: "Dec",
    month: 11,
    day: 20,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["christmas", "advent", "winter", "school"],
    overview:
      "Advent calendars, Nikolaus boots, and winter concerts — festive crafts and carols.",
    whatToPrepare: [
      "Advent or Nikolaus costume",
      "Handmade ornament for market stall",
      "Carol line or poem",
      "Warm winter outfit",
    ],
    speechIdeas: [
      "Advent is a time of light and kindness. Frohe Weihnachten / Joyeux Noël!",
      "I bring an ornament for our class market. Merry Christmas to all!",
    ],
    activities: [
      "Salt-dough ornament craft",
      "Advent wreath paper craft",
      "Practice first line of Silent Night",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Ornament done", "Costume ready", "Carol practiced", "Winter coat packed"],
    costumeCategory: "annual-day",
    accent: ["#dc2626", "#166534"],
  },
];
