import type { SchoolEvent } from "../eventTypes";
import { TIMELINE_STANDARD } from "./event-content-shared";

export const EVENTS_US: SchoolEvent[] = [
  {
    id: "us-back-to-school",
    countries: ["US", "CA"],
    name: "Back to School",
    emoji: "🎒",
    dateLabel: "Aug–Sep",
    approxMonth: 7,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["school", "supplies", "routine"],
    overview:
      "New year kick-off — fresh supplies, meet-the-teacher night, and getting back into routines.",
    whatToPrepare: [
      "Supply list from school",
      "Labelled backpack & lunch box",
      "First-day outfit picked",
      "Bedtime routine restarted early",
    ],
    speechIdeas: [
      "I am excited for a new school year! I will learn, make friends, and try my best.",
      "Back to school means new books and new adventures. Let's go!",
    ],
    activities: [
      "Decorate a pencil box or folder",
      "Practice morning routine timing",
      "Write 3 goals for the new year",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Shop supplies; label everything" },
      { daysBefore: 3, label: "Restart sleep schedule" },
      { daysBefore: 1, label: "Pack backpack; pick first-day outfit" },
      { daysBefore: 0, label: "Early bedtime; big breakfast" },
    ],
    checklist: ["Supplies packed", "Backpack labelled", "Outfit ready", "Bedtime on track"],
    costumeCategory: "fancy-dress",
    accent: ["#3b82f6", "#8b5cf6"],
  },
  {
    id: "us-halloween",
    countries: ["US", "CA"],
    name: "Halloween",
    emoji: "🎃",
    dateLabel: "31 Oct",
    month: 9,
    day: 31,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["costume", "halloween", "party", "school"],
    overview:
      "Classroom parties, costume parades, and trunk-or-treat — quick DIY costumes from things at home.",
    whatToPrepare: [
      "School-safe costume (no masks/weapons if banned)",
      "Treat bag for party",
      "Face paint or simple makeup",
      "Warm layer if parade is outdoors",
    ],
    speechIdeas: [
      "I am a friendly pumpkin! Trick or treat — I hope you have a sweet Halloween!",
      "Boo! I am a little ghost. Happy Halloween everyone!",
    ],
    activities: [
      "Make a paper plate pumpkin mask",
      "Wrap toilet-paper mummy craft",
      "Practice 'Trick or treat!' with big smile",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "School rules checked", "Treat bag packed", "Makeup tested"],
    costumeCategory: "fancy-dress",
    accent: ["#ea580c", "#7c2d12"],
  },
  {
    id: "us-thanksgiving",
    countries: ["US", "CA"],
    name: "Thanksgiving",
    emoji: "🦃",
    dateLabel: "4th Thu of Nov",
    approxMonth: 10,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["thanksgiving", "gratitude", "craft", "school"],
    overview:
      "School feasts, gratitude crafts, and pilgrim/Native American history activities (age-appropriate).",
    whatToPrepare: [
      "Gratitude card for family or teacher",
      "Simple pilgrim or turkey craft",
      "2-line thank-you speech",
      "Potluck item if school asks",
    ],
    speechIdeas: [
      "I am thankful for my family, my friends, and my school. Happy Thanksgiving!",
      "Thanksgiving reminds us to share and be grateful. I am grateful for you!",
    ],
    activities: [
      "Hand-traced turkey with thankful feathers",
      "Write 5 things you are grateful for",
      "Share a gratitude circle in class",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Craft finished", "Speech ready", "Potluck item (if needed)", "Card for teacher"],
    costumeCategory: "fancy-dress",
    accent: ["#b45309", "#dc2626"],
  },
  {
    id: "us-independence-day",
    countries: ["US"],
    name: "Independence Day (4th of July)",
    emoji: "🇺🇸",
    dateLabel: "4 Jul",
    month: 6,
    day: 4,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["patriotic", "july4", "parade", "school"],
    overview:
      "Red-white-blue dress-up, summer parades, and short speeches about freedom and community.",
    whatToPrepare: [
      "Red, white & blue outfit",
      "Small flag or pin",
      "Patriotic speech (2 lines)",
      "Sunscreen & hat for outdoor events",
    ],
    speechIdeas: [
      "On July 4th we celebrate America's birthday. I am proud to be free!",
      "Fireworks, flags, and friends — Happy Fourth of July!",
    ],
    activities: [
      "Make a star-spangled headband",
      "Draw the flag with 50 stars challenge",
      "Learn first line of 'America the Beautiful'",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit ready", "Flag packed", "Speech practiced", "Sun protection packed"],
    costumeCategory: "fancy-dress",
    accent: ["#dc2626", "#1d4ed8"],
  },
  {
    id: "us-easter",
    countries: ["US", "GB", "AU", "CA", "NZ"],
    name: "Easter",
    emoji: "🐣",
    dateLabel: "Mar/Apr (variable)",
    approxMonth: 3,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["easter", "spring", "craft", "school"],
    overview:
      "Spring egg hunts, bunny crafts, and classroom celebrations — pastel outfits and simple speeches.",
    whatToPrepare: [
      "Pastel outfit or bunny ears",
      "Decorated egg or basket craft",
      "Short spring speech",
      "Basket for egg hunt",
    ],
    speechIdeas: [
      "Happy Easter! Spring brings new flowers and new hope!",
      "I am the Easter Bunny's helper. I hide eggs and spread joy!",
    ],
    activities: [
      "Dye or decorate hard-boiled eggs",
      "Make bunny ears from construction paper",
      "Plant a seed in a cup — watch it grow",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Craft done", "Outfit/ears ready", "Basket packed", "Speech memorised"],
    costumeCategory: "fancy-dress",
    accent: ["#a855f7", "#f472b6"],
  },
  {
    id: "us-christmas",
    countries: ["US", "GB", "AU", "CA", "NZ"],
    name: "Christmas",
    emoji: "🎄",
    dateLabel: "25 Dec",
    month: 11,
    day: 25,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["christmas", "winter", "performance", "school"],
    overview:
      "Winter concerts, Secret Santa, class parties, and Santa/elf dress-up with festive speeches.",
    whatToPrepare: [
      "Festive outfit or character costume",
      "Concert costume from music teacher",
      "Gift for exchange (if assigned)",
      "Holiday speech or song line",
    ],
    speechIdeas: [
      "Merry Christmas! I wish you joy, love, and warm hugs!",
      "I am Santa's helper elf. I spread cheer and kindness!",
    ],
    activities: [
      "Paper snowflake window decorations",
      "Practice concert song at home",
      "Make a handmade gift tag",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Concert outfit ready", "Gift wrapped", "Speech/song practiced", "Party permission signed"],
    costumeCategory: "annual-day",
    accent: ["#dc2626", "#16a34a"],
  },
  {
    id: "us-field-day",
    countries: ["US", "CA", "AU", "NZ"],
    name: "Field Day",
    emoji: "🏅",
    dateLabel: "Spring (school schedule)",
    approxMonth: 4,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["sports", "outdoor", "school", "activity"],
    overview:
      "Outdoor fun stations — relay races, water games, tug-of-war. Dress for movement and sun.",
    whatToPrepare: [
      "Team-colour shirt & athletic shorts",
      "Running shoes & extra socks",
      "Water bottle & sunscreen",
      "Towel for wet games",
    ],
    speechIdeas: [
      "Field Day is about fun and teamwork. I will cheer for everyone!",
      "Run, jump, play — Field Day is the best day of school!",
    ],
    activities: [
      "Practice relay baton hand-off",
      "Stretching routine daily",
      "Make a team cheer chant",
    ],
    prepTimeline: [
      { daysBefore: 7, label: "Confirm team colour & events" },
      { daysBefore: 3, label: "Break in shoes; pack sunscreen" },
      { daysBefore: 1, label: "Pack towel, socks, water bottle" },
      { daysBefore: 0, label: "Light breakfast; arrive ready to move" },
    ],
    checklist: ["Team shirt ready", "Shoes & socks packed", "Sunscreen applied", "Towel in bag"],
    costumeCategory: "fancy-dress",
    accent: ["#0ea5e9", "#22c55e"],
  },
  {
    id: "us-talent-show",
    countries: ["US", "GB", "AU", "CA", "NZ"],
    name: "School Talent Show",
    emoji: "🌟",
    dateLabel: "Spring (school schedule)",
    approxMonth: 3,
    category: "Competition",
    ageGroups: ["6-8", "8-12"],
    tags: ["performance", "talent", "speech", "school"],
    overview:
      "Students showcase singing, dancing, magic, or comedy — costume and rehearsal are key.",
    whatToPrepare: [
      "Act polished to 1–2 minutes",
      "Costume or prop for your talent",
      "Backup plan if music fails",
      "Confidence cue cards (optional)",
    ],
    speechIdeas: [
      "Hi, I'm [name] and tonight I'll perform [act]. I hope you enjoy it!",
      "Thank you for clapping! I practiced hard for this moment!",
    ],
    activities: [
      "Record full run-through on phone",
      "Time your act with a timer",
      "Practice bow and thank-you line",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Act under time limit", "Costume/props ready", "Music file saved", "Bow practiced"],
    costumeCategory: "annual-day",
    accent: ["#eab308", "#a855f7"],
  },
  {
    id: "us-graduation",
    countries: ["US", "CA"],
    name: "Graduation Day",
    emoji: "🎓",
    dateLabel: "May–Jun",
    approxMonth: 5,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["graduation", "milestone", "speech", "school"],
    overview:
      "Moving-up ceremonies for preschool, kindergarten, or grade transitions — caps, gowns, and proud speeches.",
    whatToPrepare: [
      "Cap & gown or school-specified outfit",
      "Short proud speech or quote",
      "Family photo plan",
      "Tissues for parents!",
    ],
    speechIdeas: [
      "I worked hard this year and I am ready for the next grade!",
      "Thank you teachers and family for helping me grow. I did it!",
    ],
    activities: [
      "Make a 'memory year' drawing collage",
      "Practice walking across stage slowly",
      "Write a thank-you note to teacher",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Gown fitted", "Speech ready", "Photo plan set", "Thank-you note written"],
    costumeCategory: "annual-day",
    accent: ["#1e40af", "#fbbf24"],
  },
  {
    id: "us-spring-festival",
    countries: ["US"],
    name: "Spring Festival / Carnival",
    emoji: "🎡",
    dateLabel: "Mar–Apr",
    approxMonth: 3,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["spring", "carnival", "booth", "school"],
    overview:
      "PTA carnivals with game booths, face paint, and spring themes — colourful casual dress.",
    whatToPrepare: [
      "Bright comfortable clothes",
      "Game tickets or cash in envelope",
      "Volunteer shift if family signed up",
      "Sun hat & water bottle",
    ],
    speechIdeas: [
      "Welcome to our Spring Carnival! Games, food, and fun for everyone!",
      "Spring is here! Let's play fair and share smiles!",
    ],
    activities: [
      "Decorate a carnival sign for booth",
      "Practice ring-toss or bean-bag aim",
      "Make a spring flower crown",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit picked", "Tickets/cash ready", "Sun hat packed", "Volunteer time confirmed"],
    costumeCategory: "fancy-dress",
    accent: ["#22d3ee", "#a3e635"],
  },
];
