import type { SchoolEvent } from "../eventTypes";
import { TIMELINE_STANDARD } from "./event-content-shared";

export const EVENTS_AU: SchoolEvent[] = [
  {
    id: "au-australia-day",
    countries: ["AU"],
    name: "Australia Day",
    emoji: "🇦🇺",
    dateLabel: "26 Jan",
    month: 0,
    day: 26,
    category: "Holiday",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["patriotic", "australia", "school", "fancy-dress"],
    overview:
      "Green-and-gold dress-up, BBQ-themed crafts, and short speeches about community and country.",
    whatToPrepare: [
      "Green & gold outfit or Aussie icon costume",
      "Small flag or temporary tattoo",
      "Patriotic speech (2 lines)",
      "Sunscreen & hat for outdoor events",
    ],
    speechIdeas: [
      "Happy Australia Day! I am proud to live in a friendly, fair country.",
      "On Australia Day we celebrate our home and our mates. Aussie, Aussie, Aussie!",
    ],
    activities: [
      "Draw the Southern Cross on paper",
      "Make a koala or kangaroo mask",
      "Learn one verse of Advance Australia Fair",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Outfit ready", "Hat & sunscreen packed", "Speech practiced", "Craft finished"],
    costumeCategory: "fancy-dress",
    accent: ["#16a34a", "#eab308"],
  },
  {
    id: "au-anzac-day",
    countries: ["AU", "NZ"],
    name: "ANZAC Day",
    emoji: "🌺",
    dateLabel: "25 Apr",
    month: 3,
    day: 25,
    category: "School Event",
    ageGroups: ["6-8", "8-12"],
    tags: ["anzac", "remembrance", "assembly", "school"],
    overview:
      "Dawn service reflections, rosemary sprigs, and respectful poems about courage and mateship.",
    whatToPrepare: [
      "Smart school uniform",
      "Handmade rosemary or poppy",
      "Short ANZAC poem",
      "Quiet assembly behaviour",
    ],
    speechIdeas: [
      "We remember the ANZACs who served with bravery. Lest we forget.",
      "ANZAC Day teaches us about courage and looking after our mates.",
    ],
    activities: [
      "Bake ANZAC biscuits at home",
      "Write a thank-you note to service families",
      "Draw a war memorial silhouette art",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Uniform pressed", "Poem learnt", "Craft ready", "Service time confirmed"],
    costumeCategory: "fancy-dress",
    accent: ["#b45309", "#1e3a5f"],
  },
  {
    id: "au-harmony-day",
    countries: ["AU"],
    name: "Harmony Day",
    emoji: "🧡",
    dateLabel: "21 Mar",
    month: 2,
    day: 21,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["diversity", "orange", "culture", "school"],
    overview:
      "Wear orange, share cultural dress, and celebrate everyone's background in class.",
    whatToPrepare: [
      "Orange accessory or outfit",
      "Traditional dress from your culture (optional)",
      "1-line intro about your heritage",
      "Poster or flag drawing",
    ],
    speechIdeas: [
      "Harmony Day means everyone belongs. We are different and that's wonderful!",
      "I wear orange to show respect for all cultures in our school.",
    ],
    activities: [
      "Class world map — pin your family's country",
      "Orange handprint unity collage",
      "Share a word in another language",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Orange item ready", "Cultural dress packed", "Intro practiced", "Poster done"],
    costumeCategory: "fancy-dress",
    accent: ["#ea580c", "#f97316"],
  },
  {
    id: "au-book-week",
    countries: ["AU"],
    name: "Children's Book Week",
    emoji: "📖",
    dateLabel: "Aug (CBWA week)",
    approxMonth: 7,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["books", "parade", "costume", "school"],
    overview:
      "Book character parade — dress as your favourite Australian or international story hero.",
    whatToPrepare: [
      "Book character costume",
      "Book to carry in parade",
      "Character introduction speech",
      "Props from the story",
    ],
    speechIdeas: [
      "I am [character] from [book]. Reading helps me dream big!",
      "Book Week is my favourite — I love dressing up and sharing stories!",
    ],
    activities: [
      "Design a bookmark",
      "Class reading marathon",
      "Draw your character's adventure",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["Costume ready", "Book in bag", "Speech learnt", "Props attached"],
    costumeCategory: "fancy-dress",
    accent: ["#7c3aed", "#0ea5e9"],
  },
  {
    id: "au-athletics-carnival",
    countries: ["AU", "NZ"],
    name: "Athletics / Sports Carnival",
    emoji: "🏅",
    dateLabel: "Term 2–3",
    approxMonth: 8,
    category: "School Event",
    ageGroups: ["3-5", "6-8", "8-12"],
    tags: ["sports", "carnival", "house", "school"],
    overview:
      "House colours, track events, high jump, and faction cheers at the school oval.",
    whatToPrepare: [
      "Faction/house shirt",
      "Running spikes or trainers",
      "Water bottle & sun hat",
      "Sunscreen",
    ],
    speechIdeas: [
      "I run for my house and cheer for my friends. Best day of the year!",
      "Sports carnival teaches teamwork. I will try my best in every race!",
    ],
    activities: [
      "Practice sprint starts",
      "Make a faction banner",
      "Stretching routine before school",
    ],
    prepTimeline: TIMELINE_STANDARD,
    checklist: ["House shirt ready", "Shoes packed", "Sunscreen applied", "Events list checked"],
    costumeCategory: "fancy-dress",
    accent: ["#0ea5e9", "#22c55e"],
  },
];
