/**
 * Machine-readable Decision reason codes only.
 * No human copy.
 */

export const AMY_REASON = {
  MISSION_INCOMPLETE: "MISSION_INCOMPLETE",
  MISSION_COMPLETE: "MISSION_COMPLETE",
  COACH_PREPARED: "COACH_PREPARED",
  COACH_ACTIVE: "COACH_ACTIVE",
  COACH_PAUSED: "COACH_PAUSED",
  COACH_NONE: "COACH_NONE",
  SPEECH_PRIORITY: "SPEECH_PRIORITY",
  SPEECH_CONCERN: "SPEECH_CONCERN",
  CHALLENGE_PRESENT: "CHALLENGE_PRESENT",
  NO_CHALLENGE: "NO_CHALLENGE",
  GUEST_USER: "GUEST_USER",
  SIGNED_IN: "SIGNED_IN",
  PREMIUM_ELIGIBLE: "PREMIUM_ELIGIBLE",
  PREMIUM_UNLOCKED: "PREMIUM_UNLOCKED",
  PREMIUM_LOCKED: "PREMIUM_LOCKED",
  SAFETY_PLACEHOLDER: "SAFETY_PLACEHOLDER",
  BUDGET_HERO: "BUDGET_HERO",
  BUDGET_SECONDARY: "BUDGET_SECONDARY",
  BUDGET_PASSIVE: "BUDGET_PASSIVE",
  /** Future/unknown capability — deterministic, non-fatal. */
  UNKNOWN_CAPABILITY: "UNKNOWN_CAPABILITY",
} as const;

export type AmyReasonCode = (typeof AMY_REASON)[keyof typeof AMY_REASON];

export const AMY_REASON_CODES: readonly AmyReasonCode[] = Object.values(
  AMY_REASON,
);
