/** Auto-generated by scripts/gen-phonics-audio-map-meta.mjs — do not edit manually. */
export const PHONICS_BUNDLED_ASSET_COUNT = 1393;
export const PHONICS_BUNDLED_VERSION = 1;
export const PHONICS_BUNDLED_LIBRARY_VERSION = 1;
