import type { CoachWin } from "./coachWinGenerationService.js";

export function fallbackExtensionWins(failedWinTitle: string, startNumber: number): CoachWin[] {
  const mk = (n: number, title: string, objective: string, deep: string,
    actions: string[], example: string, mistake: string, micro: string, dur: string, sci: string): CoachWin => ({
    win: n, title, objective, deep_explanation: deep, actions,
    example, mistake_to_avoid: mistake, micro_task: micro, duration: dur,
    science_reference: sci,
  });

  // Pool of 18 unique strategies across 6 batches of 3.
  // batchIndex rotates so the SAME 3 cards never appear twice in a row.
  const batchIndex = Math.floor((startNumber - 13) / 3) % 6;

  const batches: (() => [CoachWin, CoachWin, CoachWin])[] = [
    // ── BATCH 0 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Lower the bar by 80%",
        `"${failedWinTitle}" is too big right now — shrink it to 30 seconds`,
        "Behaviour change fails when a new action requires more energy than you have on hard days. BJ Fogg's lab shows habits stick when they are 'tinier than feels useful' — small enough to do on your worst day. One heroic attempt teaches nothing; 30 seconds done daily for 7 days creates a neural groove that bigger steps never could.",
        ["Take the original step and cut it to 30 seconds maximum", "Attach it to an existing anchor (after coffee, before bath)", "Do it even on bad days — consistency matters more than quality", "Track only completion, not outcome"],
        "A mum couldn't sustain '5-min special time'. She shrank to '60 seconds of eye-contact before bath'. After 2 weeks her son started asking for it himself.",
        "Pushing through the original step instead of genuinely shrinking it.",
        "Write the 30-second version of the failed step. Do it once today.",
        "7 days",
        "Tiny Habits methodology (BJ Fogg, Stanford Behaviour Design Lab, 2019)"),
      mk(startNumber + 1,
        "Find the hidden blocker first",
        "No strategy works when a biological need is unmet — find it",
        "When a research-backed strategy repeatedly fails, a hidden blocker is almost always the cause: hunger, sleep debt, sensory overload, or parental depletion. The cortisol spike from unmet biological needs blocks the prefrontal cortex — the very part needed for behaviour change. Fixing the blocker can unlock a stalled strategy overnight.",
        ["Audit your child's last 48 hours: sleep hours, meals, screen time, transitions", "Audit your own state: sleep, stress, support", "Rank the most depleted factor (1 = worst)", "Fix that single lever for 3 days before re-trying the strategy"],
        "Dad's 'connection time' kept failing. His son was getting 9 hrs sleep instead of 11. Moving bedtime 90 min earlier fixed it — connection clicked within days.",
        "Blaming the strategy when unmet biology is the real wall.",
        "Name one biological factor (child OR yours) that needs fixing before this strategy can land.",
        "3–5 days",
        "Maslow's Hierarchy of Needs; cortisol/prefrontal cortex research (Arnsten, 1998)"),
      mk(startNumber + 2,
        "Flip the angle: structure ↔ autonomy",
        "If gentle hasn't worked, try structured. If strict hasn't worked, add autonomy",
        "Different temperaments respond to opposite angles. High-sensitivity children often need MORE structure to feel safe; strong-willed children need MORE autonomy to engage willingly. If your current approach hasn't moved the needle in 2 weeks, the philosophy isn't wrong — the fit is wrong for THIS child. Switch the angle while keeping the warmth.",
        ["If you've been gentle: add ONE clear, non-negotiable rule (no debate, just warmth)", "If you've been strict: give ONE daily choice with zero parental opinion attached", "Watch your child's first 3-day response — that's real data", "Commit to the new angle for a full week before evaluating"],
        "A mum's gentle bedtime approach stalled. She added a firm 7:30 lights-out + 15-min cuddle. Bedtime fights ended within 4 days.",
        "Switching angles every 3 days — the new approach needs 7 full days to show results.",
        "Decide right now: more structure or more autonomy? Pick one action to try tonight.",
        "7 days",
        "Goodness-of-fit theory (Chess & Thomas, 1977); temperament research"),
    ],
    // ── BATCH 1 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Use a When-Then bridge",
        "Link the new behaviour to an existing daily trigger",
        "Implementation intentions — 'When X happens, I will do Y' — triple follow-through rates compared to vague intentions. The brain stores if-then pairs in the basal ganglia, where automatic habits live. The key is specificity: an exact trigger ('when we close the front door') beats a time ('every evening'). Children's behaviour responds the same way.",
        ["Pick an existing daily moment your child reliably reaches (door, lunchbox, shoes off)", "State the bridge out loud: 'When you put your shoes away, then we do special time'", "Keep the THEN action under 2 minutes at first", "Repeat the exact same wording for 10 days — consistency cements the link"],
        "A family added 'When your bag is hung up, then we get 5 minutes of story time.' Bag-hanging went from daily battle to automatic in 9 days.",
        "Changing the wording each day — the brain needs the EXACT same trigger phrase to automate.",
        "Write one When-Then statement for today using a trigger your child hits 100% of the time.",
        "10 days",
        "Implementation intentions research (Peter Gollwitzer, NYU, 1999); habit loop science"),
      mk(startNumber + 1,
        "Add a sensory anchor",
        "Use a physical or sensory cue to shift your child's state before the hard step",
        "The nervous system must be regulated before the cortex can engage with demands. Sensory input (deep pressure, slow breath, cold water, rhythmic movement) activates the vagus nerve and drops heart rate within 90 seconds — making cooperation physiologically possible. This isn't a bribe; it's biology.",
        ["Identify when your child's body is dysregulated (tight fists, avoidance, loud voice)", "Offer a 60-second sensory reset BEFORE making the request: bear hug, 3 slow breaths together, cold water on wrists", "Only make the request after you see the body soften", "Never use the sensory reset as a bargaining chip"],
        "A dad tried 'homework time' when his daughter came home wired from school. Added 10-min outdoor swing time first. Homework resistance dropped by 70% within a week.",
        "Using the sensory reset as a reward or after the meltdown has started — it must come before.",
        "Pick one sensory reset (swing, hug, cold water, breath) and offer it before tonight's hardest transition.",
        "7–10 days",
        "Polyvagal theory (Stephen Porges, 2011); sensory processing research (Ayres, 1972)"),
      mk(startNumber + 2,
        "Co-regulate first, redirect second",
        "Your calm is the strategy — get regulated before you try to change behaviour",
        "Children co-regulate through their parent's nervous system before age 12. If you approach a dysregulated child while activated yourself, you escalate — not calm — their system. Daniel Siegel's neuroscience: a regulated adult presence lowers cortisol in a child within 4 minutes. The 'strategy' isn't the words you say; it's your state.",
        ["Notice your own activation level before approaching (1–10 scale)", "If you're above 6, take 90 seconds first: 3 slow exhales, jaw drop, shoulder drop", "Approach with a soft face and lower body position (same height as child)", "Say less — one word or a calm presence is more powerful than explanation"],
        "A mum who kept escalating bedtime fights started sitting silently next to her son for 3 minutes before speaking. Fights reduced by half in a week.",
        "Trying to reason or redirect before both of you are physiologically calm.",
        "Tonight: rate your activation before each hard parenting moment. Breathe first if above 5.",
        "14 days",
        "Co-regulation & interpersonal neurobiology (Dan Siegel, 2012); polyvagal theory"),
    ],
    // ── BATCH 2 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Make it visible with a simple chart",
        "The brain responds to visible progress — a chart does half the work",
        "Visual tracking externalises effort, making invisible progress concrete. Self-determination theory shows that seeing your own progress strengthens intrinsic motivation. For children, a simple sticker chart isn't a bribe — it's a representation of competence they can hold in their hands. The key is keeping it simple: one behaviour, one mark, same time each day.",
        ["Choose exactly ONE behaviour to track — not three", "Make the chart together with your child so they own it", "Add a mark immediately after the behaviour — delay kills the loop", "Review the chart together at the same daily moment (morning or bedtime)"],
        "A mum tracking 'morning shoes before 8am' with a simple chart. Son went from 40% to 90% compliance in 2 weeks — without any reward other than seeing his own streak.",
        "Tracking multiple behaviours or missing the immediate mark — both break the feedback loop.",
        "Draw a 7-box row on paper right now. Tell your child: one mark per day for this one thing.",
        "14 days",
        "Self-determination theory (Deci & Ryan, 1985); visual feedback loops in behaviour change"),
      mk(startNumber + 1,
        "Use play as the delivery vehicle",
        "If the direct approach isn't working, smuggle the skill inside a game",
        "Play is the brain's preferred learning state: dopamine rises, threat response drops, and the prefrontal cortex opens to new information. Stuart Brown's research shows that play-based rehearsal of skills transfers to real-life compliance faster than instruction. The trick is never revealing the 'lesson' — let it be purely fun.",
        ["Turn the hard task into a game: timer race, silly voice, stuffed animal role-play", "Never correct or teach during play — just follow your child's lead", "Repeat the same game for 5 days so the skill gets reinforced", "Gradually let the game drift toward the real situation"],
        "A dad whose daughter refused teeth-brushing turned it into a 'monster detector' game with a flashlight. She was brushing voluntarily within 3 days.",
        "Mixing game-mode with instruction-mode in the same moment — keep them completely separate.",
        "Design a 3-minute game around tonight's hardest task. No teaching — just fun.",
        "10 days",
        "Play science (Stuart Brown, 2009); Dr Lawrence Cohen's Playful Parenting (2001)"),
      mk(startNumber + 2,
        "Find the strength inside the difficulty",
        "Reframe the 'problem' behaviour as a strength running too hot",
        "Strength-based parenting, rooted in positive psychology, shifts the parent's lens from deficit to capacity. A child who 'won't listen' is often demonstrating strong autonomy and self-direction. A child who 'overreacts' often has deep emotional sensitivity. When parents name the strength (not the problem), children's self-regulation improves because shame drops and identity shifts.",
        ["Name the positive version of the difficult trait (persistent, passionate, sensitive, energetic)", "Say it to your child directly: 'You have such strong feelings — that's a real gift'", "Redirect the ENERGY of the trait, not the trait itself", "Stop using problem-framing language ('always', 'never', 'why can't you just')"],
        "Parents reframed 'she's so dramatic' to 'she feels things so deeply'. Changed their own response tone; daughter's meltdown frequency halved in 3 weeks.",
        "Using the strength reframe as a hollow compliment rather than a genuine belief shift.",
        "Name one strength your child has that the 'problem' behaviour is a version of. Say it to them today.",
        "Ongoing",
        "Positive psychology (Martin Seligman, 2002); strength-based parenting (Lea Waters, 2017)"),
    ],
    // ── BATCH 3 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Repair the rupture explicitly",
        "A brief repair conversation resets the relationship and makes the next attempt safer",
        "John Gottman's research shows it's not conflict that damages children — it's unrepaired conflict. A simple, sincere repair ('I was too loud earlier, that wasn't okay') rebuilds attachment security, which is the neurological foundation on which all behaviour change rests. Children who receive explicit repairs show lower cortisol and better cooperation than those who receive only time.",
        ["Wait until both of you are calm (at least 30 minutes after a hard moment)", "Make eye contact and name what happened without defensiveness", "Say what YOU did: 'I got frustrated and raised my voice — that's on me'", "Keep it under 60 seconds — children don't need long explanations, just sincerity"],
        "A dad who rarely apologised started doing 1-sentence repairs after hard evenings. His son began coming to him voluntarily — relationship and cooperation both improved.",
        "Over-explaining or turning the repair into a teaching moment — keep it short and accountable.",
        "Think of the last hard moment. Tonight, offer a one-sentence repair with eye contact.",
        "Ongoing",
        "Gottman's repair theory (1999); attachment & rupture-repair research (Tronick, 1989)"),
      mk(startNumber + 1,
        "Audit your own emotional state pattern",
        "When nothing is working, the pattern is often in the parent's nervous system, not the child",
        "Ross Greene and Daniel Siegel both point to a hard truth: parental emotional arousal is the single strongest predictor of child behaviour escalation. When a parent's window of tolerance is narrow (from stress, poor sleep, or their own childhood patterns), the child's normal behaviour triggers disproportionate responses — and the child's nervous system learns dysregulation. Shifting the parent's pattern often shifts the child's without any direct intervention.",
        ["For 3 days, track your own emotional arousal on a 1-10 scale at meal, homework, and bedtime", "Identify your personal depletion signals (shallow breath, tight chest, clipped sentences)", "Build one daily practice that widens your window: 20-min walk, 7-hour sleep target, one adult conversation", "Notice whether your child's behaviour shifts when YOUR state improves"],
        "A mum realised she was always at 8/10 by 5pm when her son's behaviour peaked. She added a 15-minute solo walk at 4:30. His evening meltdowns dropped significantly.",
        "Waiting until you're dysregulated to try to regulate — build the resource before you need it.",
        "Track your arousal at 3 key moments today (1–10). Identify your earliest warning signal.",
        "14 days",
        "Window of tolerance (Dan Siegel, 1999); Collaborative Problem Solving (Ross Greene, 2014)"),
      mk(startNumber + 2,
        "Natural consequences with warm curiosity",
        "Let the situation teach — with you alongside, not fixing it",
        "Alfred Adler's foundational research, extended by Jane Nelsen's Positive Discipline, shows children learn most durably from natural consequences when a trusted adult is present with curiosity rather than judgment. The parent's role is not to protect the child from the consequence, but to stay warm while it lands, and ask: 'What do you think happened? What could work differently?' This activates the child's own problem-solving brain.",
        ["Identify a consequence that naturally flows from the behaviour (not a punishment you invent)", "Warn once calmly, then step back and let it happen", "After the consequence, wait until calm and ask: 'What happened? What would you do differently?'", "Resist rescuing — your discomfort is not the signal to intervene"],
        "A mum stopped packing her son's forgotten lunch. He was hungry once. He never forgot again. She stayed warm and asked 'What's your plan for tomorrow?' — no lecture.",
        "Confusing natural consequences with punishment — tone and timing make all the difference.",
        "Identify one natural consequence you've been shielding your child from. Let it land today.",
        "Situation-dependent",
        "Natural consequences theory (Alfred Adler); Positive Discipline (Jane Nelsen, 1981)"),
    ],
    // ── BATCH 4 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Problem-solve together at a calm moment",
        "Invite your child to co-create the solution — their buy-in is the strategy",
        "Ross Greene's Collaborative Problem Solving model (used in clinical settings worldwide) shows that children who help design the solution follow through at 3× the rate of those who receive solutions. The child's prefrontal cortex must be engaged, which is only possible when both parent and child are calm. The magic is in the question: 'I've noticed X is hard — what do you think we could try?'",
        ["Wait for a genuinely calm moment — never raise the topic during or just after a conflict", "Start with curiosity, not a solution: 'I've noticed X — what's making it hard for you?'", "Listen fully without correcting. Then share your concern (not your solution)", "Ask together: 'What could work for both of us?' and pick ONE thing to try for 5 days"],
        "A dad and his 7-year-old co-designed a 'homework deal': 20-min work, then 10-min Lego. Son's follow-through went from 30% to 85% in 2 weeks because he'd built the plan himself.",
        "Doing collaborative problem-solving during a conflict or within 20 minutes after one — timing is everything.",
        "Tonight at a calm moment, ask your child: 'What makes [this] hard for you?' Just listen.",
        "Ongoing",
        "Collaborative Problem Solving (Ross Greene, The Explosive Child, 2014)"),
      mk(startNumber + 1,
        "Narrate the positive out loud",
        "Catching and naming good behaviour cements it faster than any correction",
        "Behavioural science consistently shows a 5:1 positive-to-negative feedback ratio predicts healthy family dynamics (Gottman) and child compliance. Yet most parents narrate problems and stay silent during good moments. Specific, immediate narration ('You stayed calm when your sister took your toy — that took real control') activates the dopamine-reward loop and makes the behaviour more likely to repeat.",
        ["For 3 days, commit to narrating every positive behaviour you notice — out loud, immediately", "Be specific: name the behaviour AND the quality it shows ('You shared without being asked — that's generosity')", "Don't add 'but' or a correction after the narration — just let it land", "Aim for 5 positive narrations for every 1 correction across the day"],
        "A mum shifted from mostly correcting to narrating positives for 1 week. Her son's cooperative behaviour increased and he started narrating his own good choices aloud.",
        "Saying 'good job' — it's too vague to reinforce anything. Specificity is the entire mechanism.",
        "Set a phone reminder for 3 times today to narrate something specific your child did well.",
        "14 days",
        "5:1 ratio research (John Gottman, 1994); positive reinforcement science (Skinner; Bandura)"),
      mk(startNumber + 2,
        "Shrink the transition, not the task",
        "Most resistance happens in the gap between activities — target that gap",
        "Transitions (stopping one thing, starting another) are neurologically expensive. The prefrontal cortex must inhibit one activity while orienting to another — this costs energy that young children and dysregulated older ones simply don't have. Research on transition warnings, countdown rituals, and 'bridging' (naming what comes after the transition) reduces resistance by up to 60% without changing the task itself.",
        ["Give a 5-minute verbal warning before every major transition ('5 more minutes, then bath')", "Add a 1-minute warning immediately before the switch ('1 minute, then we go')", "Use a consistent bridging phrase: 'After bath, then story time' — make the next good thing visible", "Create one transition ritual that stays the same every day (a song, a countdown, a handshake)"],
        "A mum added '5-min warning + song' to every transition for her 5-year-old. Screen-time tantrums dropped from daily to once a week within 10 days.",
        "Giving warnings but not following through — the child learns the warning means nothing.",
        "Pick one daily transition that's always hard. Add a 5-min warning starting tonight.",
        "10 days",
        "Executive function & transition research (Zelazo, 2006); Siegel & Bryson, The Whole-Brain Child (2011)"),
    ],
    // ── BATCH 5 ────────────────────────────────────────────────────────
    () => [
      mk(startNumber,
        "Match the strategy to the child's developmental stage",
        "A strategy for a 9-year-old won't work on a 4-year-old — stage-match everything",
        "Jean Piaget's developmental stages and modern neuroscience confirm that children's brains operate in qualitatively different modes at different ages. Abstract reasoning, impulse control, and empathy are NOT available to a 4-year-old — they're not choosing to be difficult, they're being 4. Every strategy in this plan was designed for your child's age group, but if it's not landing, a mismatch in expectation is almost always involved.",
        ["Write down your child's age and revisit what's developmentally normal for that stage", "For under-5s: reduce words, increase physical cues and play", "For 6-9: use concrete rules, predictable structure, and natural consequences", "For 10+: include them in problem-solving, explain the 'why', give more autonomy"],
        "A dad kept explaining 'why we don't hit' to his 3-year-old using paragraphs. Switched to a one-word redirect ('kind hands') + physical demonstration. Hitting stopped within 5 days.",
        "Using logic-heavy explanations with children under 7 — they need concrete, physical, short.",
        "Look up ONE developmental fact about your child's age group today. Adjust one expectation.",
        "Ongoing",
        "Piaget's developmental stages (1952); neurodevelopmental research (Zelazo & Carlson, 2012)"),
      mk(startNumber + 1,
        "Reduce cognitive load for both of you",
        "Too many rules and too many decisions are the silent killers of consistency",
        "Decision fatigue is real. Roy Baumeister's research shows willpower and decision-making share the same finite daily resource. Parents who are managing multiple behaviour strategies simultaneously burn through that resource by 3pm. Children whose environments have too many rules experience the same depletion. Simplifying to ONE rule, ONE consequence, ONE routine at a time restores capacity for both.",
        ["Count how many behaviour strategies you are currently running simultaneously", "Pick the ONE that matters most this week — put the others on hold", "Reduce household rules to 3 maximum, stated positively ('We use kind words')", "Reduce the child's daily decisions to 2–3 max — too much choice creates anxiety, not confidence"],
        "A mum running 6 strategies at once dropped to 1 (morning routine only). Consistency jumped because she had the energy to follow through every single time.",
        "Adding a new strategy before the current one has had 10 days — stack one at a time.",
        "List every behaviour goal you're currently working on. Cross out all but ONE. Focus there.",
        "10 days per strategy",
        "Ego depletion & decision fatigue (Roy Baumeister, 1998); choice overload (Barry Schwartz, 2004)"),
      mk(startNumber + 2,
        "Change the environment, not the child",
        "Redesigning the space removes the trigger — no willpower required",
        "Kurt Lewin's field theory and modern behavioural economics (Thaler & Sunstein) show that environment shapes behaviour more powerfully than intention. If your child always melts down in the kitchen after school, the kitchen at 4pm IS the trigger. Changing the environment (different room, snack first, outdoor time) removes the cue entirely — no willpower, no negotiation, no strategy required.",
        ["Map the last 3 difficult moments: where were you, what time, what just happened before?", "Identify the consistent environmental pattern (location, time, hunger, transition)", "Change ONE environmental variable: move the activity, change the time, add a buffer", "Run the new environment for 7 days and observe — environment changes work faster than behaviour interventions"],
        "A family noticed meltdowns happened every day at the dinner table. Moved to eating outside twice a week. Dinner-time stress halved — same food, same family, different environment.",
        "Trying to change the child's behaviour without changing the trigger environment first.",
        "Find the common environmental thread in your last 3 hard moments. Change one variable tonight.",
        "7 days",
        "Field theory (Kurt Lewin, 1936); Nudge theory (Thaler & Sunstein, 2008); behavioural design"),
    ],
  ];

  const [w0, w1, w2] = batches[batchIndex]();
  return [w0, w1, w2];
}

/** Single adaptive win — rotates through the same strategy pool as the 3-win batches. */
export function fallbackExtensionWin(failedWinTitle: string, startNumber: number): CoachWin {
  const slotIndex = Math.max(0, (startNumber - 13) % 3);
  const alignedStart = startNumber - slotIndex;
  const batch = fallbackExtensionWins(failedWinTitle, alignedStart);
  return { ...batch[slotIndex]!, win: startNumber };
}
