/**
 * useInfantPoemPlayer — ElevenLabs-backed poem player.
 *
 * Plays a calming poem aloud using a real human voice via the shared
 * `/api/tts/synthesize` pipeline. The server caches each MP3 by content
 * hash, so every poem is generated by ElevenLabs ONCE GLOBALLY and then
 * served from cache to every user — keeping per-user cost effectively
 * zero while replacing the previous robotic browser SpeechSynthesis voice.
 *
 * Capabilities:
 *   - play / pause / resume / stop
 *   - loop ON by default (HTMLAudioElement.loop = true)
 *   - sleep timer (15m / 30m / 1h) that stops playback when it expires
 *   - volume control (0..1) — applied LIVE to audio.volume, no restart
 *   - 2-second real fade-in (ramps audio.volume from 0 → target)
 *   - loading state surfaced while the synth request is in flight
 *   - graceful no-op when HTMLAudioElement is unavailable (SSR / older
 *     environments). `supported` reflects this.
 */
import { useCallback, useEffect, useRef, useState } from "react";

import { useAuthFetch } from "@/hooks/use-auth-fetch";
import { resolveApiMediaUrl } from "@/lib/api";

const FADE_IN_MS = 2000;
const FADE_TICK_MS = 60;

const clamp01 = (n: number) => Math.max(0, Math.min(1, n));

export interface PoemPlayerOptions {
  /** The poem text to read aloud (joined lines). Required unless `audioUrl`. */
  text: string;
  /** Optional pre-recorded MP3 URL — preferred when present (skips synth). */
  audioUrl?: string;
  /** Reserved for future per-poem language hints; ignored today (server picks the voice). */
  lang?: string;
}

export interface PoemPlayer {
  isPlaying: boolean;
  isPaused: boolean;
  /** True while the synth request is in flight (before audio.play() fires). */
  isLoading: boolean;
  /** True while the 2s fade-in window is still active after playback starts. */
  fadeInProgress: boolean;
  loop: boolean;
  volume: number;
  timerMs: number | null;
  remainingMs: number | null;
  /** True if the runtime exposes `Audio` (always true in modern browsers). */
  supported: boolean;
  /** Last error code from synth or playback, or null. */
  error: string | null;
  play: (opts: PoemPlayerOptions) => Promise<void>;
  pause: () => void;
  resume: () => void;
  stop: () => void;
  setLoop: (loop: boolean) => void;
  setVolume: (v: number) => void;
  setTimer: (ms: number | null) => void;
}

interface SynthesizeResponse {
  ok: true;
  cacheKey: string;
  audioUrl: string;
  cached: boolean;
  charCount: number;
  contentType: string;
}

export function useInfantPoemPlayer(): PoemPlayer {
  const authFetch = useAuthFetch();

  const [isPlaying, setIsPlaying] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [fadeInProgress, setFadeInProgress] = useState(false);
  // Spec: "Loop (ON by default)".
  const [loop, setLoopState] = useState(true);
  const [volume, setVolumeState] = useState(0.85);
  const [timerMs, setTimerMsState] = useState<number | null>(null);
  const [remainingMs, setRemainingMs] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const supported = typeof window !== "undefined" && typeof Audio !== "undefined";

  // ── Refs ──────────────────────────────────────────────────────────────────
  // Audio element, in-flight fetch, fade interval, and a monotonic request id
  // so old play() calls can be detected as superseded after async resolution.
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const fadeIntervalRef = useRef<number | null>(null);
  const reqIdRef = useRef(0);

  // Mirror loop + volume in refs so the audio element + fade ramp pick up
  // live changes without recreating callbacks.
  const loopRef = useRef(loop);
  const volumeRef = useRef(volume);
  useEffect(() => { loopRef.current = loop; }, [loop]);
  useEffect(() => { volumeRef.current = volume; }, [volume]);

  // Sleep-timer accounting.
  const timerStartRef = useRef<number | null>(null);
  const timerTotalRef = useRef<number | null>(null);

  // ── Internal helpers ──────────────────────────────────────────────────────
  const clearFade = useCallback(() => {
    if (fadeIntervalRef.current !== null) {
      window.clearInterval(fadeIntervalRef.current);
      fadeIntervalRef.current = null;
    }
    setFadeInProgress(false);
  }, []);

  const teardownAudio = useCallback(() => {
    const a = audioRef.current;
    if (a) {
      a.onended = null;
      a.onerror = null;
      try { a.pause(); } catch { /* noop */ }
      try { a.removeAttribute("src"); } catch { /* noop */ }
      try { a.load(); } catch { /* noop */ }
    }
    audioRef.current = null;
  }, []);

  const abortInFlight = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }
  }, []);

  /**
   * Start the 2s fade-in by ramping audio.volume from 0 → volumeRef.current.
   * Re-reads volumeRef each tick so user volume changes during the fade are
   * respected smoothly (target tracks the slider live).
   */
  const beginFadeIn = useCallback(() => {
    clearFade();
    const a = audioRef.current;
    if (!a) return;
    a.volume = 0;
    setFadeInProgress(true);
    const startedAt = Date.now();
    const interval = window.setInterval(() => {
      const a2 = audioRef.current;
      if (!a2) { clearFade(); return; }
      const elapsed = Date.now() - startedAt;
      const progress = Math.min(1, elapsed / FADE_IN_MS);
      a2.volume = clamp01(volumeRef.current * progress);
      if (progress >= 1) clearFade();
    }, FADE_TICK_MS);
    fadeIntervalRef.current = interval;
  }, [clearFade]);

  // ── Public API ────────────────────────────────────────────────────────────
  const play = useCallback(
    async (opts: PoemPlayerOptions) => {
      if (!supported) return;
      const text = (opts.text ?? "").trim();
      if (!text && !opts.audioUrl) return;

      // Cancel anything previous + reset state.
      const myId = ++reqIdRef.current;
      abortInFlight();
      clearFade();
      teardownAudio();
      setError(null);
      setIsPaused(false);
      setIsPlaying(false);
      setIsLoading(true);

      try {
        let audioUrl = opts.audioUrl;

        // No pre-baked MP3? Hit the server to synth (or fetch from cache).
        if (!audioUrl) {
          const controller = new AbortController();
          abortRef.current = controller;
          const synthRes = await authFetch("/api/tts/synthesize", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ text }),
            signal: controller.signal,
          });
          if (myId !== reqIdRef.current) return; // user moved on
          if (!synthRes.ok) {
            const body = (await synthRes.json().catch(() => ({}))) as { error?: string };
            throw new Error(body.error ?? `synthesize_failed_${synthRes.status}`);
          }
          const data = (await synthRes.json()) as SynthesizeResponse;
          if (myId !== reqIdRef.current) return;
          audioUrl = data.audioUrl;
        }

        // Build the audio element. The /api/tts/audio/:key.mp3 route is
        // public (content-addressed) so <audio> can load it without a token.
        const audio = new Audio(resolveApiMediaUrl(audioUrl));
        audio.loop = loopRef.current;
        audio.volume = 0; // begin silent for fade-in
        audio.preload = "auto";
        audio.onended = () => {
          if (myId !== reqIdRef.current) return;
          // For looped playback this never fires (browser auto-loops).
          setIsPlaying(false);
          setIsPaused(false);
          clearFade();
        };
        audio.onerror = () => {
          if (myId !== reqIdRef.current) return;
          setError("playback_failed");
          setIsPlaying(false);
          setIsPaused(false);
          clearFade();
        };
        audioRef.current = audio;

        await audio.play();
        if (myId !== reqIdRef.current) {
          // User cancelled between play() being scheduled and resolving —
          // tear the audio back down so it doesn't keep playing.
          try { audio.pause(); } catch { /* noop */ }
          teardownAudio();
          return;
        }
        setIsPlaying(true);
        setIsLoading(false);
        beginFadeIn();
      } catch (err) {
        const name = (err as { name?: string })?.name;
        if (name === "AbortError") return; // user-initiated cancel
        if (myId !== reqIdRef.current) return;
        setError(err instanceof Error ? err.message : "tts_failed");
        teardownAudio();
        setIsPlaying(false);
      } finally {
        if (myId === reqIdRef.current) {
          if (abortRef.current) abortRef.current = null;
          setIsLoading(false);
        }
      }
    },
    [supported, authFetch, abortInFlight, clearFade, teardownAudio, beginFadeIn],
  );

  const pause = useCallback(() => {
    const a = audioRef.current;
    if (!a) return;
    try { a.pause(); } catch { /* noop */ }
    setIsPaused(true);
  }, []);

  const resume = useCallback(() => {
    const a = audioRef.current;
    if (!a) return;
    void a.play().catch(() => { /* ignore — onerror surfaces it */ });
    setIsPaused(false);
  }, []);

  const stop = useCallback(() => {
    reqIdRef.current += 1;
    abortInFlight();
    clearFade();
    teardownAudio();
    setIsPlaying(false);
    setIsPaused(false);
    setIsLoading(false);
  }, [abortInFlight, clearFade, teardownAudio]);

  // Live: applies to currently-playing audio with no restart.
  const setLoop = useCallback((next: boolean) => {
    setLoopState(next);
    if (audioRef.current) audioRef.current.loop = next;
  }, []);

  // Live: HTMLAudioElement supports volume changes mid-playback. The fade
  // ramp tracks volumeRef each tick, so we only push it directly when no
  // fade is in progress (otherwise the fade would fight the slider).
  const setVolume = useCallback((v: number) => {
    const next = clamp01(v);
    setVolumeState(next);
    if (audioRef.current && fadeIntervalRef.current === null) {
      audioRef.current.volume = next;
    }
  }, []);

  const setTimer = useCallback((ms: number | null) => {
    setTimerMsState(ms);
  }, []);

  // ── Sleep timer tick ───────────────────────────────────────────────────────
  // Re-arms only when the user picks a new pill — adding/removing the loop
  // toggle or changing volume mid-countdown does NOT reset elapsed time.
  useEffect(() => {
    if (timerMs === null) {
      setRemainingMs(null);
      timerStartRef.current = null;
      timerTotalRef.current = null;
      return;
    }
    timerStartRef.current = Date.now();
    timerTotalRef.current = timerMs;
    setRemainingMs(timerMs);
    const interval = window.setInterval(() => {
      if (timerStartRef.current === null || timerTotalRef.current === null) return;
      const elapsed = Date.now() - timerStartRef.current;
      const remaining = Math.max(0, timerTotalRef.current - elapsed);
      setRemainingMs(remaining);
      if (remaining <= 0) {
        window.clearInterval(interval);
        // Inline stop to avoid useCallback dependency cycle.
        reqIdRef.current += 1;
        if (abortRef.current) { abortRef.current.abort(); abortRef.current = null; }
        if (fadeIntervalRef.current !== null) {
          window.clearInterval(fadeIntervalRef.current);
          fadeIntervalRef.current = null;
        }
        const a = audioRef.current;
        if (a) {
          a.onended = null;
          a.onerror = null;
          try { a.pause(); } catch { /* noop */ }
          try { a.removeAttribute("src"); } catch { /* noop */ }
          try { a.load(); } catch { /* noop */ }
        }
        audioRef.current = null;
        setFadeInProgress(false);
        setIsPlaying(false);
        setIsPaused(false);
        setIsLoading(false);
      }
    }, 1000);
    return () => window.clearInterval(interval);
  }, [timerMs]);

  // ── Cleanup on unmount ────────────────────────────────────────────────────
  useEffect(() => {
    return () => {
      reqIdRef.current += 1;
      if (abortRef.current) abortRef.current.abort();
      if (fadeIntervalRef.current !== null) window.clearInterval(fadeIntervalRef.current);
      const a = audioRef.current;
      if (a) {
        a.onended = null;
        a.onerror = null;
        try { a.pause(); } catch { /* noop */ }
        try { a.removeAttribute("src"); } catch { /* noop */ }
        try { a.load(); } catch { /* noop */ }
      }
      audioRef.current = null;
    };
  }, []);

  return {
    isPlaying,
    isPaused,
    isLoading,
    fadeInProgress,
    loop,
    volume,
    timerMs,
    remainingMs,
    supported,
    error,
    play,
    pause,
    resume,
    stop,
    setLoop,
    setVolume,
    setTimer,
  };
}
