import type { EducationStageCode, StageMetadata } from "./types";

/** Global metadata — age bounds are enforced per-country in country-config. */
export const STAGE_METADATA: Record<EducationStageCode, Omit<StageMetadata, "minMonths" | "maxMonths">> = {
  at_home: {
    code: "at_home",
    learningEnvironment: "home",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: null,
  },
  daycare: {
    code: "daycare",
    learningEnvironment: "daycare",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: null,
  },
  playgroup: {
    code: "playgroup",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Playgroup",
  },
  nursery: {
    code: "nursery",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Nursery",
  },
  lkg: {
    code: "lkg",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "LKG / KG",
  },
  ukg: {
    code: "ukg",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "UKG",
  },
  preschool: {
    code: "preschool",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Preschool",
  },
  pre_k: {
    code: "pre_k",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Pre-K",
  },
  kindergarten: {
    code: "kindergarten",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Kindergarten",
  },
  reception: {
    code: "reception",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Reception",
  },
  kindy: {
    code: "kindy",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Kindy",
  },
  prep: {
    code: "prep",
    learningEnvironment: "early_learning",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Prep",
  },
  homeschool: {
    code: "homeschool",
    learningEnvironment: "homeschool",
    impliesSchoolGoing: false,
    requiresClass: false,
    requiresSchedule: false,
    childClassValue: "Homeschool",
  },
  school: {
    code: "school",
    learningEnvironment: "formal_school",
    impliesSchoolGoing: true,
    requiresClass: true,
    requiresSchedule: true,
    childClassValue: null,
  },
};
