import { A4_HEIGHT, A4_WIDTH, PAGE_MARGIN, type WorksheetElement } from "./types.js";
import type { SchoolBrandingProfile } from "./school-branding.js";

function footerText(profile: SchoolBrandingProfile, pageNumber: number, totalPages: number): string {
  const parts: string[] = [];
  const f = profile.footer;

  if (f.showAddress && profile.address?.trim()) parts.push(profile.address.trim());
  if (f.showPhone && profile.phone?.trim()) parts.push(`Tel: ${profile.phone.trim()}`);
  if (f.showEmail && profile.email?.trim()) parts.push(profile.email.trim());
  if (f.showWebsite && profile.website?.trim()) parts.push(profile.website.trim());
  if (profile.footerText?.trim()) parts.push(profile.footerText.trim());
  if (f.showConfidential) {
    parts.push(profile.footerConfidentialText?.trim() || "For school use only — not for public distribution.");
  }
  if (f.showPageNumber) parts.push(`Page ${pageNumber} of ${totalPages}`);
  if (f.showGeneratedBy) parts.push("Generated by AmyNest Worksheet Studio");

  return parts.join("  ·  ");
}

export function hasActiveFooter(profile: SchoolBrandingProfile): boolean {
  const f = profile.footer;
  return (
    f.showAddress || f.showPhone || f.showEmail || f.showWebsite ||
    f.showConfidential || f.showPageNumber || f.showGeneratedBy ||
    Boolean(profile.footerText?.trim())
  );
}

export function buildSchoolFooterElements(
  profile: SchoolBrandingProfile,
  pageNumber: number,
  totalPages: number,
): WorksheetElement[] {
  if (!hasActiveFooter(profile)) return [];

  const content = footerText(profile, pageNumber, totalPages);
  if (!content) return [];

  const elements: WorksheetElement[] = [];

  elements.push({
    id: `footer_bg_${pageNumber}`,
    type: "shape",
    x: PAGE_MARGIN,
    y: A4_HEIGHT - PAGE_MARGIN - 28,
    width: A4_WIDTH - PAGE_MARGIN * 2,
    height: 24,
    shapeKind: "rect",
    stroke: profile.colors.border,
    strokeWidth: 0.5,
    fill: profile.colors.footerBackground,
    zIndex: 0,
    locked: true,
  });

  elements.push({
    id: `footer_text_${pageNumber}`,
    type: "text",
    content,
    x: PAGE_MARGIN + 8,
    y: A4_HEIGHT - PAGE_MARGIN - 24,
    width: A4_WIDTH - PAGE_MARGIN * 2 - 16,
    height: 20,
    fontSize: 9,
    fontWeight: "normal",
    textAlign: "center",
    color: profile.colors.text,
    lineHeight: 1.3,
    zIndex: 1,
    locked: true,
  });

  return elements;
}

export function getBrandedDocxFooterLines(
  profile: SchoolBrandingProfile,
  pageNumber: number,
  totalPages: number,
): string[] {
  const text = footerText(profile, pageNumber, totalPages);
  return text ? [text] : [];
}

export function getBrandedDocxHeaderLines(profile: SchoolBrandingProfile, topic: string): string[] {
  const lines = [profile.schoolName];
  if (profile.tagline?.trim()) lines.push(profile.tagline);
  if (profile.foundation?.trim()) lines.push(profile.foundation);
  const prefix = profile.classPrefix?.trim() ? `${profile.classPrefix} — ` : "";
  lines.push(`${prefix}Topic – ${topic}`);
  if (profile.principalName?.trim()) lines.push(`Principal: ${profile.principalName}`);
  return lines;
}
