import { A4_HEIGHT, A4_WIDTH, PAGE_MARGIN } from "./types.js";

/** Named layout constants — no magic numbers in renderers. */
export const LAYOUT = {
  PAGE_WIDTH: A4_WIDTH,
  PAGE_HEIGHT: A4_HEIGHT,
  PAGE_MARGIN,
  CONTENT_WIDTH: A4_WIDTH - PAGE_MARGIN * 2,
  FOOTER_RESERVED_HEIGHT: 52,
  FOOTER_BOX_HEIGHT: 24,
  BOTTOM_SAFE_ZONE: 48,
  ILLUSTRATION_SIZE: 56,
  PROMPT_PADDING: 8,
  OPTION_COL_GAP: 12,
  OPTION_ROW_GAP: 14,
  BLOCK_BOTTOM_PADDING: 14,
  MIN_BLOCK_GAP: 12,
  ANSWER_LINE_MAX_WIDTH: 200,
  ANSWER_LINE_WIDTH_RATIO: 0.45,
  CHAR_WIDTH_RATIO: 0.52,
  LINE_HEIGHT: 1.4,
  PAGE_BORDER_RADIUS: 12,
} as const;

export type LayoutConstants = typeof LAYOUT;
