/** Maps Amy Coach goal slugs to audio lesson ids (English, global). */
export const COACH_GOAL_TO_LESSON_IDS: Record<string, string[]> = {
  "manage-tantrums": ["toddler-tantrums-101", "early-school-emotional-regulation"],
  "handle-aggression": ["toddler-hitting-biting", "toddler-tantrums-101"],
  "reduce-defiance": ["toddler-no-phase", "early-school-emotional-regulation"],
  "emotional-regulation": ["early-school-emotional-regulation", "toddler-tantrums-101"],
  "separation-anxiety": ["infant-bonding-language", "early-school-friendship"],
  "balance-screen-time": ["toddler-screen-time", "tween-screen-balance"],
  "reduce-mobile-addiction": ["tween-screen-balance", "teen-social-media"],
  "improve-focus-span": ["early-school-homework", "health-digital-eyes-posture"],
  "reduce-shorts-overuse": ["tween-screen-balance", "toddler-screen-time"],
  "encourage-independent-eating": ["infant-feeding-cues", "toddler-picky-eating"],
  "navigate-fussy-eating": ["toddler-picky-eating", "health-hidden-nutrition-gaps"],
  "stop-junk-food-craving": ["health-childhood-obesity", "toddler-picky-eating"],
  "healthy-eating-routine": ["health-hidden-nutrition-gaps", "infant-feeding-cues"],
  "improve-mealtime-behavior": ["toddler-picky-eating", "health-childhood-obesity"],
  "improve-sleep-patterns": ["infant-sleep-foundations", "toddler-routines-transitions"],
  "fix-bedtime-resistance": ["infant-sleep-foundations", "toddler-routines-transitions"],
  "stop-night-waking": ["infant-sleep-foundations", "infant-safe-sleep-environment"],
  "consistent-sleep-routine": ["infant-sleep-foundations", "toddler-routines-transitions"],
  "reduce-late-sleeping": ["tween-screen-balance", "infant-sleep-foundations"],
  "boost-concentration": ["early-school-homework", "early-school-growth-mindset"],
  "build-study-discipline": ["early-school-homework", "tween-exam-stress"],
  "reduce-homework-resistance": ["early-school-homework", "early-school-growth-mindset"],
  "develop-growth-mindset": ["early-school-growth-mindset", "early-school-homework"],
  "toddler-tantrums": ["toddler-tantrums-101", "toddler-no-phase"],
  "hitting-biting": ["toddler-hitting-biting", "toddler-tantrums-101"],
  "no-phase": ["toddler-no-phase", "toddler-tantrums-101"],
  "manage-grandparents-interference": ["tween-talking-to-them", "teen-staying-connected"],
  "align-parenting-between-parents": ["teen-staying-connected", "tween-sibling-fights"],
  "handle-working-parent-guilt": ["teen-staying-connected", "infant-bonding-language"],
  "improve-own-sleep": ["infant-sleep-foundations", "teen-brain-101"],
  "manage-overwhelm": ["teen-mental-health-signs", "early-school-emotional-regulation"],
  "teen-social-media": ["teen-social-media", "tween-screen-balance"],
};

export const COACH_AUDIO_GOAL_STORAGE_KEY = "amynest_coach_audio_goal";
