import type { RuntimeRule } from "./types.js";

/**
 * Default declarative rule pack for Amy Learning Runtime.
 * Modules must not embed their own decision logic — extend this pack instead.
 */
export const DEFAULT_RUNTIME_RULES: RuntimeRule[] = [
  {
    id: "attention.suggest_break",
    priority: 100,
    cooldownMs: 60_000,
    featureFlag: "runtime.attention_break",
    when: {
      op: "or",
      any: [
        { op: "truthy", path: "state.suggestBreak" },
        {
          op: "in",
          path: "state.attentionClass",
          value: ["fatigued", "distracted"],
        },
        {
          op: "and",
          all: [
            { op: "eq", path: "signal.type", value: "attention.state_changed" },
            {
              op: "in",
              path: "signal.metadata.classification",
              value: ["fatigued", "distracted"],
            },
          ],
        },
      ],
    },
    then: {
      reason: "Attention signals fatigue — suggest a short break",
      breakSuggestion: true,
      difficulty: "easier",
      hints: "guided",
      narrationLength: "short",
      celebrationLevel: 0,
      rewardPriority: "low",
      nextActivity: {
        kind: "break",
        label: "Take a breath",
        href: "/nature",
      },
      confidence: 88,
      evidence: [
        { key: "attentionClass", value: "fatigued_or_distracted", source: "attention" },
      ],
    },
  },
  {
    id: "session.fail_streak_ease",
    priority: 90,
    cooldownMs: 15_000,
    when: { op: "gte", path: "state.failStreak", value: 2 },
    then: {
      reason: "Recent struggles — ease difficulty and add hints",
      difficulty: "easier",
      hints: "guided",
      narrationLength: "short",
      celebrationLevel: 1,
      rewardPriority: "normal",
      confidence: 82,
      evidence: [{ key: "failStreak", value: 2, source: "session" }],
    },
  },
  {
    id: "session.success_streak_celebrate",
    priority: 85,
    cooldownMs: 10_000,
    when: {
      op: "and",
      all: [
        { op: "gte", path: "state.successStreak", value: 3 },
        { op: "truthy", path: "flags.isSuccess" },
      ],
    },
    then: {
      reason: "Strong success streak — celebrate and keep challenge",
      celebrationLevel: 3,
      difficulty: "harder",
      hints: "none",
      narrationLength: "medium",
      rewardPriority: "high",
      confidence: 86,
      evidence: [{ key: "successStreak", value: 3, source: "session" }],
    },
  },
  {
    id: "learning.mastered_advance",
    priority: 80,
    when: { op: "eq", path: "signal.type", value: "learning.item_mastered" },
    then: {
      reason: "Item mastered — recommend a related next activity",
      celebrationLevel: 3,
      difficulty: "harder",
      hints: "none",
      rewardPriority: "high",
      narrationLength: "medium",
      nextActivity: {
        kind: "explore",
        entityId: null,
        label: "Try something related",
      },
      confidence: 90,
      evidence: [{ key: "event", value: "learning.item_mastered", source: "events" }],
    },
  },
  {
    id: "speech.completed_route",
    priority: 75,
    when: {
      op: "eq",
      path: "signal.type",
      value: "speech.practice_completed",
    },
    then: {
      reason: "Speech practice completed — tune feedback intensity",
      nextActivity: {
        kind: "speech_practice",
        href: "/speech-coach",
        label: "Keep practicing",
      },
      celebrationLevel: 2,
      narrationLength: "short",
      rewardPriority: "normal",
      confidence: 78,
      evidence: [{ key: "module", value: "speech_coach", source: "events" }],
    },
  },
  {
    id: "speech.low_score_hints",
    // Below speech.completed_route so dependsOn can see it fire first.
    priority: 74,
    dependsOn: ["speech.completed_route"],
    when: {
      op: "and",
      all: [
        { op: "eq", path: "signal.type", value: "speech.practice_completed" },
        { op: "lt", path: "signal.confidence", value: 70 },
      ],
    },
    then: {
      reason: "Speech score below target — guided hints and easier path",
      difficulty: "easier",
      hints: "guided",
      celebrationLevel: 1,
      rewardPriority: "normal",
      confidence: 84,
      evidence: [{ key: "speechScore", value: "below_70", source: "speech_coach" }],
    },
  },
  {
    id: "story.chapter_completed_route",
    priority: 75,
    when: {
      op: "eq",
      path: "signal.type",
      value: "story.chapter_completed",
    },
    then: {
      reason: "Story chapter completed — keep narrative flow and light celebration",
      nextActivity: {
        kind: "story",
        href: "/parenting-hub#tile-story-hub",
        label: "Next story chapter",
      },
      celebrationLevel: 2,
      narrationLength: "medium",
      difficulty: "same",
      hints: "light",
      rewardPriority: "normal",
      confidence: 78,
      evidence: [{ key: "module", value: "stories", source: "events" }],
    },
  },
  {
    id: "story.vocabulary_enrich",
    priority: 73,
    dependsOn: ["story.chapter_completed_route"],
    featureFlag: "runtime.kg_recommend",
    when: {
      op: "eq",
      path: "signal.type",
      value: "story.vocabulary_learned",
    },
    then: {
      reason: "New story vocabulary — recommend speech practice opportunity",
      recommendation: {
        id: "rec_story_speech",
        title: "Say a new story word",
        reason: "Story World discovered vocabulary worth speaking aloud",
        href: "/speech-coach",
        priority: "medium",
      },
      hints: "light",
      celebrationLevel: 2,
      narrationLength: "short",
      confidence: 76,
      evidence: [{ key: "storyVocabulary", value: true, source: "stories" }],
    },
  },
  {
    id: "story.session_wrap",
    priority: 72,
    when: {
      op: "eq",
      path: "signal.type",
      value: "story.session_completed",
    },
    then: {
      reason: "Story session complete — celebrate and suggest gentle next step",
      celebrationLevel: 3,
      narrationLength: "medium",
      rewardPriority: "high",
      difficulty: "same",
      nextActivity: {
        kind: "story",
        href: "/parenting-hub#tile-story-hub",
        label: "More stories",
      },
      confidence: 80,
      evidence: [{ key: "storySession", value: "completed", source: "stories" }],
    },
  },
  {
    id: "reading.page_completed_route",
    priority: 76,
    when: {
      op: "eq",
      path: "signal.type",
      value: "reading.page_completed",
    },
    then: {
      reason: "Reading page completed — continue phonics path with light hints",
      nextActivity: {
        kind: "reading",
        href: "/phonics",
        label: "Next reading page",
      },
      difficulty: "same",
      hints: "light",
      celebrationLevel: 2,
      narrationLength: "medium",
      rewardPriority: "normal",
      confidence: 80,
      evidence: [{ key: "module", value: "reading", source: "events" }],
    },
  },
  {
    id: "reading.word_enrich",
    priority: 74,
    dependsOn: ["reading.page_completed_route"],
    featureFlag: "runtime.kg_recommend",
    when: {
      op: "or",
      any: [
        { op: "eq", path: "signal.type", value: "reading.word_completed" },
        { op: "eq", path: "signal.type", value: "reading.new_word" },
      ],
    },
    then: {
      reason: "Reading vocabulary progress — recommend phoneme review",
      recommendation: {
        id: "rec_reading_phoneme",
        title: "Practice today's sound",
        reason: "Reading World introduced or completed vocabulary",
        href: "/phonics",
        priority: "medium",
      },
      hints: "light",
      celebrationLevel: 2,
      narrationLength: "short",
      confidence: 77,
      evidence: [{ key: "readingVocabulary", value: true, source: "reading" }],
    },
  },
  {
    id: "reading.phoneme_practice",
    priority: 75,
    when: {
      op: "eq",
      path: "signal.type",
      value: "reading.phoneme_practiced",
    },
    then: {
      reason: "Phoneme practiced in Reading World — reinforce with guided hints if needed",
      nextActivity: {
        kind: "reading",
        href: "/phonics",
        label: "Keep reading",
      },
      difficulty: "same",
      hints: "light",
      celebrationLevel: 1,
      narrationLength: "short",
      confidence: 79,
      evidence: [{ key: "phonemePractice", value: true, source: "reading" }],
    },
  },
  {
    id: "reading.session_wrap",
    priority: 73,
    when: {
      op: "eq",
      path: "signal.type",
      value: "reading.session_completed",
    },
    then: {
      reason: "Reading session complete — celebrate and suggest review",
      celebrationLevel: 3,
      narrationLength: "medium",
      rewardPriority: "high",
      difficulty: "same",
      nextActivity: {
        kind: "reading",
        href: "/phonics",
        label: "More reading",
      },
      confidence: 82,
      evidence: [{ key: "readingSession", value: "completed", source: "reading" }],
    },
  },
  {
    id: "game.level_completed_route",
    priority: 77,
    when: {
      op: "eq",
      path: "signal.type",
      value: "game.level_completed",
    },
    then: {
      reason: "Game level completed — celebrate and keep challenge balanced",
      nextActivity: {
        kind: "game",
        href: "/games",
        label: "Next game level",
      },
      difficulty: "same",
      hints: "none",
      celebrationLevel: 2,
      rewardPriority: "normal",
      confidence: 80,
      evidence: [{ key: "module", value: "games", source: "events" }],
    },
  },
  {
    id: "game.level_struggle",
    priority: 78,
    when: {
      op: "and",
      all: [
        { op: "eq", path: "signal.type", value: "game.level_completed" },
        { op: "lt", path: "signal.confidence", value: 55 },
      ],
    },
    then: {
      reason: "Game score below target — easier path and light hints",
      difficulty: "easier",
      hints: "light",
      celebrationLevel: 1,
      rewardPriority: "normal",
      nextActivity: {
        kind: "game",
        href: "/games",
        label: "Try again gently",
      },
      confidence: 84,
      evidence: [{ key: "gameScore", value: "below_55", source: "games" }],
    },
  },
  {
    id: "game.challenge_enrich",
    priority: 74,
    featureFlag: "runtime.kg_recommend",
    when: {
      op: "eq",
      path: "signal.type",
      value: "game.challenge_completed",
    },
    then: {
      reason: "Challenge completed — recommend related practice",
      recommendation: {
        id: "rec_game_next",
        title: "Another fun challenge",
        reason: "Keep skills warm with a related game",
        href: "/games",
        priority: "medium",
      },
      celebrationLevel: 2,
      rewardPriority: "high",
      hints: "none",
      confidence: 76,
      evidence: [{ key: "gameChallenge", value: true, source: "games" }],
    },
  },
  {
    id: "game.session_wrap",
    priority: 72,
    when: {
      op: "eq",
      path: "signal.type",
      value: "game.session_completed",
    },
    then: {
      reason: "Game session complete — celebrate and suggest next play",
      celebrationLevel: 3,
      rewardPriority: "high",
      difficulty: "same",
      nextActivity: {
        kind: "game",
        href: "/games",
        label: "Play again",
      },
      confidence: 82,
      evidence: [{ key: "gameSession", value: "completed", source: "games" }],
    },
  },
  {
    id: "knowledge.review_forgotten",
    priority: 70,
    featureFlag: "runtime.kg_review",
    when: {
      op: "or",
      any: [
        { op: "eq", path: "signal.type", value: "knowledge.updated" },
        { op: "eq", path: "signal.type", value: "learning.item_forgotten" },
        {
          op: "gt",
          path: "snapshots.knowledge.forgottenNodeIds.length",
          value: 0,
        },
      ],
    },
    then: {
      reason: "Forgotten or weak concepts queued for review",
      difficulty: "same",
      hints: "light",
      nextActivity: {
        kind: "review",
        label: "Quick review",
      },
      reviewQueue: [
        {
          priority: 80,
          reason: "Forgotten / weak concept refresh",
        },
      ],
      recommendation: {
        id: "rec_kg_review",
        title: "Quick concept review",
        reason: "Keep earlier learning fresh",
        priority: "high",
      },
      confidence: 74,
      evidence: [{ key: "knowledge", value: "forgotten_or_updated", source: "knowledge_graph" }],
    },
  },
  {
    id: "knowledge.follow_recommendation",
    priority: 65,
    featureFlag: "runtime.kg_recommend",
    when: {
      op: "gt",
      path: "snapshots.knowledge.topRecommendations.length",
      value: 0,
    },
    then: {
      reason: "Knowledge graph recommends a related concept",
      nextActivity: {
        kind: "discovery_play",
        label: "Explore related concept",
      },
      recommendation: {
        id: "rec_kg_top",
        title: "Related learning",
        reason: "Connected to what you just practiced",
        priority: "medium",
      },
      confidence: 72,
      evidence: [{ key: "kg_recs", value: true, source: "knowledge_graph" }],
    },
  },
  {
    id: "daily_mission.completed_reward",
    priority: 72,
    when: { op: "truthy", path: "flags.isDailyMission" },
    then: {
      reason: "Daily mission completed — high celebration + reward priority",
      celebrationLevel: 3,
      rewardPriority: "high",
      narrationLength: "medium",
      difficulty: "same",
      nextActivity: {
        kind: "daily_mission",
        label: "Mission complete",
      },
      confidence: 92,
      evidence: [{ key: "daily_mission", value: true, source: "daily_missions" }],
    },
  },
  {
    id: "skill.weak_practice",
    priority: 60,
    when: {
      op: "gt",
      path: "snapshots.skills.length",
      value: 0,
    },
    then: {
      reason: "Skill registry available — prefer weak-skill practice when idle",
      hints: "light",
      difficulty: "same",
      recommendation: {
        id: "rec_skill_weak",
        title: "Practice a weak skill",
        reason: "Skill registry shows room to grow",
        priority: "medium",
        href: "/study",
      },
      confidence: 60,
      evidence: [{ key: "skills", value: "present", source: "skill_registry" }],
    },
  },
  {
    id: "discovery.item_heard_continue",
    priority: 55,
    when: {
      op: "in",
      path: "signal.type",
      value: [
        "learning.item_seen",
        "learning.item_heard",
        "learning.item_recognized",
      ],
    },
    then: {
      reason: "Discovery progress — continue exploration with light coaching",
      nextActivity: {
        kind: "discovery_play",
        label: "Keep exploring",
      },
      difficulty: "same",
      hints: "light",
      celebrationLevel: 1,
      narrationLength: "short",
      rewardPriority: "normal",
      confidence: 70,
      evidence: [{ key: "discovery", value: true, source: "discovery_worlds" }],
    },
  },
  {
    id: "profile.younger_short_narration",
    priority: 40,
    when: {
      op: "or",
      any: [
        { op: "lte", path: "snapshots.child.ageMonths", value: 48 },
        { op: "lte", path: "snapshots.child.age", value: 4 },
      ],
    },
    then: {
      reason: "Younger child profile — keep narration short",
      narrationLength: "short",
      hints: "guided",
      confidence: 68,
      evidence: [{ key: "age", value: "younger", source: "child_profile" }],
    },
  },
  {
    id: "runtime.baseline_continue",
    priority: 10,
    when: { op: "truthy", path: "signal.eventId" },
    then: {
      reason: "Baseline — continue current learning path",
      difficulty: "same",
      hints: "none",
      celebrationLevel: 0,
      narrationLength: "medium",
      breakSuggestion: false,
      rewardPriority: "normal",
      nextActivity: {
        kind: "explore",
        label: "Continue",
      },
      confidence: 50,
      evidence: [{ key: "baseline", value: true, source: "runtime" }],
    },
  },
];

export const DEFAULT_FEATURE_FLAGS: Record<string, boolean> = {
  "runtime.attention_break": true,
  "runtime.kg_review": true,
  "runtime.kg_recommend": true,
};
