/**
 * Curated Golden Script seeds — every angle maps to a real AmyNest surface.
 * Sources verified via feature discovery + product docs (2026-07).
 */

import type { GoldenCategory, GoldenCharacter, GoldenEmotion } from "./types.js";

export interface GoldenSeed {
  category: GoldenCategory;
  slug: string;
  title: string;
  topic: string;
  targetAge: string;
  targetParent: string;
  objective: string;
  featureId: string;
  featureName: string;
  featureSource: string;
  problem: string;
  whyParentsFaceIt: string;
  emotionBeat: string;
  amynestSolution: string;
  featureDemo: string;
  expectedChildOutcome: string;
  parentBenefit: string;
  suggestedDuration: "15s" | "20s" | "30s";
  suggestedCharacters: GoldenCharacter[];
  suggestedCameraStyle: string;
  suggestedEmotion: GoldenEmotion;
  suggestedMusic: string;
  suggestedThumbnail: string;
  suggestedOpeningScene: string;
  suggestedEndingScene: string;
  hookSubjects: [string, string, string];
  /** Optional overrides — otherwise loaded from situations.ts */
  parentingSituation?: string;
  firstThreeSeconds?: string;
  hopeClose?: string;
}

export const GOLDEN_SEEDS: GoldenSeed[] = [
  // ─── Learning (5) ─────────────────────────────────────────────
  {
    category: "Learning",
    slug: "learning",
    title: "A Fresh Lesson Every Day — Without the Worksheet Panic",
    topic: "Daily adaptive practice in Study Zone",
    targetAge: "4–10",
    targetParent: "Parents who want structured learning without homework battles",
    objective: "Show how Study Zone delivers age-aware daily lessons so practice feels fresh, not forced",
    featureId: "learning-zone",
    featureName: "Study Zone (Learning Zone)",
    featureSource: "artifacts/kidschedule/src/pages/study.tsx",
    problem: "Parents buy workbooks, then watch them gather dust after day three.",
    whyParentsFaceIt: "Static pages don't adapt to the child's pace — too easy becomes boredom; too hard becomes tears.",
    emotionBeat: "Curiosity replaces dread when learning feels like today's adventure.",
    amynestSolution: "AmyNest Study Zone serves age-aware subjects, play categories, and daily fresh lessons with progress and XP.",
    featureDemo: "Open Study Zone → pick today's lesson → child practices → XP and progress update before they leave the screen.",
    expectedChildOutcome: "Your child returns tomorrow because the lesson feels new — and winnable.",
    parentBenefit: "You stop inventing curriculum at 9 PM and start celebrating small, visible wins.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Warm push-in from parent kitchen table into Study Zone UI, soft daylight",
    suggestedEmotion: "Curiosity",
    suggestedMusic: "Gentle learning piano with soft curiosity motif",
    suggestedThumbnail: "Amy Girl pointing at a glowing daily lesson card; parent smile in soft background",
    suggestedOpeningScene: "A blank workbook on the table; Amy AI appears with a soft purple glow and a new lesson card",
    suggestedEndingScene: "Study Zone progress ring fills; end card with AmyNest icon + store badges",
    hookSubjects: ["daily lessons", "Study Zone", "learning that sticks"],
  },
  {
    category: "Learning",
    slug: "learning",
    title: "Teach, Practice, Quiz, Doubt — One Tutor That Follows the Child",
    topic: "Amy AI Tutor modes for Math, English, GK, and Logic",
    targetAge: "6–12",
    targetParent: "Parents juggling homework help across subjects",
    objective: "Demonstrate Amy AI Tutor's Teach / Practice / Quiz / Doubt modes as a calm homework companion",
    featureId: "amy-ai-tutor",
    featureName: "Amy AI Tutor",
    featureSource: "artifacts/kidschedule/src/pages/amy-ai-tutor.tsx",
    problem: "Homework help turns into a power struggle — and parents become the exhausted default tutor.",
    whyParentsFaceIt: "Kids need different modes: explanation one minute, practice the next, a safe place for doubts always.",
    emotionBeat: "Confidence grows when a child can ask without fear of being judged.",
    amynestSolution: "Amy AI Tutor chats across Math, English, GK, and Logic with Teach, Practice, Quiz, and Doubt modes.",
    featureDemo: "Child opens Amy AI Tutor → chooses Doubt → asks a question → Amy explains gently → switches to Practice for two quick rounds.",
    expectedChildOutcome: "Your child learns to seek clarity instead of shutting down when stuck.",
    parentBenefit: "You stay the parent — Amy handles the patient, repeatable explanation loop.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Over-shoulder into chat tutor UI, then cut to proud child nod",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Encouraging mid-tempo learning bed",
    suggestedThumbnail: "Amy AI chat bubble: “Ask me your doubt”; Amy Boy with raised hand energy",
    suggestedOpeningScene: "Child stares at homework; Amy AI leans in: “Want Teach, Practice, Quiz, or Doubt?”",
    suggestedEndingScene: "Doubt answered; Practice streak ticks; branded end card",
    hookSubjects: ["homework help", "Amy AI Tutor", "asking doubts safely"],
  },
  {
    category: "Learning",
    slug: "learning",
    title: "Voice-Led Learning That Feels Like a Real Teacher",
    topic: "Amy Learning Tutor voice conversation",
    targetAge: "5–10",
    targetParent: "Parents whose children learn better by speaking than typing",
    objective: "Show voice-led teach → ask → encourage → correct loops with mic answers",
    featureId: "amy-learning-tutor",
    featureName: "Amy Learning Tutor",
    featureSource: "artifacts/kidschedule/src/pages/amy-learning-tutor.tsx",
    problem: "Screen learning often becomes silent tapping — no conversation, no thinking out loud.",
    whyParentsFaceIt: "Young learners build language and reasoning faster when they speak answers, not only select them.",
    emotionBeat: "Pride lands when a child hears themselves get it right.",
    amynestSolution: "Amy Learning Tutor leads a voice back-and-forth: explain, ask, encourage, and correct — with mic answers.",
    featureDemo: "Open Amy Learning Tutor → Amy explains → child answers on mic → Amy encourages and gently corrects → next prompt.",
    expectedChildOutcome: "Your child practices speaking their thinking — clearer, braver, more engaged.",
    parentBenefit: "You get a spoken learning session you can trust while dinner finishes.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Intimate close-up on mic button glow, then Amy's warm listening face",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Soft voice-friendly pad; leave headroom for narration",
    suggestedThumbnail: "Mic icon + Amy AI listening; Amy Girl mid-answer, eyes bright",
    suggestedOpeningScene: "Amy AI: “Say it out loud — I’m listening.” Mic pulse begins.",
    suggestedEndingScene: "Correct answer sparkle; end card Download AmyNest AI",
    hookSubjects: ["voice learning", "speaking answers", "Amy Learning Tutor"],
  },
  {
    category: "Learning",
    slug: "learning",
    title: "Letter Sounds That Stick — One Phonics Round at a Time",
    topic: "Phonics daily lesson, quiz, and CVC practice",
    targetAge: "3–7",
    targetParent: "Parents building early reading foundations at home",
    objective: "Highlight phonics daily lessons, letter/sound practice, and CVC blend rounds",
    featureId: "phonics-audio-preview",
    featureName: "Phonics Learning",
    featureSource: "artifacts/kidschedule/src/pages/phonics.tsx",
    problem: "Parents know phonics matters — but don't know what to practice tonight.",
    whyParentsFaceIt: "Early reading needs short, sequenced sound practice; random alphabet songs aren't enough.",
    emotionBeat: "Hope rises when a child blends three sounds into a real word.",
    amynestSolution: "AmyNest Phonics offers daily lessons, letter/sound practice, CVC blend rounds, and a clear digraph pathway.",
    featureDemo: "Open Phonics → today's lesson → sound practice → CVC blend round → quick quiz with audio support.",
    expectedChildOutcome: "Your child starts hearing words as sounds they can build — the first reading superpower.",
    parentBenefit: "You follow a pathway instead of guessing what “phonics practice” means.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Bright classroom-warm lighting; letter cards animate into a CVC word",
    suggestedEmotion: "Learning",
    suggestedMusic: "Playful letter-motif chimes, soft and clear",
    suggestedThumbnail: "C-A-T tiles merging into CAT; Amy Girl celebrating softly",
    suggestedOpeningScene: "Three floating letter sounds; Amy AI helps blend them into a word",
    suggestedEndingScene: "Quiz star earned; end card with store badges",
    hookSubjects: ["phonics at home", "letter sounds", "early reading"],
  },
  {
    category: "Learning",
    slug: "learning",
    title: "AI Worksheets Matched to Class, Subject, and Difficulty",
    topic: "Worksheet Studio for English, Hindi, and bilingual practice",
    targetAge: "6–12",
    targetParent: "Parents who need print-ready practice without hunting PDFs",
    objective: "Show Worksheet Studio generating class/subject/difficulty worksheets with drafts and templates",
    featureId: "worksheet-studio",
    featureName: "Worksheet Studio",
    featureSource: "artifacts/kidschedule/src/features/worksheet-studio",
    problem: "Finding the right worksheet takes longer than the practice itself.",
    whyParentsFaceIt: "Random internet worksheets rarely match class level, language, or tonight's goal.",
    emotionBeat: "Calm returns when the right practice appears in minutes — not after a search spiral.",
    amynestSolution: "Worksheet Studio creates AI worksheets by class, subject, and difficulty — English, Hindi, or bilingual — with drafts and templates.",
    featureDemo: "Open Worksheet Studio → choose class + subject + difficulty → generate → preview draft → save or print for tonight.",
    expectedChildOutcome: "Your child practices at the right level — challenged, not crushed.",
    parentBenefit: "You get useful worksheets without becoming a late-night Google machine.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Top-down worksheet reveal with purple accent paper transition",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Organized, upbeat productivity bed (soft)",
    suggestedThumbnail: "Fresh worksheet + Amy AI stamp; bilingual English/Hindi hint",
    suggestedOpeningScene: "Parents scrolling endless PDFs; Amy AI replaces chaos with one clear worksheet card",
    suggestedEndingScene: "Printed sheet on table; child starts; end card",
    hookSubjects: ["worksheets", "class-matched practice", "Worksheet Studio"],
  },

  // ─── Speech (5) ───────────────────────────────────────────────
  {
    category: "Speech",
    slug: "speech",
    title: "Hear It. Say It. Get Gentle Feedback.",
    topic: "Speech Practice with pronunciation feedback",
    targetAge: "2–8",
    targetParent: "Parents supporting clearer speech at home",
    objective: "Show Speech Practice: prompt → mic → pronunciation feedback → session memory",
    featureId: "speech-practice",
    featureName: "Speech Practice",
    featureSource: "artifacts/kidschedule/src/pages/speech-coach/index.tsx",
    problem: "Parents hear unclear sounds — and don't know how to coach without pressure.",
    whyParentsFaceIt: "Correcting every word can shut a child down; silence doesn't help either.",
    emotionBeat: "Emotional growth happens when practice feels safe and playful.",
    amynestSolution: "AmyNest Speech Practice lets your child hear a prompt, speak into the mic, and receive pronunciation feedback with session memory.",
    featureDemo: "Open Speech Practice → child hears prompt → speaks → feedback appears → session progress is remembered for next time.",
    expectedChildOutcome: "Your child practices sounds with warmth — not embarrassment.",
    parentBenefit: "You get a structured speech session instead of anxious guessing.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Soft close-up on mouth-safe framing + mic UI; never clinical",
    suggestedEmotion: "Emotional Growth",
    suggestedMusic: "Warm encouraging pad, slow pulse",
    suggestedThumbnail: "Amy Girl at mic; soft waveform; Amy AI coaching smile",
    suggestedOpeningScene: "Amy AI: “Listen first… now your turn.” Mic glows.",
    suggestedEndingScene: "Gentle feedback star; end card Download AmyNest AI",
    hookSubjects: ["speech practice", "pronunciation", "speaking with confidence"],
  },
  {
    category: "Speech",
    slug: "speech",
    title: "Speech Games That Make Practice Feel Like Play",
    topic: "Speech Coach game-style drills with rewards",
    targetAge: "3–8",
    targetParent: "Parents whose child resists “sit and practice”",
    objective: "Highlight short speech games with rewards alongside practice sessions",
    featureId: "speech-coach-v2",
    featureName: "Speech Games",
    featureSource: "artifacts/kidschedule/src/pages/speech-coach/speech-game-flow.tsx",
    problem: "The moment practice feels like a drill, kids leave the room.",
    whyParentsFaceIt: "Motivation for young speakers comes from play loops — not lectures.",
    emotionBeat: "Achievement sparkles when a reward follows a brave try.",
    amynestSolution: "AmyNest Speech includes short game-style drills with rewards, so practice rides on play energy.",
    featureDemo: "Open a speech game → child completes a short drill → earns a reward → returns to practice with momentum.",
    expectedChildOutcome: "Your child asks to “play speech” again tomorrow.",
    parentBenefit: "You get consistency without bribes or battles.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Playful parallax; reward sticker pop; keep faces soft",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Light playful claps + soft melody",
    suggestedThumbnail: "Speech game reward burst; Amy Boy cheering",
    suggestedOpeningScene: "Amy AI flips a practice card into a mini game board",
    suggestedEndingScene: "Sticker earned; end card",
    hookSubjects: ["speech games", "practice that feels like play", "rewards for speaking"],
  },
  {
    category: "Speech",
    slug: "speech",
    title: "Know Where Your Child’s Speech Is — Without Panic",
    topic: "Age-band speech milestone checker",
    targetAge: "Infant–4+",
    targetParent: "Parents wondering if speech is “on track”",
    objective: "Show milestone checker for age-band speech markers as on track / needs attention",
    featureId: "speech-practice",
    featureName: "Speech Milestone Checker",
    featureSource: "lib/speech-coach/src/content.ts",
    problem: "Parents compare their child to cousins, reels, and worst-case stories — and spiral.",
    whyParentsFaceIt: "Without a calm age-band map, every delayed sound feels like an emergency.",
    emotionBeat: "Hope returns when you can see the next milestone clearly.",
    amynestSolution: "AmyNest’s speech milestone checker lets parents mark age-band milestones as on track or needs attention — calmly, privately.",
    featureDemo: "Open Speech → Milestone checker → select age band → mark milestones → see a clear parent-friendly snapshot.",
    expectedChildOutcome: "Your child gets support matched to real needs — not random pressure.",
    parentBenefit: "You replace late-night worry with a clearer next step.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Quiet, reassuring framing; soft lavender grade; no clinical white",
    suggestedEmotion: "Hope",
    suggestedMusic: "Breathing-tempo ambient warmth",
    suggestedThumbnail: "Milestone checklist with gentle green “on track”; Amy AI beside parent",
    suggestedOpeningScene: "Parent scrolling anxiety; Amy AI places a calm milestone card in frame",
    suggestedEndingScene: "Clear next practice suggestion; end card",
    hookSubjects: ["speech milestones", "is my child on track", "calm speech guidance"],
  },
  {
    category: "Speech",
    slug: "speech",
    title: "A Parent View Built for Caregivers — Not Just Kids",
    topic: "Speech parent view, guidance cards, and progress notes",
    targetAge: "2–8",
    targetParent: "Caregivers who want tips they can use after the session",
    objective: "Show parent vs child view toggle with guidance cards and progress notes",
    featureId: "speech-practice",
    featureName: "Speech Parent Guidance",
    featureSource: "lib/speech-coach/src/i18n-manifest.ts",
    problem: "Apps entertain kids — then leave parents without a takeaway.",
    whyParentsFaceIt: "Speech growth needs caregiver follow-through between sessions.",
    emotionBeat: "Confidence grows when parents know what to reinforce tonight.",
    amynestSolution: "Speech Coach includes a parent view with guidance cards and progress notes — switch from child play to caregiver clarity.",
    featureDemo: "Finish a child session → toggle Parent view → read guidance card → note one home practice tip.",
    expectedChildOutcome: "Practice continues at home in tiny, kind moments.",
    parentBenefit: "You leave with one clear action — not a fog of metrics.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Split frame: child view → parent guidance card reveal",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Warm professional bed",
    suggestedThumbnail: "Toggle: Child / Parent; guidance card glowing",
    suggestedOpeningScene: "Amy AI flips the screen from playful child UI to calm parent guidance",
    suggestedEndingScene: "One tip saved; end card",
    hookSubjects: ["parent speech tips", "guidance after practice", "parent view"],
  },
  {
    category: "Speech",
    slug: "speech",
    title: "Realtime Coaching — Minutes, Words, Confidence, Streak",
    topic: "Speech Coach V2 live coaching and parent dashboard",
    targetAge: "3–10",
    targetParent: "Parents who want visible speech progress over time",
    objective: "Highlight live coaching plus parent dashboard: minutes, words, confidence, streak",
    featureId: "speech-coach-v2",
    featureName: "Speech Coach V2",
    featureSource: "artifacts/kidschedule/src/features/speech-coach-v2",
    problem: "Parents practice for weeks — and still can't tell if anything improved.",
    whyParentsFaceIt: "Without a simple progress story, motivation fades for both parent and child.",
    emotionBeat: "Achievement feels real when streak and confidence rise together.",
    amynestSolution: "Speech Coach V2 offers live realtime coaching for pronunciation and fluency, with a parent dashboard for minutes, words, confidence, and streak.",
    featureDemo: "Start a live coaching session → child practices → dashboard updates minutes, words, confidence, and streak.",
    expectedChildOutcome: "Your child sees progress as a streak they want to protect.",
    parentBenefit: "You finally have a clear speech progress story — not guesswork.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "UI dashboard glide across four metrics; soft purple accents",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Uplifting resolve into end card",
    suggestedThumbnail: "Parent dashboard tiles: Minutes · Words · Confidence · Streak",
    suggestedOpeningScene: "Amy AI opens the parent dashboard like a proud report card — warm, never harsh",
    suggestedEndingScene: "Streak +1; end card",
    hookSubjects: ["speech progress", "confidence streak", "Speech Coach"],
  },

  // ─── Health (5) ───────────────────────────────────────────────
  {
    category: "Health",
    slug: "health",
    title: "Not a Workout App — A Secret Lab in the Sky",
    topic: "Amy Health Lab motion wellness world",
    targetAge: "3–12",
    targetParent: "Parents who want movement without “exercise” battles",
    objective: "Introduce Amy Health Lab as a wonder-led motion wellness zone",
    featureId: "health-lab",
    featureName: "Amy Health Lab™",
    featureSource: "artifacts/kidschedule/src/features/health-lab",
    problem: "“Go exercise” rarely works — kids want adventure, not instructions.",
    whyParentsFaceIt: "Movement sticks when it feels like saving a world, not completing a checklist.",
    emotionBeat: "Curiosity opens the body when the story feels magical and safe.",
    amynestSolution: "Amy Health Lab™ is a motion-based wellness zone — a secret science lab in the sky where kids become Amy’s Field Partner.",
    featureDemo: "Open Health Lab → enter today's land → child uses motion powers (balance, freeze, breath, reaction) to help the world.",
    expectedChildOutcome: "Your child remembers a place they loved — and moves with pride.",
    parentBenefit: "You get real movement practice wrapped in wonder, not nagging.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Pixar-inspired wonder; soft cosmic lab docking with floating land",
    suggestedEmotion: "Curiosity",
    suggestedMusic: "Soft magical adventure arpeggios — never scary",
    suggestedThumbnail: "Amy Health Lab observatory above clouds; Amy Girl as Field Partner",
    suggestedOpeningScene: "Sky lab door opens; Amy AI: “Today’s land needs your powers.”",
    suggestedEndingScene: "Land saved sparkle; end card",
    hookSubjects: ["kids movement", "Health Lab", "play that builds wellness"],
  },
  {
    category: "Health",
    slug: "health",
    title: "Balance Games That Build Stillness Superpowers",
    topic: "Flamingo balance and freeze-statue challenges",
    targetAge: "4–10",
    targetParent: "Parents helping restless kids find body control",
    objective: "Show balance and freeze games as fun steadiness challenges",
    featureId: "health-lab",
    featureName: "Health Lab Balance & Freeze Games",
    featureSource: "artifacts/kidschedule/src/features/health-lab/components/games",
    problem: "Restlessness gets labeled as “bad behavior” when kids actually need body practice.",
    whyParentsFaceIt: "Balance and stillness are skills — they improve with playful reps.",
    emotionBeat: "Achievement lands when a child holds still and grins.",
    amynestSolution: "Health Lab includes flamingo balance, freeze-statue, and steadiness challenges powered by motion play.",
    featureDemo: "Open Health Lab games → Flamingo Balance or Freeze Statue → child holds pose → gentle success feedback.",
    expectedChildOutcome: "Your child discovers they can control energy — and feels proud of it.",
    parentBenefit: "You gain a tool for regulation that doesn't feel like punishment.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Full-body kid frame; freeze-frame sparkle on success",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Light playful hold — then soft reward chime",
    suggestedThumbnail: "Child in flamingo pose; Amy AI counting softly",
    suggestedOpeningScene: "Amy AI: “Freeze magic — ready?” Child freezes; world glows.",
    suggestedEndingScene: "Balance badge; end card",
    hookSubjects: ["balance for kids", "freeze game", "body control"],
  },
  {
    category: "Health",
    slug: "health",
    title: "Breath Play That Helps Kids Find Calm",
    topic: "Breath-control and calmness-meter games",
    targetAge: "4–10",
    targetParent: "Parents navigating big feelings after school",
    objective: "Demonstrate breath and calmness games as gentle regulation practice",
    featureId: "health-lab",
    featureName: "Health Lab Breath & Calm",
    featureSource: "artifacts/kidschedule/src/features/health-lab/components/games",
    problem: "When emotions spike, “calm down” is the least calming phrase in parenting.",
    whyParentsFaceIt: "Kids need a practice for breath before they need a lecture about feelings.",
    emotionBeat: "Emotional growth starts with one slower breath they can feel.",
    amynestSolution: "Health Lab includes breath-control play and a calmness meter — challenge without fear.",
    featureDemo: "Open a breath/calm game → child follows breath cues → calmness meter rises → soft success moment.",
    expectedChildOutcome: "Your child has a body tool they can use when feelings get big.",
    parentBenefit: "You co-regulate with a shared game instead of a standoff.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Soft slow push-in; cool-to-warm color shift as calm rises",
    suggestedEmotion: "Emotional Growth",
    suggestedMusic: "Breathing-tempo ambient; sparse and kind",
    suggestedThumbnail: "Calmness meter rising; Amy Girl breathing with Amy AI",
    suggestedOpeningScene: "After-school storm energy; Amy AI invites a breath mission",
    suggestedEndingScene: "Meter full; soft hug energy; end card",
    hookSubjects: ["calm down tools", "breathing for kids", "big feelings"],
  },
  {
    category: "Health",
    slug: "health",
    title: "Reaction Games That Train Focus Through Play",
    topic: "Reaction-time and fine-motor motion challenges",
    targetAge: "5–12",
    targetParent: "Parents building focus and coordination",
    objective: "Show reaction-time and finger-stability challenges with motion calibration",
    featureId: "health-lab",
    featureName: "Health Lab Reaction & Fine Motor",
    featureSource: "artifacts/kidschedule/src/features/health-lab/hooks/use-motion-sensor.ts",
    problem: "Focus lectures don't build focus muscles — play does.",
    whyParentsFaceIt: "Attention and fine motor skills improve with short, joyful challenges — not longer screen scolding.",
    emotionBeat: "Curiosity fuels the next try when the challenge feels fair.",
    amynestSolution: "Health Lab offers reaction-time and finger-stability challenges with motion calibration — short missions, clear feedback.",
    featureDemo: "Calibrate motion → start reaction or stability challenge → child responds → score/feedback → try again proudly.",
    expectedChildOutcome: "Your child sharpens response and control while having fun.",
    parentBenefit: "You replace “pay attention” with a game that trains it.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Quick cuts synced to reaction pops; keep warm not frantic",
    suggestedEmotion: "Curiosity",
    suggestedMusic: "Light adventure tick; no harsh EDM",
    suggestedThumbnail: "Reaction flash + Amy Boy ready stance",
    suggestedOpeningScene: "Amy AI: “Ready… set…” — reaction cue fires",
    suggestedEndingScene: "Personal best spark; end card",
    hookSubjects: ["focus games", "reaction time", "fine motor play"],
  },
  {
    category: "Health",
    slug: "health",
    title: "Nutrition That Fits Real Family Life",
    topic: "Nutrition Hub: Today, Plan, Track, Learn, Family",
    targetAge: "2–12",
    targetParent: "Parents building healthier meals without perfection pressure",
    objective: "Walk through Nutrition Hub tabs — meal plans, checklist score, streaks, learn cards",
    featureId: "nutrition",
    featureName: "Nutrition Hub",
    featureSource: "artifacts/kidschedule/src/features/nutrition",
    problem: "Meal guilt is loud — and meal plans rarely survive a real weekday.",
    whyParentsFaceIt: "Families need a simple today plan, a trackable checklist, and learning — not a perfect plate every time.",
    emotionBeat: "Hope grows when small nutrition wins streak into a habit.",
    amynestSolution: "AmyNest Nutrition Hub brings Today / Plan / Track / Learn / Family — meal plans, daily checklist score, streaks, and nutrient learn cards.",
    featureDemo: "Open Nutrition → Today checklist → Track a meal → open a Learn card → see streak grow.",
    expectedChildOutcome: "Kids join food learning as curiosity — not force.",
    parentBenefit: "You get a calmer meal system that respects busy evenings.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Fresh morning kitchen light; UI tabs swipe elegantly",
    suggestedEmotion: "Hope",
    suggestedMusic: "Fresh acoustic warmth",
    suggestedThumbnail: "Nutrition Today checklist + streak; colorful tiffin hint",
    suggestedOpeningScene: "Empty fridge anxiety softens as Amy AI opens Nutrition Today",
    suggestedEndingScene: "Checklist score up; end card",
    hookSubjects: ["kids nutrition", "meal planning", "family food habits"],
  },

  // ─── Games (5) ────────────────────────────────────────────────
  {
    category: "Games",
    slug: "games",
    title: "Brain Games With a Daily Limit That Protects Play",
    topic: "Games hub catalog with free daily limits",
    targetAge: "3–10",
    targetParent: "Parents who want play with boundaries",
    objective: "Show Games hub brain/memory/math/focus games with free daily limit structure",
    featureId: "games",
    featureName: "Games Hub",
    featureSource: "artifacts/kidschedule/src/pages/games.tsx",
    problem: "Open-ended game apps swallow the afternoon.",
    whyParentsFaceIt: "Kids need playful brain practice — parents need healthy limits built in.",
    emotionBeat: "Family bonding improves when play ends cleanly, not with a fight.",
    amynestSolution: "AmyNest Games Hub offers brain, memory, math, focus, creativity, and behavior games — with a free daily play limit and premium expansion.",
    featureDemo: "Open Games → pick a free starter → play a short round → see daily plays remaining → celebrate and close.",
    expectedChildOutcome: "Your child gets focused play — and learns that good games can end.",
    parentBenefit: "You set a boundary without becoming the villain.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Bright playful UI montage; end on daily limit counter kindly",
    suggestedEmotion: "Family Bonding",
    suggestedMusic: "Happy light play bed",
    suggestedThumbnail: "Games Hub tiles + “plays left today” badge",
    suggestedOpeningScene: "Amy AI opens the Games Hub like a toy shelf with purpose",
    suggestedEndingScene: "Play complete; limit respected; end card",
    hookSubjects: ["kids brain games", "healthy screen play", "daily game limit"],
  },
  {
    category: "Games",
    slug: "games",
    title: "Abacus PRO — From Beads to Mental Math",
    topic: "Abacus learn, practice, challenge, mental, tutor modes",
    targetAge: "2–10",
    targetParent: "Parents building number sense early",
    objective: "Showcase Abacus PRO Zone modes for ages ~2–10",
    featureId: "abacus",
    featureName: "Abacus PRO Zone",
    featureSource: "artifacts/kidschedule/src/pages/abacus.tsx",
    problem: "Number apps jump to drills before kids feel numbers in their hands.",
    whyParentsFaceIt: "Strong math foundations grow from concrete bead sense into mental fluency.",
    emotionBeat: "Learning pride when beads become numbers in the mind.",
    amynestSolution: "Abacus PRO Zone includes Learn, Practice, Challenge, Mental, and Tutor soroban modes for young learners.",
    featureDemo: "Open Abacus → Learn with beads → Practice → try Mental mode → Amy Tutor supports a tricky round.",
    expectedChildOutcome: "Your child builds number sense they can feel — then think.",
    parentBenefit: "You get a clear abacus pathway instead of random math apps.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Macro bead motion → pull back to proud child face",
    suggestedEmotion: "Learning",
    suggestedMusic: "Crisp curious xylophone motif",
    suggestedThumbnail: "Glowing abacus beads; Amy Girl counting",
    suggestedOpeningScene: "Beads slide; Amy AI: “Feel the number first.”",
    suggestedEndingScene: "Mental mode success; end card",
    hookSubjects: ["abacus for kids", "mental math", "number sense"],
  },
  {
    category: "Games",
    slug: "games",
    title: "Animal World — Learning That Sounds Alive",
    topic: "Animal World sound learning experience",
    targetAge: "2–7",
    targetParent: "Parents seeking gentle discovery play",
    objective: "Introduce Animal World as a hub-gated animal sound/learning world",
    featureId: "animal-world",
    featureName: "Animal World",
    featureSource: "artifacts/kidschedule/src/pages/animal-world.tsx",
    problem: "Flashcard animals get ignored; kids want living worlds.",
    whyParentsFaceIt: "Early learning sticks when sound, story, and wonder travel together.",
    emotionBeat: "Curiosity blooms when a child hears an animal and names it with joy.",
    amynestSolution: "Animal World is a Discovery-gated animal sound and learning experience — playful, warm, and memorable.",
    featureDemo: "Enter Animal World → explore an animal → hear its sound → learn a simple fact → collect the moment.",
    expectedChildOutcome: "Your child connects sound and meaning through play.",
    parentBenefit: "You get discovery time that feels premium — not noisy chaos.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Storybook animal reveal; soft nature light",
    suggestedEmotion: "Curiosity",
    suggestedMusic: "Light nature-curious bed; soft animal cue",
    suggestedThumbnail: "Friendly animal + sound waves; Amy Girl listening",
    suggestedOpeningScene: "World gate opens; a soft animal call draws the child in",
    suggestedEndingScene: "Animal learned; end card",
    hookSubjects: ["animal sounds", "discovery learning", "Animal World"],
  },
  {
    category: "Games",
    slug: "games",
    title: "Discovery Worlds — A Map of Adventures Kids Want to Finish",
    topic: "Discovery Worlds hub: map, daily adventure, parent insights",
    targetAge: "3–9",
    targetParent: "Parents who want learning worlds with a progress story",
    objective: "Show Discovery Worlds hub with learning map, daily adventure, and parent insights",
    featureId: "discovery-worlds-hub",
    featureName: "Discovery Worlds Hub",
    featureSource: "artifacts/kidschedule/src/pages/discovery-worlds-hub.tsx",
    problem: "Content dumps overwhelm kids — then nothing gets finished.",
    whyParentsFaceIt: "Children persist when progress is visible on a map they love.",
    emotionBeat: "Achievement grows across a journey, not a single session.",
    amynestSolution: "Discovery Worlds Hub brings sound learning worlds, a learning map, daily adventure, and parent insights across worlds.",
    featureDemo: "Open Discovery Worlds → see the learning map → start today's adventure → parent insights update after play.",
    expectedChildOutcome: "Your child chases mastery across worlds — proudly.",
    parentBenefit: "You see what was practiced without interrupting the magic.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Map orbit then dive into today's world portal",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Adventure wonder theme — gentle",
    suggestedThumbnail: "Learning map with glowing daily adventure pin",
    suggestedOpeningScene: "Amy AI points to today's pin on the Discovery map",
    suggestedEndingScene: "Adventure complete; parent insight chip; end card",
    hookSubjects: ["discovery worlds", "daily adventure", "learning map"],
  },
  {
    category: "Games",
    slug: "games",
    title: "Stickers and Mastery That Make Progress Feel Collectible",
    topic: "Streaks, sticker album, and mastery map",
    targetAge: "3–9",
    targetParent: "Parents who want motivation without junk rewards",
    objective: "Highlight sticker album and mastery map (≥80% heard) as meaningful progress",
    featureId: "discovery-worlds-hub",
    featureName: "Discovery Worlds Stickers & Mastery",
    featureSource: "docs/discovery-worlds-premiumization-sprint.md",
    problem: "Random points feel empty — kids forget why they earned them.",
    whyParentsFaceIt: "Collectible mastery turns practice into identity: “I earned this.”",
    emotionBeat: "Pride sticks when a sticker represents real listening and learning.",
    amynestSolution: "Discovery Worlds tracks streaks, a sticker album, and a mastery map for sounds heard at a high level — progress kids can collect.",
    featureDemo: "Finish an adventure → earn a sticker → open sticker album → see mastery map progress.",
    expectedChildOutcome: "Your child wants to return to complete what they started.",
    parentBenefit: "Motivation becomes intrinsic collectible pride — not candy bribes.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Sticker peel animation into album; mastery map fill",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Soft celebration swell",
    suggestedThumbnail: "Sticker album page + mastery ring",
    suggestedOpeningScene: "Empty sticker slot sparkles; Amy AI: “You earned this.”",
    suggestedEndingScene: "Album page fills; end card",
    hookSubjects: ["collectible stickers", "mastery progress", "learning streaks"],
  },
];

export const GOLDEN_SEEDS_PART2: GoldenSeed[] = [
  // ─── Astro (5) ────────────────────────────────────────────────
  {
    category: "Astro",
    slug: "astro",
    title: "A Cosmic Portrait — Not a Prediction",
    topic: "Birth Sky reflective parenting insights",
    targetAge: "All ages (parent-facing)",
    targetParent: "Parents curious about reflective, non-fear astrology",
    objective: "Position Birth Sky as reflective parenting insight — never fortune-telling fear",
    featureId: "birth-sky",
    featureName: "Amy Astro Intelligence (Birth Sky)",
    featureSource: "artifacts/kidschedule/src/features/birth-sky",
    problem: "Astrology content online often scares parents with fate language.",
    whyParentsFaceIt: "Parents want meaning and reflection — not fear dressed as destiny.",
    emotionBeat: "Hope softens when the sky becomes a mirror for parenting, not a verdict.",
    amynestSolution: "Amy Astro Intelligence creates a Birth Sky cosmic portrait from birth details — reflective parenting insights, not prediction.",
    featureDemo: "Enter birth details → reveal Birth Sky snapshot → read reflective insights Amy frames for parenting understanding.",
    expectedChildOutcome: "Your child is seen with warmth — not labeled by fear.",
    parentBenefit: "You get a calm reflective lens — never a scare forecast.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Soft cosmic twilight; gentle purple nebula; intimate parent framing",
    suggestedEmotion: "Hope",
    suggestedMusic: "Soft cosmic arpeggios — wonder without tension",
    suggestedThumbnail: "Birth Sky portrait glow; Amy AI with calm constellation",
    suggestedOpeningScene: "Stars settle into a child’s sky portrait; Amy AI: “This is reflection — not fate.”",
    suggestedEndingScene: "Insight card; end card",
    hookSubjects: ["birth chart for parents", "reflective astrology", "Birth Sky"],
  },
  {
    category: "Astro",
    slug: "astro",
    title: "Explore the Sky After the Snapshot",
    topic: "Sky map and astronomy segments in Birth Sky",
    targetAge: "All ages (family exploration)",
    targetParent: "Parents who want science-wonder alongside meaning",
    objective: "Show sky map / astronomy exploration after snapshot reveal",
    featureId: "birth-sky",
    featureName: "Birth Sky Astronomy Segments",
    featureSource: "artifacts/kidschedule/src/features/birth-sky/pages/dashboard",
    problem: "Astrology apps skip the wonder of the actual sky.",
    whyParentsFaceIt: "Kids light up when meaning meets real astronomy curiosity.",
    emotionBeat: "Curiosity expands when a family looks up together.",
    amynestSolution: "After the Birth Sky snapshot, families can explore sky map and astronomy segments — wonder grounded in the sky.",
    featureDemo: "Open Birth Sky dashboard → explore sky/astronomy segment → point out bodies with Amy’s guidance.",
    expectedChildOutcome: "Your child connects “my sky” with real celestial wonder.",
    parentBenefit: "You get a shared learning moment — beautiful and grounding.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Orbit camera across soft sky map; keep readable",
    suggestedEmotion: "Curiosity",
    suggestedMusic: "Quiet space-wonder bed",
    suggestedThumbnail: "Sky map with child’s highlight; Amy Boy pointing up",
    suggestedOpeningScene: "Snapshot fades into an explorable sky map",
    suggestedEndingScene: "Family looking up; end card",
    hookSubjects: ["sky map for kids", "astronomy with Amy", "Birth Sky explore"],
  },
  {
    category: "Astro",
    slug: "astro",
    title: "Tradition — Only With Consent and Care",
    topic: "Optional tradition layer with intro consent",
    targetAge: "All ages (parent choice)",
    targetParent: "Families who value cultural tradition without pressure",
    objective: "Show optional tradition segment requiring intro consent",
    featureId: "birth-sky",
    featureName: "Birth Sky Tradition Segment",
    featureSource: "artifacts/kidschedule/src/features/birth-sky/pages/dashboard",
    problem: "Cultural layers can feel forced — or completely missing.",
    whyParentsFaceIt: "Families deserve choice: tradition as invitation, never imposition.",
    emotionBeat: "Family bonding deepens when culture is chosen with respect.",
    amynestSolution: "Birth Sky offers an optional tradition segment with an intro consent step — your family’s choice.",
    featureDemo: "Open Tradition → read consent intro → opt in → explore tradition layer calmly.",
    expectedChildOutcome: "Your child meets culture as belonging — not obligation.",
    parentBenefit: "You control what enters your family’s story.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Warm cultural soft-light; consent UI clear and respectful",
    suggestedEmotion: "Family Bonding",
    suggestedMusic: "Soft traditional-inspired acoustic (tasteful, modern)",
    suggestedThumbnail: "Consent card + gentle tradition motif; Amy AI respectful pose",
    suggestedOpeningScene: "Amy AI: “Tradition is optional — you choose.” Consent card appears.",
    suggestedEndingScene: "Tradition layer opens softly; end card",
    hookSubjects: ["family tradition", "consent in apps", "cultural astrology"],
  },
  {
    category: "Astro",
    slug: "astro",
    title: "Reflect — Turn Insight Into Parenting Clarity",
    topic: "Birth Sky reflect journal prompts",
    targetAge: "All ages (parent journaling)",
    targetParent: "Parents who process through writing",
    objective: "Highlight reflect journal prompts tied to the Birth Sky portrait",
    featureId: "birth-sky",
    featureName: "Birth Sky Reflect Journal",
    featureSource: "artifacts/kidschedule/src/features/birth-sky/pages/dashboard/reflect-segment.tsx",
    problem: "Insights fade if they never become a personal note.",
    whyParentsFaceIt: "Reflection turns beautiful words into parenting intention.",
    emotionBeat: "Emotional growth for parents begins with one honest sentence.",
    amynestSolution: "Birth Sky includes reflect journal prompts tied to the child’s cosmic portrait.",
    featureDemo: "Open Reflect → read a prompt → write a short parent reflection → save the moment.",
    expectedChildOutcome: "Your child is parented with more intention tomorrow.",
    parentBenefit: "You convert insight into a calm personal practice.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Quiet journaling close-up; soft lamp light; purple ink accent",
    suggestedEmotion: "Emotional Growth",
    suggestedMusic: "Sparse piano reflection",
    suggestedThumbnail: "Journal prompt card; pen; Amy AI gentle presence",
    suggestedOpeningScene: "Amy AI places a reflect prompt beside the sky portrait",
    suggestedEndingScene: "Saved reflection glow; end card",
    hookSubjects: ["parenting journal", "reflect prompts", "Birth Sky reflect"],
  },
  {
    category: "Astro",
    slug: "astro",
    title: "Ask Amy Astro About Your Child’s Sky",
    topic: "AI conversation sheet for Birth Sky questions",
    targetAge: "All ages (parent Q&A)",
    targetParent: "Parents with follow-up questions after the snapshot",
    objective: "Show Ask Amy Astro conversation on the sky snapshot (premium-aware)",
    featureId: "birth-sky",
    featureName: "Amy Astro Conversation",
    featureSource: "artifacts/kidschedule/src/features/birth-sky/pages/dashboard/conversation-sheet.tsx",
    problem: "A beautiful snapshot still leaves parents with “but what does this mean for bedtime?”",
    whyParentsFaceIt: "Parents need conversational clarity tied to their child’s sky — not generic horoscopes.",
    emotionBeat: "Confidence rises when questions get warm, specific answers.",
    amynestSolution: "Birth Sky’s conversation sheet lets parents ask Amy Astro about the child’s sky snapshot — guided, premium-aware, parent-safe.",
    featureDemo: "Open conversation sheet → ask a parenting question → Amy Astro answers in context of the snapshot.",
    expectedChildOutcome: "Parenting choices become more thoughtful and less reactive.",
    parentBenefit: "You get answers rooted in your child’s portrait — not a feed of fear.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Chat sheet rise from bottom; soft cosmic UI chrome",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Warm hopeful pad",
    suggestedThumbnail: "“Ask Amy Astro” sheet; constellation chat bubble",
    suggestedOpeningScene: "Parent types a gentle question; Amy AI listens under starlight",
    suggestedEndingScene: "Helpful answer; end card",
    hookSubjects: ["ask Amy Astro", "birth sky questions", "parenting astrology chat"],
  },

  // ─── Routine Technology (5) ───────────────────────────────────
  {
    category: "Routine Technology",
    slug: "routine",
    title: "A Day Plan Your Whole Family Can See",
    topic: "Daily routines hub with today plan and completion tracking",
    targetAge: "1–12",
    targetParent: "Parents drowning in mental load",
    objective: "Show daily routines hub: today’s plan, week calendar, child chips, completion",
    featureId: "daily-routines",
    featureName: "Daily Routines Hub",
    featureSource: "artifacts/kidschedule/src/pages/routines/index.tsx",
    problem: "The day lives only in a parent’s head — until something snaps.",
    whyParentsFaceIt: "Mental load shrinks when the plan is visible, shared, and completable.",
    emotionBeat: "Routine success feels like calm you can check off.",
    amynestSolution: "AmyNest Daily Routines shows today’s plan, a week calendar, child chips, and completion tracking in one hub.",
    featureDemo: "Open Routines → see today’s plan → switch child chips → mark completions → glance at the week.",
    expectedChildOutcome: "Your child knows what comes next — less friction, more cooperation.",
    parentBenefit: "You offload the day from your brain into a living plan.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Clean UI glide across today plan; warm home background",
    suggestedEmotion: "Routine",
    suggestedMusic: "Steady hopeful pulse",
    suggestedThumbnail: "Today’s routine timeline with checkmarks; Amy AI",
    suggestedOpeningScene: "Chaotic morning dissolves into a clear Today plan",
    suggestedEndingScene: "Last item checked; end card",
    hookSubjects: ["daily routine app", "family day plan", "reduce mental load"],
  },
  {
    category: "Routine Technology",
    slug: "routine",
    title: "AI Routines That Fit Age, School, and Real Life",
    topic: "Personalized AI routine generation",
    targetAge: "1–12",
    targetParent: "Parents who need a plan that fits their actual household",
    objective: "Demonstrate AI routine generate from age, school, fridge, handlers, special plans",
    featureId: "daily-routines",
    featureName: "AI Routine Generate",
    featureSource: "artifacts/kidschedule/src/pages/routines/generate.tsx",
    problem: "Copied schedules fail the first day they meet your real fridge and school timings.",
    whyParentsFaceIt: "Useful routines must be personalized — age, school, household constraints included.",
    emotionBeat: "Hope when a plan finally looks like your life.",
    amynestSolution: "AmyNest generates personalized day plans from age, school, fridge, handlers, and special plans — then you can refine.",
    featureDemo: "Open Generate → enter household context → Amy builds a day plan → review and save to Today.",
    expectedChildOutcome: "Your child’s day fits their age and energy — not a generic template.",
    parentBenefit: "You start from a smart draft instead of a blank stressful page.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Form inputs → magical but calm plan materialization",
    suggestedEmotion: "Hope",
    suggestedMusic: "Soft build into organized melody",
    suggestedThumbnail: "Generate button → personalized timeline appear",
    suggestedOpeningScene: "Amy AI: “Tell me your real day.” Context chips light up.",
    suggestedEndingScene: "Plan ready; end card",
    hookSubjects: ["AI routine", "personalized schedule", "family planning"],
  },
  {
    category: "Routine Technology",
    slug: "routine",
    title: "Weather-Aware Plans — Because Outdoor Time Isn’t Guesswork",
    topic: "Live environment context in routine generation",
    targetAge: "2–12",
    targetParent: "Parents planning outdoor and indoor blocks",
    objective: "Show weather/outdoor allowance folded into routine generation",
    featureId: "environment",
    featureName: "Routine Environment Context",
    featureSource: "artifacts/kidschedule/src/pages/routines/routine-environment-ui.tsx",
    problem: "Perfect outdoor blocks collapse the moment rain or heat arrives.",
    whyParentsFaceIt: "Smart days adapt to environment — not fight it.",
    emotionBeat: "Confidence when the plan respects the weather.",
    amynestSolution: "AmyNest folds live environment context — weather and outdoor allowance — into routine generation.",
    featureDemo: "Open routine generation with environment context → see outdoor/indoor suggestions adjust with weather.",
    expectedChildOutcome: "Your child still gets movement and play — adapted to the day.",
    parentBenefit: "You stop rewriting the whole schedule when clouds roll in.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Weather icon morph outdoor block → cozy indoor play block",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Light weather-transition motif",
    suggestedThumbnail: "Sun/rain toggle over routine blocks",
    suggestedOpeningScene: "Rain starts; Amy AI soft-swaps outdoor slot to indoor adventure",
    suggestedEndingScene: "Day still works; end card",
    hookSubjects: ["weather routines", "outdoor time planning", "adaptive schedule"],
  },
  {
    category: "Routine Technology",
    slug: "routine",
    title: "Multi-Child Days Without the Schedule Collision",
    topic: "Household orchestration across children",
    targetAge: "1–12 (multi-child homes)",
    targetParent: "Parents managing more than one child’s day",
    objective: "Highlight multi-child conflict-aware household scheduling",
    featureId: "daily-routines",
    featureName: "Household Routine Orchestration",
    featureSource: "artifacts/kidschedule/src/pages/household",
    problem: "Two kids, one parent, three overlapping “musts” — chaos by 7:40 AM.",
    whyParentsFaceIt: "Households need conflict-aware planning, not separate wishlists.",
    emotionBeat: "Family bonding improves when the day stops feeling like triage.",
    amynestSolution: "AmyNest household orchestration supports multi-child, conflict-aware scheduling so the day can actually work.",
    featureDemo: "Open household view → see children together → generate/adjust for conflicts → save a shared workable day.",
    expectedChildOutcome: "Each child gets attention windows that don't constantly collide.",
    parentBenefit: "You parent one household — not two competing calendars.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl", "Amy Boy"],
    suggestedCameraStyle: "Split child chips merging into one household timeline",
    suggestedEmotion: "Family Bonding",
    suggestedMusic: "Warm collaborative theme",
    suggestedThumbnail: "Two child chips + one conflict-resolved timeline",
    suggestedOpeningScene: "Two schedules clash; Amy AI weaves them into one calm plan",
    suggestedEndingScene: "Household day looks doable; end card",
    hookSubjects: ["multi child schedule", "household planning", "sibling routines"],
  },
  {
    category: "Routine Technology",
    slug: "routine",
    title: "Patent-Pending Care for Dinner-to-Sleep Health Gaps",
    topic: "Routine Engine health guarantees and adaptive orchestration",
    targetAge: "Toddler–teen (age-aware gaps)",
    targetParent: "Parents serious about sleep-protecting schedules",
    objective: "Explain certified dinner-to-bedtime health gaps and patent-pending adaptive orchestration",
    featureId: "docs-routine-engine-frozen-files",
    featureName: "Routine Engine (Patent-Pending)",
    featureSource: "docs/routine-engine/v1-certified-architecture.md",
    problem: "Late dinners quietly steal children’s sleep — and parents don’t see the gap.",
    whyParentsFaceIt: "Healthy days need enforced dinner-to-sleep spacing by age — not hope.",
    emotionBeat: "Routine confidence when health logic protects bedtime.",
    amynestSolution: "AmyNest’s Routine Engine uses certified age-aware dinner-to-sleep health gaps and adaptive, context-aware orchestration described as patent-pending.",
    featureDemo: "Generate a routine → Engine repairs dinner anchors to protect minimum dinner-end → bedtime gaps by age band.",
    expectedChildOutcome: "Your child’s bedtime is protected by design — not luck.",
    parentBenefit: "You trust the plan’s health logic, not just its pretty timeline.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Timeline zoom on dinner→sleep gap; soft shield glow",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Steady trustworthy bed",
    suggestedThumbnail: "Dinner → Sleep gap shield; “health-aware routine”",
    suggestedOpeningScene: "Amy AI measures the dinner-to-sleep gap and gently repairs it",
    suggestedEndingScene: "Protected bedtime; patent-pending pill subtle; end card",
    hookSubjects: ["bedtime routine", "dinner-to-sleep timing", "sleep-protecting schedules"],
  },

  // ─── Amy Coach (5) ────────────────────────────────────────────
  {
    category: "Amy Coach",
    slug: "coach",
    title: "A Coaching Plan for the Goal You Actually Chose",
    topic: "Goal-based AI Coach plans",
    targetAge: "Depends on selected goal age-band",
    targetParent: "Parents who want guided coaching, not random tips",
    objective: "Show goal selection → Amy generates a coaching plan with listen/share/print",
    featureId: "ai-coach",
    featureName: "Amy AI Coach",
    featureSource: "artifacts/kidschedule/src/pages/ai-coach.tsx",
    problem: "Advice is everywhere — a plan for your goal is rare.",
    whyParentsFaceIt: "Parents need a path they can follow, not another overwhelming tip pile.",
    emotionBeat: "Hope when a goal becomes a clear next step.",
    amynestSolution: "Amy Coach lets you pick age-band goals; Amy generates a coaching plan you can listen to, share, or print.",
    featureDemo: "Open AI Coach → choose a goal → Amy generates the plan → listen/share/print for follow-through.",
    expectedChildOutcome: "Your child benefits from consistent coaching — not one-off advice.",
    parentBenefit: "You leave with a plan you can actually use this week.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Goal cards → plan document materialize; warm professional",
    suggestedEmotion: "Hope",
    suggestedMusic: "Encouraging coaching theme",
    suggestedThumbnail: "Goal selected + coaching plan preview",
    suggestedOpeningScene: "Amy AI: “What’s the goal?” Parent taps; plan unfolds.",
    suggestedEndingScene: "Plan ready to listen; end card",
    hookSubjects: ["parenting coach", "goal based plan", "Amy Coach"],
  },
  {
    category: "Amy Coach",
    slug: "coach",
    title: "First, Amy Understands — Then She Plans",
    topic: "Coach understanding screen before the plan",
    targetAge: "All ages (parent emotional safety)",
    targetParent: "Parents who feel unseen by generic advice",
    objective: "Highlight the understanding screen that acknowledges the situation before planning",
    featureId: "coach-understanding-screen",
    featureName: "Coach Understanding Screen",
    featureSource: "artifacts/kidschedule/src/pages/coach-understanding-screen.tsx",
    problem: "Jumping to tips before feeling understood makes parents shut down.",
    whyParentsFaceIt: "Emotional safety comes before behavior change.",
    emotionBeat: "Emotional growth starts with “you’re not alone in this.”",
    amynestSolution: "Before the plan, Amy Coach shows an understanding screen — Amy reflects your situation with care.",
    featureDemo: "Enter coaching flow → Understanding screen acknowledges the moment → then the plan appears.",
    expectedChildOutcome: "Parents show up calmer — and kids feel that calm.",
    parentBenefit: "You feel seen before you’re coached.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Soft intimate close-up; slow push; lavender grade",
    suggestedEmotion: "Emotional Growth",
    suggestedMusic: "Gentle empathy pad",
    suggestedThumbnail: "“Amy understands” screen; soft eye contact with Amy AI",
    suggestedOpeningScene: "Amy AI nods gently: “I understand what you’re carrying.”",
    suggestedEndingScene: "Transition to plan; end card",
    hookSubjects: ["feeling understood", "empathetic coaching", "Amy understands"],
  },
  {
    category: "Amy Coach",
    slug: "coach",
    title: "Track the Wins — Coaching Is a Journey",
    topic: "AI Coach progress and journey tracking",
    targetAge: "All ages (parent journey)",
    targetParent: "Parents who need to see progress over time",
    objective: "Show coach progress tracking wins across the coaching journey",
    featureId: "ai-coach-progress",
    featureName: "AI Coach Progress",
    featureSource: "artifacts/kidschedule/src/pages/ai-coach-progress.tsx",
    problem: "Without a journey view, parents forget how far they’ve come.",
    whyParentsFaceIt: "Motivation for hard parenting seasons needs visible wins.",
    emotionBeat: "Achievement for parents — progress you can point to.",
    amynestSolution: "Amy Coach Progress tracks wins and coaching progress over time — your journey, remembered.",
    featureDemo: "Open Coach Progress → review wins → see journey continuity → continue the plan.",
    expectedChildOutcome: "Consistency compounds because parents stay engaged.",
    parentBenefit: "You see proof that the work is working.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Progress path animation; warm milestone markers",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Soft triumph without hype",
    suggestedThumbnail: "Progress path with wins lit",
    suggestedOpeningScene: "Amy AI lights a win on the journey path",
    suggestedEndingScene: "Next milestone awaits; end card",
    hookSubjects: ["parenting progress", "coaching journey", "track wins"],
  },
  {
    category: "Amy Coach",
    slug: "coach",
    title: "Graduate a Goal — Then Choose What’s Next",
    topic: "Coach graduation: maintain, strengthen, or new goal",
    targetAge: "All ages (goal completion)",
    targetParent: "Parents finishing a coaching goal path",
    objective: "Celebrate graduation and next choices: maintain, strengthen, or new goal",
    featureId: "coach-graduation-screen",
    featureName: "Coach Graduation Screen",
    featureSource: "artifacts/kidschedule/src/pages/coach-graduation-screen.tsx",
    problem: "Finishing a goal can feel empty if there’s no celebration — or next step.",
    whyParentsFaceIt: "Healthy coaching closes loops and opens wise next choices.",
    emotionBeat: "Pride and hope meet at graduation.",
    amynestSolution: "Coach Graduation celebrates a finished goal path — then invites you to maintain, strengthen, or start a new goal.",
    featureDemo: "Complete a goal path → Graduation screen → choose Maintain / Strengthen / New Goal.",
    expectedChildOutcome: "Gains stick because parents choose how to sustain them.",
    parentBenefit: "You finish with clarity — not a cliff.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Gentle celebration confetti (tasteful); diploma-like glow",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Warm celebration swell into calm",
    suggestedThumbnail: "Graduation badge + three next-step choices",
    suggestedOpeningScene: "Amy AI: “You did it.” Graduation glow.",
    suggestedEndingScene: "Parent chooses Strengthen; end card",
    hookSubjects: ["goal graduation", "parenting wins", "what’s next"],
  },
  {
    category: "Amy Coach",
    slug: "coach",
    title: "Ask Amy — Sleep, Feeding, Learning, and More",
    topic: "Ask Amy assistant topic chat with daily limits",
    targetAge: "Infant–12 (topic dependent)",
    targetParent: "Parents who need quick, calm answers in the moment",
    objective: "Show Ask Amy assistant for topic chat with healthy daily AI query limits",
    featureId: "assistant",
    featureName: "Ask Amy Assistant",
    featureSource: "artifacts/kidschedule/src/pages/assistant.tsx",
    problem: "Midnight questions send parents into endless, conflicting search tabs.",
    whyParentsFaceIt: "Parents need a trusted place to ask — with boundaries that protect quality.",
    emotionBeat: "Confidence from a calm answer when you need it.",
    amynestSolution: "Ask Amy is a topic chat for sleep, feeding, learning, and more — with daily AI query limits that keep guidance intentional.",
    featureDemo: "Open Assistant → pick a topic → ask Amy → receive a warm, practical answer within daily limits.",
    expectedChildOutcome: "Parents respond with more clarity in the moment.",
    parentBenefit: "You get help without drowning in the internet.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Night-stand soft light; chat UI intimate",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Quiet reassuring night pad",
    suggestedThumbnail: "Ask Amy chat: “Sleep tips for tonight?”",
    suggestedOpeningScene: "Clock shows late; Amy AI: “I’m here — ask me.”",
    suggestedEndingScene: "Clear tip; end card",
    hookSubjects: ["ask Amy", "parenting questions", "sleep feeding help"],
  },

  // ─── Audio Lessons (5) ────────────────────────────────────────
  {
    category: "Audio Lessons",
    slug: "audio",
    title: "Lessons Kids Can Hear — Matched to Their Age",
    topic: "Audio Lessons library with age buckets and series progress",
    targetAge: "2–10",
    targetParent: "Parents who want learning during car rides and quiet time",
    objective: "Introduce Audio Lessons age-bucket library with series progress and multi-language text",
    featureId: "audio-lessons",
    featureName: "Audio Lessons Library",
    featureSource: "artifacts/kidschedule/src/pages/audio-lessons.tsx",
    problem: "Video isn’t always possible — but learning time still exists in the cracks of the day.",
    whyParentsFaceIt: "Ears-free moments (travel, wind-down) are perfect for age-right audio lessons.",
    emotionBeat: "Learning continues even when screens should rest.",
    amynestSolution: "AmyNest Audio Lessons offers age-bucket lessons, series progress, and multi-language lesson text.",
    featureDemo: "Open Audio Lessons → choose age bucket → start a lesson → see series progress update.",
    expectedChildOutcome: "Your child learns through listening — calmly and consistently.",
    parentBenefit: "You turn dead time into gentle learning time.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Car window light / cozy couch; waveform UI soft",
    suggestedEmotion: "Learning",
    suggestedMusic: "Lesson theme under narration headroom",
    suggestedThumbnail: "Headphones + age bucket chips; Amy Girl listening",
    suggestedOpeningScene: "Amy AI presses play on an age-matched lesson",
    suggestedEndingScene: "Series progress +1; end card",
    hookSubjects: ["audio lessons for kids", "learning by listening", "age matched audio"],
  },
  {
    category: "Audio Lessons",
    slug: "audio",
    title: "Amy’s Daily Pick — One Tap to Today’s Listen",
    topic: "Daily pick and quick play cards",
    targetAge: "2–10",
    targetParent: "Busy parents who don’t want to browse",
    objective: "Show daily pick and quick play for one-tap listening",
    featureId: "audio-lessons",
    featureName: "Audio Lessons Daily Pick",
    featureSource: "artifacts/kidschedule/src/components/audio-lessons/daily-pick-card.tsx",
    problem: "Choice overload kills the habit before the first play.",
    whyParentsFaceIt: "A single trusted pick beats twenty undecided thumbnails.",
    emotionBeat: "Routine success from one tap.",
    amynestSolution: "Audio Lessons includes Daily Pick and Quick Play — Amy chooses a listen for today.",
    featureDemo: "Open Audio Lessons → tap Daily Pick / Quick Play → audio starts immediately.",
    expectedChildOutcome: "Your child gets today’s listen without delay.",
    parentBenefit: "Zero decision fatigue — just press play.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Big friendly Daily Pick card; one-tap pulse",
    suggestedEmotion: "Routine",
    suggestedMusic: "Bright soft opener into lesson bed",
    suggestedThumbnail: "“Amy’s pick for today” card with play button",
    suggestedOpeningScene: "Amy AI: “I picked today’s listen.” Tap.",
    suggestedEndingScene: "Playing; end card",
    hookSubjects: ["daily audio pick", "quick play", "one tap lessons"],
  },
  {
    category: "Audio Lessons",
    slug: "audio",
    title: "Keep Browsing While the Lesson Plays",
    topic: "Persistent in-page audio player",
    targetAge: "2–10",
    targetParent: "Parents multitasking during lesson time",
    objective: "Highlight persistent player bar/sheet while browsing lessons",
    featureId: "audio-lessons",
    featureName: "Audio Lessons Player Bar",
    featureSource: "artifacts/kidschedule/src/components/audio-lessons/audio-player-bar.tsx",
    problem: "Leaving the player to browse breaks the listening spell.",
    whyParentsFaceIt: "Good audio UX lets families browse the next lesson while the current one plays.",
    emotionBeat: "Calm continuity — learning doesn’t interrupt itself.",
    amynestSolution: "Audio Lessons keeps a persistent player bar/sheet so listening continues while you browse.",
    featureDemo: "Start a lesson → player bar stays → browse other lessons → return without losing playback.",
    expectedChildOutcome: "Listening stays smooth; fewer restart fights.",
    parentBenefit: "You can prepare the next listen without stopping this one.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "UI focus on sticky player bar; smooth scroll behind",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Continuous soft bed demonstrating persistence",
    suggestedThumbnail: "Player bar over lesson library grid",
    suggestedOpeningScene: "Lesson plays; parent scrolls; player bar remains",
    suggestedEndingScene: "Next lesson queued; end card",
    hookSubjects: ["audio player", "listen while browsing", "kids audio UX"],
  },
  {
    category: "Audio Lessons",
    slug: "audio",
    title: "When Emotions Spike — Open Calm Audio Fast",
    topic: "Emergency calm sheet from Audio Lessons",
    targetAge: "2–10",
    targetParent: "Parents in meltdown or overstimulation moments",
    objective: "Show emergency calm sheet as quick calming audio entry",
    featureId: "audio-lessons",
    featureName: "Audio Lessons Emergency Calm",
    featureSource: "artifacts/kidschedule/src/components/audio-lessons/emergency-sheet.tsx",
    problem: "In a meltdown, nobody has time to search a library.",
    whyParentsFaceIt: "Regulation tools must be one gesture away.",
    emotionBeat: "Emotional growth supported by immediate calm audio.",
    amynestSolution: "From Audio Lessons, an emergency calm sheet opens quick calming audio — fast, gentle, available.",
    featureDemo: "Open Audio Lessons → Emergency calm → play calming audio immediately.",
    expectedChildOutcome: "Your child gets a soft landing sooner.",
    parentBenefit: "You have a calm button when words aren’t working.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Slow, soft; reduce visual noise; warm close",
    suggestedEmotion: "Emotional Growth",
    suggestedMusic: "Very soft calm bed — sparse",
    suggestedThumbnail: "Emergency calm sheet; soft heartbeat wave",
    suggestedOpeningScene: "Big feelings; Amy AI opens calm audio like a hug",
    suggestedEndingScene: "Breaths slower; end card",
    hookSubjects: ["calm audio for kids", "meltdown help", "emergency calm"],
  },
  {
    category: "Audio Lessons",
    slug: "audio",
    title: "Rhymes and Lullabies — Tap to Play Comfort",
    topic: "Nursery rhymes and lullabies catalog",
    targetAge: "0–6",
    targetParent: "Parents building bedtime and bonding rituals",
    objective: "Showcase rhymes/lullabies tap-to-play catalog",
    featureId: "rhymes-audio-ab",
    featureName: "Rhymes & Lullabies",
    featureSource: "artifacts/kidschedule/src/pages/rhymes.tsx",
    problem: "Bedtime needs a ritual — and parents are too tired to invent one nightly.",
    whyParentsFaceIt: "Familiar rhymes and lullabies create predictable comfort.",
    emotionBeat: "Family bonding in the quiet last minutes of the day.",
    amynestSolution: "AmyNest includes a tap-to-play nursery rhymes and lullabies catalog for comfort and bonding.",
    featureDemo: "Open Rhymes → tap a lullaby or rhyme → play → use as bedtime ritual.",
    expectedChildOutcome: "Your child settles with familiar sound comfort.",
    parentBenefit: "You get a reliable bedtime helper in one tap.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Night nursery warmth; soft vignette; gentle float",
    suggestedEmotion: "Family Bonding",
    suggestedMusic: "Actual lullaby-style bed (soft)",
    suggestedThumbnail: "Moon + lullaby play button; Amy Girl sleepy smile",
    suggestedOpeningScene: "Lights dim; Amy AI taps a lullaby",
    suggestedEndingScene: "Child resting; end card",
    hookSubjects: ["lullabies", "nursery rhymes", "bedtime audio"],
  },

  // ─── Parent Tips (5) ──────────────────────────────────────────
  {
    category: "Parent Tips",
    slug: "parent-tips",
    title: "Today for You — A Tip That Meets This Day",
    topic: "Daily Tips on the Parent Hub",
    targetAge: "All ages",
    targetParent: "Parents who want one useful tip — not twenty",
    objective: "Show Daily Tips / Today for you tiles on the parenting hub",
    featureId: "dashboard",
    featureName: "Daily Tips (Parent Hub)",
    featureSource: "artifacts/kidschedule/src/pages/parenting-hub.tsx",
    problem: "Parenting advice is infinite — attention is not.",
    whyParentsFaceIt: "One timely tip beats a feed of guilt.",
    emotionBeat: "Hope from a small, doable idea today.",
    amynestSolution: "AmyNest’s Parent Hub surfaces “Today for you” tip tiles — practical, daily, human.",
    featureDemo: "Open Parent Hub → read Today tip tile → take one action → move on with the day.",
    expectedChildOutcome: "Parents show up slightly wiser — daily.",
    parentBenefit: "You get guidance without drowning.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Hub tip tile hero; clean and premium",
    suggestedEmotion: "Hope",
    suggestedMusic: "Soft morning optimism",
    suggestedThumbnail: "“Today for you” tip card; coffee-side calm",
    suggestedOpeningScene: "Amy AI places today’s tip card in the parent’s hand (visually)",
    suggestedEndingScene: "Tip taken; end card",
    hookSubjects: ["daily parenting tip", "today for you", "parent hub"],
  },
  {
    category: "Parent Tips",
    slug: "parent-tips",
    title: "New Parent Tips — Age-Right Guidance for Early Days",
    topic: "New parent / infant caregiver tip sets",
    targetAge: "Infant–toddler",
    targetParent: "New parents and early caregivers",
    objective: "Highlight New Parent Tips by age group",
    featureId: "dashboard",
    featureName: "New Parent Tips",
    featureSource: "artifacts/kidschedule/src/components/new-parent-tips",
    problem: "Early parenthood is loud with advice — quiet with clarity.",
    whyParentsFaceIt: "New parents need age-group tips that match this week, not next year.",
    emotionBeat: "Confidence for the earliest, tender season.",
    amynestSolution: "AmyNest New Parent Tips offer age-group guidance for new and infant caregivers.",
    featureDemo: "Open New Parent Tips → select age group → read a focused tip → apply tonight.",
    expectedChildOutcome: "Babies and toddlers receive calmer, more informed care.",
    parentBenefit: "You feel less alone in the early days.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Soft nursery light; intimate parent-and-baby framing (tasteful)",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Very soft lullaby-adjacent bed",
    suggestedThumbnail: "New Parent Tips age chips; Amy AI gentle",
    suggestedOpeningScene: "Amy AI: “You’re new at this — here’s today’s age-right tip.”",
    suggestedEndingScene: "Tip card; end card",
    hookSubjects: ["new parent tips", "infant guidance", "early parenting"],
  },
  {
    category: "Parent Tips",
    slug: "parent-tips",
    title: "Dashboard Insights That Rotate With Your Life",
    topic: "Personalized dashboard insight chips and routine progress",
    targetAge: "All ages",
    targetParent: "Parents who check one home screen for the day",
    objective: "Show dashboard rotating insight chips + routine timeline progress",
    featureId: "dashboard",
    featureName: "Parent Dashboard Insights",
    featureSource: "artifacts/kidschedule/src/pages/dashboard.tsx",
    problem: "Apps bury the useful thing three taps deep.",
    whyParentsFaceIt: "Parents need a home that surfaces what matters today.",
    emotionBeat: "Routine clarity at a glance.",
    amynestSolution: "The AmyNest Dashboard rotates personalized insight chips and shows routine timeline progress in one place.",
    featureDemo: "Open Dashboard → read insight chip → scan routine timeline progress → act on the next item.",
    expectedChildOutcome: "The day moves with fewer dropped balls.",
    parentBenefit: "You open one screen and know what matters now.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Dashboard hero; insight chip pulse; timeline scrub",
    suggestedEmotion: "Routine",
    suggestedMusic: "Clean organized morning bed",
    suggestedThumbnail: "Dashboard with insight chip + timeline",
    suggestedOpeningScene: "Amy AI highlights today’s insight chip",
    suggestedEndingScene: "Next routine item clear; end card",
    hookSubjects: ["parent dashboard", "daily insights", "routine progress"],
  },
  {
    category: "Parent Tips",
    slug: "parent-tips",
    title: "Progress Insights From Real Routine History",
    topic: "Streaks and tip/warning insights from routines",
    targetAge: "All ages",
    targetParent: "Parents who want feedback rooted in their data",
    objective: "Show progress page streaks and tip/warning insights from routine history",
    featureId: "dashboard",
    featureName: "Progress & AI Insights",
    featureSource: "artifacts/kidschedule/src/pages/progress.tsx",
    problem: "Motivation fades when progress is invisible.",
    whyParentsFaceIt: "Families stick with routines when streaks and insights tell a true story.",
    emotionBeat: "Achievement when a streak reflects real life — not vanity metrics.",
    amynestSolution: "AmyNest Progress surfaces streaks and tip/warning insights drawn from routine history.",
    featureDemo: "Open Progress → see streak → read an insight tip or warning → adjust tomorrow’s plan.",
    expectedChildOutcome: "Consistency improves because parents course-correct early.",
    parentBenefit: "You get honest feedback without shame — and a clearer plan for tomorrow.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Progress charts soft; warning tips warm not red-alert fear",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Steady growth motif",
    suggestedThumbnail: "Streak flame + insight tip card",
    suggestedOpeningScene: "Amy AI: “Here’s what your week is teaching us.”",
    suggestedEndingScene: "Insight applied; end card",
    hookSubjects: ["routine streaks", "parent progress", "habit insights"],
  },
  {
    category: "Parent Tips",
    slug: "parent-tips",
    title: "Speech Guidance Cards Parents Can Use Tonight",
    topic: "Speech Coach parent guidance and dashboard",
    targetAge: "2–8",
    targetParent: "Parents supporting speech between sessions",
    objective: "Connect speech parent guidance cards + parent dashboard as actionable tips",
    featureId: "speech-coach-v2",
    featureName: "Speech Parent Guidance Cards",
    featureSource: "artifacts/kidschedule/src/features/speech-coach-v2/components/parent-dashboard.tsx",
    problem: "Speech practice ends — and parents don’t know what to reinforce at dinner.",
    whyParentsFaceIt: "Tiny home cues between sessions multiply progress.",
    emotionBeat: "Confidence from one clear caregiver action.",
    amynestSolution: "Speech Coach provides parent guidance cards and a parent dashboard so caregivers know what to practice next.",
    featureDemo: "After speech play → open parent guidance → read tonight’s tip → check dashboard progress.",
    expectedChildOutcome: "Speech gains continue in ordinary moments.",
    parentBenefit: "You become a calm co-coach — not a worried critic.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Guidance card hero; dinner-table soft cutaway",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Warm encouraging bed",
    suggestedThumbnail: "Guidance card: “Tonight, try…” + parent dashboard",
    suggestedOpeningScene: "Amy AI hands parent a guidance card after practice",
    suggestedEndingScene: "Tip used at home; end card",
    hookSubjects: ["speech tips for parents", "home practice", "guidance cards"],
  },

  // ─── Premium Features (5) ─────────────────────────────────────
  {
    category: "Premium Features",
    slug: "premium",
    title: "Premium Unlocks the Hubs Families Use Daily",
    topic: "Hub entitlements across Learning, Speech, Nutrition, Health Lab, and more",
    targetAge: "All ages",
    targetParent: "Parents ready for the full AmyNest toolkit",
    objective: "Explain premium hub unlocks: Learning, Activities, Speech, Nutrition, Health Lab, reports",
    featureId: "docs-discovery-worlds-premiumization-sprint",
    featureName: "AmyNest Premium Hub Entitlements",
    featureSource: "artifacts/kidschedule/src/lib/subscription-defaults.ts",
    problem: "Families outgrow free limits exactly when habits start working.",
    whyParentsFaceIt: "Premium should unlock real daily hubs — not empty badges.",
    emotionBeat: "Confidence when the full toolkit opens.",
    amynestSolution: "AmyNest Premium unlocks core hubs including Learning, Activities, Speech Coach, Nutrition, Health Lab, downloads/phonics workbook support, sleep coach, feeding roadmap, and weekly reports.",
    featureDemo: "View Premium entitlements → unlock hubs → open Speech/Nutrition/Health Lab/Learning without the free wall.",
    expectedChildOutcome: "Your child gets fuller daily access to the tools that help them grow.",
    parentBenefit: "One membership covers the hubs you actually use.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Hub icons unlock cascade; premium purple accent restrained",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Premium soft resolve",
    suggestedThumbnail: "Unlocked hubs constellation around AmyNest icon",
    suggestedOpeningScene: "Locked hubs glow; Amy AI unlocks them with care — not hype",
    suggestedEndingScene: "Hubs open; end card Download AmyNest AI",
    hookSubjects: ["AmyNest Premium", "unlock parenting hubs", "full access"],
  },
  {
    category: "Premium Features",
    slug: "premium",
    title: "More AI Routines When Free Caps Aren’t Enough",
    topic: "Premium routine generation beyond free limits",
    targetAge: "1–12",
    targetParent: "Parents generating routines for changing weeks",
    objective: "Show free routine caps vs premium expanded AI routine generation",
    featureId: "daily-routines",
    featureName: "Premium AI Routines",
    featureSource: "artifacts/kidschedule/src/components/routines/routine-premium-cta.tsx",
    problem: "Life changes weekly — two static routines can’t keep up.",
    whyParentsFaceIt: "Premium removes the generate paywall feeling when families need fresh plans.",
    emotionBeat: "Hope when planning isn’t rationed.",
    amynestSolution: "Free plans include capped routines; Premium expands AI routine generation so families can adapt as life changes.",
    featureDemo: "Hit a free routine limit → Premium unlocks further AI generate → create this week’s plan freely.",
    expectedChildOutcome: "Schedules stay age-right as school and seasons shift.",
    parentBenefit: "You regenerate plans without fighting a wall mid-week.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI"],
    suggestedCameraStyle: "Limit wall softens into open generate canvas",
    suggestedEmotion: "Hope",
    suggestedMusic: "Light unlock motif",
    suggestedThumbnail: "Routine generate unlocked; timeline abundance",
    suggestedOpeningScene: "Free cap reached; Amy AI opens Premium generate",
    suggestedEndingScene: "New week planned; end card",
    hookSubjects: ["unlimited routines", "premium AI schedule", "family planning"],
  },
  {
    category: "Premium Features",
    slug: "premium",
    title: "More Daily Plays — And Premium-Only Brain Games",
    topic: "Games premiumization: higher daily plays and exclusive titles",
    targetAge: "3–10",
    targetParent: "Parents whose kids love Games Hub",
    objective: "Contrast free 3 vs premium 12 daily plays and premium-only titles",
    featureId: "games",
    featureName: "Games Premium",
    featureSource: "artifacts/kidschedule/src/lib/games.ts",
    problem: "When a child is in a learning groove, a tiny daily cap can cut the joy short.",
    whyParentsFaceIt: "Premium extends healthy play with more daily rounds and exclusive titles — still structured.",
    emotionBeat: "Achievement with room to practice.",
    amynestSolution: "Games Premium raises daily plays (from free’s tighter cap toward twelve) and unlocks premium-only titles like Spot the Difference and Hidden Objects.",
    featureDemo: "Compare free plays remaining → Premium expands daily plays → open a premium-only game.",
    expectedChildOutcome: "Your child practices more of the games that build focus and observation.",
    parentBenefit: "More learning play without removing healthy structure.",
    suggestedDuration: "15s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Play counter rises; premium game tile unlock",
    suggestedEmotion: "Achievement",
    suggestedMusic: "Playful premium chime",
    suggestedThumbnail: "12 plays + Spot the Difference tile",
    suggestedOpeningScene: "Play limit expands; Amy Boy cheers; Amy AI keeps it kind",
    suggestedEndingScene: "Premium game starts; end card",
    hookSubjects: ["premium kids games", "more daily plays", "spot the difference"],
  },
  {
    category: "Premium Features",
    slug: "premium",
    title: "Worksheets and Nutrition Extras for Families Who Go Deeper",
    topic: "Worksheet Studio + Nutrition premium extras",
    targetAge: "2–12",
    targetParent: "Parents who want printables and deeper meal tools",
    objective: "Show Worksheet Studio and nutrition extras (e.g. tiffin week / library) as premium depth",
    featureId: "worksheet-studio",
    featureName: "Worksheet Studio & Nutrition Premium Extras",
    featureSource: "artifacts/kidschedule/src/pages/worksheet.tsx",
    problem: "Some weeks need printables and meal depth — not just the free surface.",
    whyParentsFaceIt: "Premium should deepen school and food tools families rely on.",
    emotionBeat: "Confidence from richer tools on hard weeks.",
    amynestSolution: "Premium supports Worksheet Studio generation workflows and Nutrition extras such as deeper tiffin/week planning and library downloads.",
    featureDemo: "Open Worksheet Studio under Premium → generate class worksheet → open Nutrition extras for richer weekly planning.",
    expectedChildOutcome: "Practice sheets and meals support real school weeks.",
    parentBenefit: "You get depth when the week demands it.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Girl"],
    suggestedCameraStyle: "Worksheet + tiffin plan dual reveal",
    suggestedEmotion: "Confidence",
    suggestedMusic: "Organized upbeat soft",
    suggestedThumbnail: "Worksheet + nutrition week plan side by side",
    suggestedOpeningScene: "Amy AI lays a worksheet and a tiffin plan on the family table",
    suggestedEndingScene: "Tools ready; end card",
    hookSubjects: ["premium worksheets", "tiffin planning", "deeper nutrition tools"],
  },
  {
    category: "Premium Features",
    slug: "premium",
    title: "Discovery Worlds Retention — Map, Stickers, Parent Dashboard",
    topic: "Premiumized Discovery Worlds engagement layer",
    targetAge: "3–9",
    targetParent: "Parents investing in long-term learning worlds",
    objective: "Highlight daily adventures, learning map, stickers, achievements, unified parent dashboard",
    featureId: "discovery-worlds-hub",
    featureName: "Discovery Worlds Premium Retention Layer",
    featureSource: "docs/discovery-worlds-premiumization-sprint.md",
    problem: "Worlds are magical — retention needs a progress story parents can trust.",
    whyParentsFaceIt: "Premium engagement should mean mastery, stickers, and parent insight — not noise.",
    emotionBeat: "Family bonding through a journey you can see together.",
    amynestSolution: "Discovery Worlds’ premiumized layer includes daily adventures, learning map, stickers, achievements, and a unified parent dashboard.",
    featureDemo: "Open Discovery Worlds → daily adventure → sticker/achievement update → parent dashboard insight.",
    expectedChildOutcome: "Your child stays on a mastery path across worlds.",
    parentBenefit: "You see retention as learning — not endless scrolling.",
    suggestedDuration: "20s",
    suggestedCharacters: ["Amy AI", "Amy Boy"],
    suggestedCameraStyle: "Map → sticker → parent dashboard triptych",
    suggestedEmotion: "Family Bonding",
    suggestedMusic: "Wonder theme resolving warmly",
    suggestedThumbnail: "Learning map + sticker + parent insight chips",
    suggestedOpeningScene: "Amy AI opens the mastery map like a storybook",
    suggestedEndingScene: "Parent dashboard smile; end card Download AmyNest AI",
    hookSubjects: ["discovery worlds premium", "learning map", "parent insights"],
  },
];

export function allGoldenSeeds(): GoldenSeed[] {
  return [...GOLDEN_SEEDS, ...GOLDEN_SEEDS_PART2];
}
