/**
 * AmyNest YouTube Content Automation Engine
 * Phase 1: topics, calendar, rotation, config
 * Phase 2: provider-agnostic content package generation
 * Phase 3: deterministic visual storyboard planning
 * Phase 4: provider-agnostic asset orchestration
 * Phase 5: provider-agnostic media rendering (RenderPackage)
 * Phase 6: provider-agnostic publishing (PublishedVideo)
 * Phase 7: autonomous workflow orchestration across Phases 1–6
 * Phase 8: analytics and growth intelligence (AnalyticsReport)
 * Phase 9: autonomous AI decision / campaign brain (CampaignPlan)
 * Phase 10: production readiness & operations (bootstrap, health, recovery)
 */

export * from "./types/index.js";
export {
  DEFAULT_ANALYTICS_SETTINGS,
  DEFAULT_ASSET_ENGINE_SETTINGS,
  DEFAULT_BRAIN_SETTINGS,
  DEFAULT_CONFIG_PATH,
  DEFAULT_GENERATION_SETTINGS,
  DEFAULT_OPERATIONS_SETTINGS,
  DEFAULT_PUBLISHING_SETTINGS,
  DEFAULT_RENDER_ENGINE_SETTINGS,
  DEFAULT_STORYBOARD_SETTINGS,
  DEFAULT_WORKFLOW_SETTINGS,
  assertValidUploadTime,
  isDayOfWeek,
  loadConfigFromJson,
  loadDefaultConfig,
  loadResolvedAnalyticsConfig,
  loadResolvedAssetEngineConfig,
  loadResolvedBrainConfig,
  loadResolvedConfig,
  loadResolvedOpsConfig,
  loadResolvedPublishingConfig,
  loadResolvedRenderEngineConfig,
  loadResolvedStoryboardConfig,
  loadResolvedWorkflowConfig,
  resolveAnalyticsSettings,
  resolveAssetEngineSettings,
  resolveBrainSettings,
  resolveGenerationSettings,
  resolveOperationsSettings,
  resolvePublishingSettings,
  resolveRenderEngineSettings,
  resolveStoryboardSettings,
  resolveVideosPerDay,
  resolveWorkflowSettings,
} from "./config/index.js";
export {
  DEFAULT_WEEK_CALENDAR,
  addUtcDays,
  buildDayPlans,
  buildUploadTimestamp,
  formatIsoDate,
  getDayOfWeek,
  getDefaultWeekCalendar,
  listDateRange,
  parseIsoDate,
  resolveSlotsForDay,
  type DayPlan,
} from "./calendar/index.js";
export {
  TOPIC_COUNT,
  TOPIC_DATABASE,
  getAllTopics,
  getTopicById,
  getTopicsByAgeGroup,
  getTopicsByCategory,
  getTopicsByVideoStyle,
  listCategoriesPresent,
} from "./topics/index.js";
export {
  ContentPackageService,
  InMemoryHistoryStore,
  daysBetweenUtc,
  getEligibleTopics,
  prioritizeUnused,
  scheduleContent,
  selectTopic,
  validateConfig,
  validateTopic,
  validateTopics,
  validateWeekCalendar,
  wasUsedWithinWindow,
  type ContentGenerationResult,
  type ContentPackageServiceOptions,
  type HistoryStore,
  type ScheduleOptions,
} from "./services/index.js";
export {
  PROMPT_BLUEPRINTS,
  PROMPT_LIBRARY,
  getPromptBlueprint,
  getPromptTemplate,
  getPromptTemplatesByFamily,
  renderPromptTemplate,
  resolvePromptFamily,
  type PromptFamily,
  type PromptTemplate,
} from "./prompts/index.js";
export {
  VIDEO_TEMPLATES,
  getTemplatesByStyle,
  getVideoTemplate,
} from "./templates/index.js";
export {
  ContentEngineError,
  FutureProvider,
  MockProvider,
  OpenAIProvider,
  ProviderRegistry,
  createDefaultProviderRegistry,
  isContentEngineError,
  toContentEngineError,
  type AIGenerateRequest,
  type AIGenerateResult,
  type AIHealthStatus,
  type AIProvider,
  type AITokenUsage,
  type ContentEngineErrorCode,
  type MockProviderOptions,
  type OpenAIProviderOptions,
  type ProviderRegistryOptions,
} from "./ai/index.js";
export {
  assembleDescription,
  classifyTag,
  generateScriptPayload,
  isClickbaitTitle,
  normalizeDescriptionParts,
  parseGeneratedScriptPayload,
  refineHashtags,
  refineTitleSet,
  type HashtagTier,
  type RankedHashtag,
  type ScriptGenerationResult,
} from "./script/index.js";
export { calculateSeoScore, type SeoScoreInput } from "./seo/index.js";
export { buildCaptions } from "./captions/index.js";
export {
  clampTarget,
  estimateSpeakingSeconds,
  refineVoiceScript,
} from "./voice/index.js";
export {
  MODERATION_RULES,
  buildModerationRewriteHint,
  moderatePayload,
  moderateText,
} from "./moderation/index.js";
export { calculateQualityScore, type QualityScoreInput } from "./scoring/index.js";
export {
  InMemoryContentCache,
  buildContentCacheKey,
  type CacheEntry,
  type ContentCache,
} from "./cache/index.js";
export {
  InMemoryTelemetrySink,
  createTelemetryEvent,
  type TelemetryEvent,
  type TelemetrySink,
} from "./telemetry/index.js";
export {
  StoryboardPlanner,
  buildBrandingPlan,
  buildCaptionPlan,
  buildMusicPlan,
  buildVoicePlan,
  type StoryboardPlanResult,
  type StoryboardPlannerOptions,
} from "./storyboard/index.js";
export {
  applyTimelineDurations,
  assertTimelineIntegrity,
  buildTimeline,
  resolveSupportedDuration,
} from "./timeline/index.js";
export {
  buildSceneBlueprints,
  buildScenes,
  type SceneBlueprint,
} from "./scenes/index.js";
export { buildCameraPlan } from "./camera/index.js";
export { buildTransitionPlan } from "./transitions/index.js";
export { buildOverlayPlan } from "./overlays/index.js";
export { buildAnimationPlan } from "./animation/index.js";
export {
  collectAssets,
  planAssetRequirements,
  type AssetPlanInput,
} from "./assets/index.js";
export { validateStoryboard } from "./validation/index.js";
export * from "./brand/index.js";
export * from "./studio/index.js";
export * from "./golden-scripts/index.js";
export * from "./scene-composer/index.js";
export * from "./ai-director/index.js";
export * from "./content-intelligence/index.js";
export { exportStoryboard, toYaml } from "./export/index.js";
export {
  AssetOrchestrator,
  AssetProviderRegistry,
  BaseAssetProvider,
  FutureAiProvider,
  IllustrationProvider,
  InMemoryAssetCache,
  LocalLibraryProvider,
  PlaceholderProvider,
  ScreenRecordingProvider,
  assetPackageToYaml,
  buildAssetManifest,
  buildBrandingAssets,
  createDefaultAiProviders,
  createDefaultAssetRegistry,
  exportAssetPackage,
  fingerprintAssetRequest,
  fingerprintSimilarity,
  listLocalLibraryEntries,
  matchesAspectRatio,
  parseResolution,
  planAssetRequests,
  resolutionForAspect,
  resolveAssetRequests,
  validateAssetPackage,
  type AssetCacheEntry,
  type AssetCacheStore,
  type AssetOrchestrationResult,
  type AssetOrchestratorOptions,
  type AssetProvider,
  type AssetProviderRegistryOptions,
  type FutureAiProviderOptions,
  type ResolveAssetsOptions,
  type ResolveAssetsResult,
} from "./asset-engine/index.js";
export {
  FFmpegRenderer,
  FutureRenderer,
  InMemoryRenderCache,
  MockRenderer,
  ProgressTracker,
  RemotionRenderer,
  RenderOrchestrator,
  RenderProviderRegistry,
  buildAudioMixPlan,
  buildCompositionPlan,
  buildFfmpegCommand,
  buildFrameTimeline,
  buildRemotionCompositionProps,
  buildRenderFingerprint,
  buildSubtitlePlan,
  buildTransitionSpecs,
  buildWatermarkSpec,
  composeVisualLayers,
  createDefaultRenderRegistry,
  exportRenderPackage,
  isFfmpegAvailable,
  renderPackageToYaml,
  toAss,
  toSrt,
  validateAudioSync,
  validateCompositionPlan,
  validateRenderPackage,
  wrapSubtitle,
  writeRemotionCompositionFile,
  writeSubtitleFiles,
  type ProgressListener,
  type RenderCacheEntry,
  type RenderCacheStore,
  type RenderOrchestrationResult,
  type RenderOrchestratorOptions,
  type RenderProvider,
  type RenderProviderRegistryOptions,
} from "./render-engine/index.js";
export {
  AuditLog,
  FuturePublishingProvider,
  InMemoryNotificationBus,
  InMemoryPublishStore,
  MockPublishingProvider,
  PublishingError,
  PublishingOrchestrator,
  PublishingProviderRegistry,
  YouTubePublishingProvider,
  buildPublishMetadata,
  buildPublishingTelemetry,
  buildSchedulePlan,
  computeBackoff,
  createDefaultPublishingRegistry,
  createDefaultTransports,
  exportPublishedVideo,
  isPublishingError,
  publishedVideoToYaml,
  resolveScheduledPublishAt,
  resolveThumbnail,
  toPublishingError,
  verifyPublishedVideo,
  withRetries,
  type BuildScheduleInput,
  type MockPublishingProviderOptions,
  type NotificationTransport,
  type PublishPersistenceStore,
  type PublishingOrchestrationResult,
  type PublishingOrchestratorOptions,
  type PublishingProvider,
  type PublishingProviderRegistryOptions,
  type RetryPolicy,
  type RetryResult,
  type YouTubePublishingProviderOptions,
} from "./publishing/index.js";
export {
  CHECKPOINT_ORDER,
  InMemoryWorkflowStore,
  WorkflowNotificationBus,
  WorkflowOrchestrator,
  WorkflowQueue,
  artifactsForResume,
  buildExecutionReport,
  buildScheduledJob,
  buildWorkflowTelemetry,
  canSkipToPhase,
  checkpointIndex,
  completePhaseTiming,
  computeWorkflowBackoff,
  createCheckpoint,
  createPipelineServices,
  createVideoUnit,
  cronMatches,
  describeTrigger,
  exportWorkflowResult,
  hasCheckpoint,
  mapWithConcurrency,
  nextPhaseAfterCheckpoint,
  prepareRecovery,
  recoverUnit,
  runSequential,
  runVideoPipeline,
  selectTopicsForJob,
  startPhaseTiming,
  withWorkflowRetry,
  workflowResultToYaml,
  type CronMatchInput,
  type PipelineServices,
  type WorkflowNotification,
  type WorkflowOrchestrationResult,
  type WorkflowOrchestratorOptions,
  type WorkflowPersistenceStore,
  type WorkflowQueueOptions,
  type WorkflowScheduleSpec,
} from "./workflow/index.js";
export {
  AnalyticsOrchestrator,
  AnalyticsProviderRegistry,
  FutureAnalyticsProvider,
  InMemoryAnalyticsStore,
  MockAnalyticsProvider,
  YouTubeAnalyticsProvider,
  aggregateVideoMetrics,
  analyticsReportToYaml,
  buildAnalyticsTelemetry,
  buildChannelSummary,
  buildLearningSnapshot,
  buildOptimizationSignals,
  buildPeriodReport,
  buildRecommendations,
  buildVideoSummaries,
  collectAnalytics,
  createDefaultAnalyticsRegistry,
  detectTrends,
  exportAnalyticsReport,
  mergeChannelWithAggregate,
  preferredCategoriesFromLearning,
  rankVideosByViews,
  scoreContent,
  scoreTopic,
  type AggregatedVideoMetrics,
  type AnalyticsOrchestrationResult,
  type AnalyticsOrchestratorOptions,
  type AnalyticsPersistenceStore,
  type AnalyticsProvider,
  type AnalyticsProviderRegistryOptions,
  type ContentScoreInput,
  type MockAnalyticsProviderOptions,
  type TopicScoreInput,
  type TrendInputVideo,
  type YouTubeAnalyticsProviderOptions,
} from "./analytics/index.js";
export {
  BrainOrchestrator,
  FutureTrendProvider,
  GoogleTrendsProvider,
  MockTrendProvider,
  TrendProviderRegistry,
  YouTubeTrendsProvider,
  activeSeasonalEvents,
  aggregateExpectedPerformance,
  boostTopicsWithTrends,
  buildBrainRecommendations,
  buildBrainTelemetry,
  buildContentMemory,
  buildOptimizationDecision,
  buildPublishingCalendar,
  buildPublishingSchedule,
  campaignPlanToYaml,
  collectExperimentResults,
  createDefaultTrendRegistry,
  exportCampaignPlan,
  listSeasonalEvents,
  planCampaignSeries,
  planExperiments,
  predictPerformance,
  rankCampaigns,
  rankCategories,
  rankCtas,
  rankHooks,
  rankPublishingSlots,
  rankTopics,
  type BrainOrchestrationResult,
  type BrainOrchestratorOptions,
  type GoogleTrendsProviderOptions,
  type PredictionInput,
  type TrendProvider,
  type TrendProviderRegistryOptions,
  type TrendQuery,
  type YouTubeTrendsProviderOptions,
} from "./brain/index.js";
export {
  BackupEngine,
  FileOperationsStore,
  InMemoryOperationsStore,
  OperationsOrchestrator,
  OpsNotificationBus,
  OpsScheduler,
  RecoveryEngine,
  StructuredLogger,
  applyEnvironmentOverrides,
  bootstrapOperations,
  buildDiagnosticReport,
  buildOpsTelemetry,
  collectHealthReport,
  collectRuntimeMetrics,
  createDefaultOpsTransports,
  createOperationsOrchestrator,
  createStructuredLogger,
  exportDiagnosticReport,
  loadLayeredConfiguration,
  maskSecret,
  parseEnvironment,
  redactSecretsFromText,
  loadAmyNestEnvFiles,
  loadEnvFiles,
  runOpsCliCommand,
  runProductionAcceptance,
  runProductionPipeline,
  validateProductionReadiness,
  validateSecrets,
  type AcceptanceOptions,
  type BootstrapOptions,
  type BootstrapResult,
  type ConfigurationLoadOptions,
  type HealthCheckOptions,
  type LoadedConfiguration,
  type MetricsCollectorOptions,
  type OperationsDoctorResult,
  type OperationsOrchestratorOptions,
  type OperationsPersistenceStore,
  type OpsCliCommand,
  type OpsNotificationBusOptions,
  type OpsSchedulerOptions,
  type ProductionValidationOptions,
  type SecretsValidationOptions,
  type StructuredLoggerOptions,
} from "./operations/index.js";
