import { describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { RoutineLivingDashboard } from "./routine-living-dashboard";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (_key: string, opts?: { defaultValue?: string; name?: string }) => {
      const value = opts?.defaultValue ?? _key;
      if (opts?.name && value.includes("{{name}}")) {
        return value.replaceAll("{{name}}", opts.name);
      }
      return value;
    },
  }),
}));

describe("RoutineLivingDashboard", () => {
  it("empty state is a living room, not an AI planner", () => {
    render(
      <RoutineLivingDashboard
        childName="John"
        childrenList={[
          { id: 1, name: "John" },
          { id: 2, name: "Child 2" },
        ]}
        activeChildId={1}
        onSelectChild={vi.fn()}
        hasPlan={false}
        onPrimary={vi.fn()}
      />,
    );

    expect(screen.getByTestId("routine-living-dashboard")).toBeInTheDocument();
    expect(screen.getByTestId("routine-living-dashboard")).not.toHaveClass("parent-hub-premium");
    expect(screen.getByTestId("routine-living-dashboard-empty")).toHaveTextContent(
      "No plan for today yet",
    );
    expect(screen.getByTestId("routine-living-child-context")).toHaveClass("rg-dash-family");
    expect(screen.getByTestId("routines-primary-cta")).toHaveClass("rg-dash-cta");
    expect(screen.getByTestId("routines-primary-cta")).toHaveTextContent("Build today's plan");
    expect(screen.queryByText(/generate routine/i)).toBeNull();
    expect(screen.getByRole("button", { name: "Child 2" })).toHaveAttribute("aria-pressed", "false");
    expect(screen.getByRole("button", { name: "John" })).toHaveAttribute("aria-pressed", "true");
    expect(screen.queryByText(/daily schedules generated by ai/i)).toBeNull();
    expect(screen.queryByText(/^Schedule$/)).toBeNull();
  });

  it("child switching stays available as quiet family context", async () => {
    const onSelectChild = vi.fn();
    const { userEvent } = await import("@testing-library/user-event");
    const user = userEvent.setup();
    render(
      <RoutineLivingDashboard
        childName="John"
        childrenList={[
          { id: 1, name: "John" },
          { id: 2, name: "Child 2" },
        ]}
        activeChildId={1}
        onSelectChild={onSelectChild}
        hasPlan={false}
        onPrimary={vi.fn()}
      />,
    );

    await user.click(screen.getByRole("button", { name: "Child 2" }));
    expect(onSelectChild).toHaveBeenCalledWith(2);
  });

  it("existing plan leads with today and Begin today", () => {
    render(
      <RoutineLivingDashboard
        childName="John"
        childrenList={[{ id: 1, name: "John" }]}
        activeChildId={1}
        onSelectChild={vi.fn()}
        hasPlan
        firstAction={{ time: "07:30", activity: "Quiet breakfast" }}
        arcPreview={[
          { time: "07:30", label: "Quiet breakfast" },
          { time: "08:00", label: "Get dressed" },
        ]}
        onPrimary={vi.fn()}
        onRebuild={vi.fn()}
      />,
    );

    expect(screen.getByTestId("routine-living-dashboard-plan")).toHaveTextContent("Today");
    expect(screen.getByTestId("routines-primary-cta")).toHaveTextContent("Begin today");
    expect(screen.getByTestId("routines-living-rebuild")).toHaveTextContent(
      "Rebuild today's plan",
    );
  });
});
