/**
 * Builds static spelling manifest JSON + TypeScript index from word seeds.
 * Run: pnpm --filter @workspace/spelling-catalog run build:manifest
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { enrichWord } from "../src/enrich.ts";
import {
  SPELLING_AGE_GROUPS,
  SPELLING_DIFFICULTIES,
  WORD_SEEDS,
} from "../src/seeds/word-banks.ts";
import type { SpellingBucketKey, SpellingManifest } from "../src/types.ts";
import { bucketKey } from "../src/types.ts";

const __dir = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dir, "..");
const dataDir = join(pkgRoot, "data");

mkdirSync(dataDir, { recursive: true });

const buckets = {} as SpellingManifest["buckets"];
const bucketCounts = {} as Record<SpellingBucketKey, number>;

for (const age of SPELLING_AGE_GROUPS) {
  for (const diff of SPELLING_DIFFICULTIES) {
    const seeds = WORD_SEEDS[age][diff];
    const total = seeds.length;
    const entries = seeds.map((word, rank) => enrichWord(word, age, diff, rank, total));
    const key = bucketKey(age, diff);
    buckets[key] = entries;
    bucketCounts[key] = entries.length;
  }
}

const manifest: SpellingManifest = {
  meta: {
    version: 1,
    generatedAt: new Date().toISOString(),
    bucketCounts,
  },
  buckets,
};

const manifestPath = join(dataDir, "manifest.json");
writeFileSync(manifestPath, JSON.stringify(manifest));

const totalWords = Object.values(bucketCounts).reduce((a, b) => a + b, 0);
console.log(`Wrote ${manifestPath} (${totalWords} words across ${Object.keys(bucketCounts).length} buckets)`);

// Lightweight TS re-export for bundlers (avoids parsing huge JSON at typecheck in some setups).
const indexTs = `/** Auto-generated by scripts/build-manifest.ts — do not edit. */
import type { SpellingManifest } from "../src/types.js";
import manifestJson from "./manifest.json" with { type: "json" };

export const SPELLING_MANIFEST: SpellingManifest = manifestJson as SpellingManifest;
export const SPELLING_MANIFEST_VERSION = ${manifest.meta.version};
`;

writeFileSync(join(dataDir, "index.ts"), indexTs);
